/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4f8b2924-a21e-4fcf-b719-72ff26534ef8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved the general formula for the Frullani integral:
$\int_0^\infty \frac{f(ax) - f(bx)}{x} dx = (f(0) - f(\infty)) \ln(b/a)$.
The proof relies on splitting the integral, using substitution, and taking limits at 0 and infinity using the provided and proven lemmas.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f911456e-0c00-4034-a857-cf39c0ef1901

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Lemma: The integral $\int_a^b \frac{f(uT) - f(0)}{u} du$ tends to 0 as $T \to 0^+$.
-/
theorem frullani_limit_zero_lemma {f : ℝ → ℝ} {a b : ℝ} (ha : 0 < a) (hb : 0 < b)
    (hf : ContinuousAt f 0) :
    Filter.Tendsto (fun T => ∫ u in a..b, (f (u * T) - f 0) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
      -- First use the fact that $f$ is continuous at $0$ to find a bound for $|f(uT) - f(0)|$.
      have h_bound : ∀ ε > 0, ∃ δ > 0, ∀ T, 0 < T ∧ T < δ → ∀ u ∈ Set.Icc (min a b) (max a b), abs ((f (u * T)) - (f 0)) < ε := by
        intros ε hε_pos
        obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, ∀ x, abs x < δ → abs (f x - f 0) < ε := by
          simpa using Metric.continuousAt_iff.mp hf ε hε_pos;
        exact ⟨ δ / ( Max.max a b ), div_pos hδ_pos ( by positivity ), fun T hT u hu => hδ _ <| by rw [ abs_lt ] ; constructor <;> cases max_cases a b <;> cases min_cases a b <;> nlinarith [ hu.1, hu.2, mul_div_cancel₀ δ ( by positivity : ( Max.max a b ) ≠ 0 ) ] ⟩;
      -- Use the bound to show that the integral tends to 0.
      have h_integral_bound : ∀ ε > 0, ∃ δ > 0, ∀ T, 0 < T ∧ T < δ → abs (∫ u in a..b, (f (u * T) - f 0) / u) ≤ ε * abs (∫ u in a..b, 1 / u) := by
        intro ε hε; obtain ⟨ δ, hδ, H ⟩ := h_bound ε hε; use δ, hδ; intros T hT; cases le_total a b <;> simp_all +decide [ intervalIntegral, abs_mul, abs_div ];
        · -- Apply the bound to the integral.
          have h_integral_bound : abs (∫ u in Set.Ioc a b, (f (u * T) - f 0) / u) ≤ ∫ u in Set.Ioc a b, ε / abs u := by
            refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( MeasureTheory.integral_mono_of_nonneg _ _ _ );
            · exact Filter.Eventually.of_forall fun x => norm_nonneg _;
            · exact ContinuousOn.integrableOn_Icc ( by exact continuousOn_of_forall_continuousAt fun u hu => ContinuousAt.div continuousAt_const ( continuousAt_id.abs ) ( ne_of_gt ( abs_pos.mpr ( by linarith [ hu.1 ] ) ) ) ) |> fun h => h.mono_set ( Set.Ioc_subset_Icc_self );
            · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with u hu using by simpa [ abs_div ] using div_le_div_of_nonneg_right ( le_of_lt ( H T hT.1 hT.2 u hu.1.le hu.2 ) ) ( abs_nonneg u ) ;
          refine le_trans h_integral_bound ?_;
          rw [ abs_of_nonneg ( MeasureTheory.setIntegral_nonneg ( by norm_num ) fun x hx => inv_nonneg.2 ( by linarith [ hx.1 ] ) ) ] ; norm_num [ div_eq_mul_inv, MeasureTheory.integral_const_mul ] ; ring_nf;
          exact mul_le_mul_of_nonneg_left ( le_of_eq ( MeasureTheory.setIntegral_congr_fun measurableSet_Ioc fun x hx => by rw [ abs_of_nonneg ( by linarith [ hx.1 ] ) ] ) ) hε.le;
        · refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _ );
          refine' fun u => ε / |u|;
          · exact Filter.Eventually.of_forall fun x => norm_nonneg _;
          · exact ContinuousOn.integrableOn_Icc ( by exact continuousOn_of_forall_continuousAt fun u hu => ContinuousAt.div continuousAt_const ( continuousAt_id.abs ) ( ne_of_gt ( abs_pos.mpr ( by linarith [ hu.1 ] ) ) ) ) |> fun h => h.mono_set ( Set.Ioc_subset_Icc_self );
          · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with u hu using by simpa [ abs_div ] using div_le_div_of_nonneg_right ( le_of_lt ( H T hT.1 hT.2 u hu.1.le hu.2 ) ) ( abs_nonneg u ) ;
          · rw [ MeasureTheory.setIntegral_congr_fun measurableSet_Ioc fun x hx => by rw [ abs_of_nonneg ( by linarith [ hx.1 ] ) ] ] ; norm_num [ div_eq_mul_inv, MeasureTheory.integral_const_mul ];
            exact mul_le_mul_of_nonneg_left ( le_abs_self _ ) hε.le;
      norm_num +zetaDelta at *;
      refine' Metric.tendsto_nhdsWithin_nhds.mpr _;
      intro ε hε; rcases h_integral_bound ( ε / ( |∫ u in a..b, u⁻¹| + 1 ) ) ( div_pos hε ( by positivity ) ) with ⟨ δ, hδ, H ⟩ ; exact ⟨ δ, hδ, fun { x } hx₁ hx₂ => by rw [ dist_zero_right ] ; exact lt_of_le_of_lt ( H x hx₁ ( by linarith [ abs_lt.mp hx₂ ] ) ) ( by nlinarith [ abs_nonneg ( ∫ u in a..b, u⁻¹ ), mul_div_cancel₀ ε ( by positivity : ( |∫ u in a..b, u⁻¹| + 1 ) ≠ 0 ) ] ) ⟩ ;

/-
Lemma: $\int_{aT}^{bT} \frac{f(x)}{x} dx = \int_a^b \frac{f(uT)}{u} du$ for $T > 0$.
-/
theorem frullani_substitution_lemma {f : ℝ → ℝ} {a b T : ℝ} (hT : 0 < T) :
    ∫ x in a * T..b * T, f x / x = ∫ u in a..b, f (u * T) / u := by
      -- Apply the substitution $x = uT$ to the integral.
      have h_subst : ∀ a b : ℝ, ∫ x in a..b, f x / x = ∫ u in (a / T).. (b / T), f (u * T) / (u * T) * T := by
        simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, intervalIntegral.integral_comp_mul_right, hT.ne' ];
        intro a b; convert intervalIntegral.integral_comp_div _ _ using 3 <;> ring ; norm_num [ hT.ne' ] ;
        · ring ; norm_num [ hT.ne' ];
        · positivity;
      convert h_subst ( a * T ) ( b * T ) using 1 ; ring_nf ; norm_num [ hT.ne' ];
      simp +decide [ mul_assoc, mul_comm T, hT.ne' ]

/-
Lemma: $\int_a^b \frac{C}{u} du = C \ln(b/a)$.
-/
theorem frullani_constant_term {a b C : ℝ} (ha : 0 < a) (hb : 0 < b) :
    ∫ u in a..b, C / u = C * Real.log (b / a) := by
      simp +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, ha, hb, Real.log_div, ne_of_gt ]

/-
The integral $\int_a^b \frac{f(uT) - L}{u} du$ tends to 0 as $T \to \infty$.
-/
theorem frullani_limit_infinity_lemma {f : ℝ → ℝ} {a b L : ℝ} (ha : 0 < a) (hb : 0 < b)
    (hf_cont : ContinuousOn f (Set.Ioi 0))
    (hf_inf : Filter.Tendsto f Filter.atTop (nhds L)) :
    Filter.Tendsto (fun T => ∫ u in a..b, (f (u * T) - L) / u) Filter.atTop (nhds 0) := by
      cases le_total a b <;> simp_all +decide [ intervalIntegral, division_def ];
      · -- Since $|f(xT) - L| < \epsilon$ for $x \ge M/a$, and $u \in [a, b]$, we have $|f(uT) - L| < \epsilon$ for $T > M/a$.
        have h_bound : ∀ ϵ > 0, ∃ M : ℝ, ∀ T > M, ∀ u ∈ Set.Icc a b, |(f (u * T) - L)| < ϵ := by
          exact fun ε ε_pos => by rcases Metric.tendsto_atTop.mp hf_inf ε ε_pos with ⟨ M, hM ⟩ ; exact ⟨ ⌈M / a⌉₊ + 1, fun T hT u hu => hM _ <| by nlinarith [ hu.1, hu.2, Nat.le_ceil ( M / a ), mul_div_cancel₀ M ha.ne' ] ⟩ ;
        -- Using the bound, we can show that the integral is bounded by $\epsilon \int_a^b \frac{1}{u} du$.
        have h_integral_bound : ∀ ϵ > 0, ∃ M : ℝ, ∀ T > M, |∫ u in Set.Ioc a b, (f (u * T) - L) / u| ≤ ϵ * ∫ u in Set.Ioc a b, |u⁻¹| := by
          intro ε hε_pos; obtain ⟨ M, HM ⟩ := h_bound ε hε_pos; use M; intro T hT; rw [ ←MeasureTheory.integral_const_mul ] ; refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) _ ; simp_all +decide [ div_eq_mul_inv, abs_mul, abs_inv ] ;
          refine' MeasureTheory.integral_mono_of_nonneg _ _ _ <;> norm_num [ ha.le, hb.le ];
          · exact Filter.eventually_inf_principal.mpr ( Filter.Eventually.of_forall fun x hx => by positivity );
          · exact ContinuousOn.integrableOn_Icc ( by exact ContinuousOn.mul continuousOn_const <| ContinuousOn.inv₀ ( continuousOn_id.abs ) fun x hx => ne_of_gt <| abs_pos.mpr <| by linarith [ hx.1 ] ) |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self;
          · exact Filter.eventually_inf_principal.mpr ( Filter.Eventually.of_forall fun x hx => mul_le_mul_of_nonneg_right ( le_of_lt ( HM T hT x hx.1.le hx.2 ) ) ( inv_nonneg.mpr ( abs_nonneg x ) ) );
        rw [ Metric.tendsto_nhds ];
        simp +zetaDelta at *;
        exact fun ε hε => by rcases h_integral_bound ( ε / ( Max.max ( ∫ u in Set.Ioc a b, |u|⁻¹ ) 1 + 1 ) ) ( by positivity ) with ⟨ M, HM ⟩ ; exact ⟨ M + 1, fun T hT => lt_of_le_of_lt ( HM T ( by linarith ) ) ( by rw [ div_mul_eq_mul_div, div_lt_iff₀ ] <;> nlinarith [ le_max_left ( ∫ u in Set.Ioc a b, |u|⁻¹ ) 1, le_max_right ( ∫ u in Set.Ioc a b, |u|⁻¹ ) 1 ] ) ⟩ ;
      · -- Since $f(x) \to L$ as $x \to \infty$, for any $\epsilon > 0$, there exists $M$ such that $|f(x) - L| < \epsilon$ for $x \ge M$.
        have h_eps : ∀ ϵ > 0, ∃ M : ℝ, ∀ x ≥ M, abs (f x - L) < ϵ := by
          exact Metric.tendsto_atTop.mp hf_inf;
        -- For $T > M/a$, and $u \in [a, b]$, we have $uT \ge aT > M$, so $|f(uT) - L| < \epsilon$.
        have h_bound : ∀ ϵ > 0, ∃ M : ℝ, ∀ T ≥ M, ∀ u ∈ Set.Icc b a, abs ((f (u * T) - L) / u) ≤ ϵ / u := by
          exact fun ε hε => by rcases h_eps ε hε with ⟨ M, HM ⟩ ; exact ⟨ Max.max ( M / b ) 1, fun T hT u hu => by rw [ abs_div, abs_of_nonneg ( by linarith [ hu.1 ] : 0 ≤ u ) ] ; exact div_le_div_of_nonneg_right ( le_of_lt ( HM _ ( by nlinarith [ hu.1, hu.2, le_max_left ( M / b ) 1, le_max_right ( M / b ) 1, mul_div_cancel₀ M hb.ne' ] ) ) ) ( by linarith [ hu.1, hu.2 ] ) ⟩ ;
        -- Then $|\int_a^b \frac{f(uT) - L}{u} du| \le \int_a^b \frac{|f(uT) - L|}{u} du \le \epsilon \int_a^b \frac{1}{u} du = \epsilon \ln(b/a)$.
        have h_integral_bound : ∀ ϵ > 0, ∃ M : ℝ, ∀ T ≥ M, abs (∫ u in Set.Ioc b a, (f (u * T) - L) / u) ≤ ϵ * ∫ u in Set.Ioc b a, (1 / u) := by
          intro ε hε_pos; obtain ⟨ M, hM ⟩ := h_bound ε hε_pos; use Max.max M ( a + 1 ) ; intro T hT; rw [ ← MeasureTheory.integral_const_mul ] ; refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm ( _ : ℝ → ℝ ) ) ( MeasureTheory.integral_mono_of_nonneg _ _ _ );
          · exact Filter.Eventually.of_forall fun x => norm_nonneg _;
          · exact ContinuousOn.integrableOn_Icc ( by exact ContinuousOn.mul continuousOn_const <| ContinuousOn.div continuousOn_const continuousOn_id <| by intro x hx; linarith [ hx.1 ] ) |> fun h => h.mono_set <| Set.Ioc_subset_Icc_self;
          · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioc ] with u hu using by simpa [ div_eq_mul_inv ] using hM T ( le_trans ( le_max_left _ _ ) hT ) u ⟨ hu.1.le, hu.2 ⟩ ;
        rw [ Metric.tendsto_nhds ];
        simp +zetaDelta at *;
        exact fun ε ε_pos => by rcases h_integral_bound ( ε / ( 2 * ( ∫ u in Set.Ioc b a, u⁻¹ ) + 1 ) ) ( div_pos ε_pos ( by linarith [ show 0 ≤ ∫ u in Set.Ioc b a, u⁻¹ by exact MeasureTheory.setIntegral_nonneg measurableSet_Ioc fun x hx => inv_nonneg.2 ( by linarith [ hx.1 ] ) ] ) ) with ⟨ M, HM ⟩ ; exact ⟨ M, fun T hT => lt_of_le_of_lt ( HM T hT ) ( by rw [ div_mul_eq_mul_div, div_lt_iff₀ ] <;> nlinarith [ show 0 ≤ ∫ u in Set.Ioc b a, u⁻¹ by exact MeasureTheory.setIntegral_nonneg measurableSet_Ioc fun x hx => inv_nonneg.2 ( by linarith [ hx.1 ] ) ] ) ⟩ ;

/-
The Frullani integral formula: $\int_0^\infty \frac{f(ax) - f(bx)}{x} dx = (f(0) - f(\infty)) \ln(b/a)$.
-/
theorem frullani_integral_formula {f : ℝ → ℝ} {a b L : ℝ} (ha : 0 < a) (hb : 0 < b)
    (hf_zero : ContinuousAt f 0)
    (hf_cont : ContinuousOn f (Set.Ioi 0))
    (hf_inf : Filter.Tendsto f Filter.atTop (nhds L)) :
    Filter.Tendsto (fun (p : ℝ × ℝ) => ∫ x in p.1..p.2, (f (a * x) - f (b * x)) / x)
      ((nhdsWithin 0 (Set.Ioi 0)) ×ˢ Filter.atTop)
      (nhds ((f 0 - L) * Real.log (b / a))) := by
        -- Let's split the integral into two parts:
        suffices h_split : Filter.Tendsto (fun p : ℝ × ℝ => (∫ x in (p.1)..p.2, f (a * x) / x) - (∫ x in (p.1)..p.2, f (b * x) / x)) (nhdsWithin 0 (Set.Ioi 0) ×ˢ Filter.atTop) (nhds ((f 0 - L) * Real.log (b / a))) by
          refine h_split.congr' ?_;
          filter_upwards [ Filter.prod_mem_prod ( Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ) ( Filter.eventually_gt_atTop 1 ) ] with p hp;
          rw [ ← intervalIntegral.integral_sub ] ; congr ; ext ; ring;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.div ( hf_cont.comp ( continuousOn_const.mul continuousOn_id ) fun x hx => mul_pos ha <| by cases Set.mem_uIcc.mp hx <;> linarith [ hp.1.1, hp.1.2, hp.2.out ] ) continuousOn_id fun x hx => by cases Set.mem_uIcc.mp hx <;> linarith [ hp.1.1, hp.1.2, hp.2.out ] ;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.div ( hf_cont.comp ( continuousOn_const.mul continuousOn_id ) fun x hx => mul_pos hb <| by cases Set.mem_uIcc.mp hx <;> linarith [ hp.1.1, hp.1.2, hp.2.out ] ) continuousOn_id fun x hx => by cases Set.mem_uIcc.mp hx <;> linarith [ hp.1.1, hp.1.2, hp.2.out ] ;
        -- By Fubini's theorem, we can interchange the order of integration.
        have h_fubini : ∀ δ T : ℝ, 0 < δ → 0 < T → (∫ x in (δ)..T, f (a * x) / x) - (∫ x in (δ)..T, f (b * x) / x) = (∫ v in (a * δ).. (b * δ), f v / v) - (∫ v in (a * T).. (b * T), f v / v) := by
          intros δ T hδ hT;
          -- By substitution using $u = ax$ and $v = bx$, we can rewrite the integrals as follows:
          have h_subst_a : ∫ x in (δ)..T, f (a * x) / x = ∫ u in (a * δ).. (a * T), f u / u := by
            convert intervalIntegral.integral_comp_mul_left _ ha.ne' using 3 ; ring;
            any_goals exact fun x => f x / x * a;
            · grind;
            · simp +decide [ div_eq_inv_mul, mul_assoc, mul_comm, mul_left_comm, ha.ne' ]
          have h_subst_b : ∫ x in (δ)..T, f (b * x) / x = ∫ v in (b * δ).. (b * T), f v / v := by
            simpa [ div_eq_inv_mul, mul_assoc, mul_comm b, hb.ne' ] using intervalIntegral.integral_comp_mul_left ( fun x => f x / x ) hb.ne';
          rw [ h_subst_a, h_subst_b, ← intervalIntegral.integral_add_adjacent_intervals ];
          rw [ intervalIntegral.integral_symm ] ; ring;
          · rw [ show ( ∫ x in b * δ..b * T, f x * x⁻¹ ) = ( ∫ x in b * δ..a * T, f x * x⁻¹ ) + ( ∫ x in a * T..b * T, f x * x⁻¹ ) from ?_ ] ; ring;
            rw [ intervalIntegral.integral_add_adjacent_intervals ] <;> apply_rules [ ContinuousOn.intervalIntegrable ];
            · exact ContinuousOn.mul ( hf_cont.mono ( by intro x hx; cases Set.mem_uIcc.mp hx <;> exact Set.mem_Ioi.mpr <| by nlinarith ) ) ( ContinuousOn.inv₀ continuousOn_id fun x hx => by cases Set.mem_uIcc.mp hx <;> nlinarith );
            · exact ContinuousOn.mul ( hf_cont.mono ( by intro x hx; cases Set.mem_uIcc.mp hx <;> exact Set.mem_Ioi.mpr <| by nlinarith ) ) ( ContinuousOn.inv₀ ( continuousOn_id ) fun x hx => by cases Set.mem_uIcc.mp hx <;> nlinarith );
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.div ( hf_cont.mono ( by intro u hu; cases Set.mem_uIcc.mp hu <;> exact Set.mem_Ioi.mpr <| by nlinarith ) ) continuousOn_id fun u hu => by cases Set.mem_uIcc.mp hu <;> nlinarith;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.div ( hf_cont.mono ( by intro u hu; cases Set.mem_uIcc.mp hu <;> exact Set.mem_Ioi.mpr <| by nlinarith ) ) continuousOn_id fun u hu => by cases Set.mem_uIcc.mp hu <;> nlinarith;
        -- Applying the lemma `frullani_limit_zero_lemma` to the first integral and `frullani_limit_infinity_lemma` to the second integral.
        have h_first : Filter.Tendsto (fun δ => ∫ v in (a * δ).. (b * δ), f v / v) (nhdsWithin 0 (Set.Ioi 0)) (nhds (f 0 * Real.log (b / a))) := by
          have h_first : Filter.Tendsto (fun δ => ∫ u in (a)..b, (f (u * δ) - f 0) / u) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
            convert frullani_limit_zero_lemma ha hb hf_zero using 1;
          have h_first : Filter.Tendsto (fun δ => (∫ u in (a)..b, (f (u * δ) - f 0) / u) + (∫ u in (a)..b, f 0 / u)) (nhdsWithin 0 (Set.Ioi 0)) (nhds (f 0 * Real.log (b / a))) := by
            convert h_first.add_const ( ∫ u in a..b, f 0 / u ) using 2 ; norm_num [ div_eq_mul_inv ] ; ring;
            rw [ integral_inv_of_pos, Real.log_mul ] <;> norm_num <;> try positivity;
            exact Or.inl ( by rw [ Real.log_div hb.ne' ha.ne' ] ; ring );
          refine' h_first.congr' _;
          filter_upwards [ self_mem_nhdsWithin ] with δ hδ ; rw [ ← intervalIntegral.integral_add ] ; rw [ frullani_substitution_lemma hδ ] ; congr ; ext ; ring;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact ContinuousOn.div ( ContinuousOn.sub ( hf_cont.comp ( continuousOn_id.mul continuousOn_const ) fun x hx => mul_pos ( show 0 < x from by cases Set.mem_uIcc.mp hx <;> linarith ) hδ ) continuousOn_const ) continuousOn_id fun x hx => by cases Set.mem_uIcc.mp hx <;> linarith;
          · apply_rules [ ContinuousOn.intervalIntegrable ];
            exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.div continuousAt_const continuousAt_id ( by cases Set.mem_uIcc.mp hx <;> linarith )
        have h_second : Filter.Tendsto (fun T => ∫ v in (a * T).. (b * T), f v / v) Filter.atTop (nhds (L * Real.log (b / a))) := by
          -- Applying the lemma `frullani_limit_infinity_lemma` to the second integral.
          have h_second : Filter.Tendsto (fun T => ∫ u in a..b, (f (u * T) - L) / u) Filter.atTop (nhds 0) := by
            apply_rules [ frullani_limit_infinity_lemma ];
          have h_second : Filter.Tendsto (fun T => (∫ u in a..b, f (u * T) / u) - (∫ u in a..b, L / u)) Filter.atTop (nhds 0) := by
            refine' h_second.congr' _;
            filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT;
            rw [ ← intervalIntegral.integral_sub ] ; congr ; ext ; ring;
            · apply_rules [ ContinuousOn.intervalIntegrable ];
              exact ContinuousOn.div ( hf_cont.comp ( continuousOn_id.mul continuousOn_const ) fun x hx => mul_pos ( by cases Set.mem_uIcc.mp hx <;> linarith ) hT ) continuousOn_id fun x hx => by cases Set.mem_uIcc.mp hx <;> linarith;
            · apply_rules [ ContinuousOn.intervalIntegrable ];
              exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.div continuousAt_const continuousAt_id ( by cases Set.mem_uIcc.mp hx <;> linarith );
          have h_second : Filter.Tendsto (fun T => (∫ u in a..b, f (u * T) / u)) Filter.atTop (nhds (L * Real.log (b / a))) := by
            convert h_second.add_const ( L * Real.log ( b / a ) ) using 2 <;> norm_num [ div_eq_mul_inv ];
            field_simp;
            norm_num [ mul_comm, ha.not_le, hb.not_le ];
            rw [ integral_inv_of_pos, Real.log_div ] <;> linarith;
          refine h_second.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ ← frullani_substitution_lemma hT ] );
        rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.prod_mem_prod ( self_mem_nhdsWithin ) ( Filter.eventually_gt_atTop 0 ) ] with p hp; rw [ h_fubini p.1 p.2 hp.1 hp.2 ] ) ];
        simpa only [ sub_mul ] using Filter.Tendsto.sub ( h_first.comp <| Filter.tendsto_fst ) ( h_second.comp <| Filter.tendsto_snd )
