/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1e10088e-6eeb-4fbd-ba71-77c08df01021

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have proved the Perron-Frobenius theorem for positive matrices, using the lemmas provided in the workspace. The main theorem is `perron_frobenius_positive`, which establishes the existence of a positive Perron root and Perron vector, the algebraic multiplicity of the Perron root being 1, and the maximality of the Perron root among all eigenvalues.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 88d88ed0-2629-496c-abe6-52e305115af1

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a9b65787-1c81-452f-aa55-2364e7fb17e4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: eb8bcf5b-02f0-4e54-aa5d-31536d7d15a9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 32bc4e31-f352-4773-a64e-620122f9e476

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Check OrderedSemiring
-/
#check OrderedSemiring

/-
Check if OrderedSemiring is a class.
-/
#print OrderedSemiring

/-
Check LinearOrderedSemiring and spectralRadius
-/
#check LinearOrderedSemiring
#check spectralRadius

/-
Check LinearOrderedField
-/
#check LinearOrderedField

/-
Definitions of positive and irreducible matrices over Real.
-/
def Matrix.IsPositive {n : Type*} [Fintype n] (A : Matrix n n ℝ) : Prop :=
  ∀ i j, 0 < A i j

def Matrix.IsIrreducible {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) : Prop :=
  ∀ i j : n, ∃ k : ℕ, (A ^ k) i j > 0

/-
Definition of non-negative matrix.
-/
def Matrix.IsNonneg {n : Type*} [Fintype n] (A : Matrix n n ℝ) : Prop :=
  ∀ i j, 0 ≤ A i j

/-
Definitions of irreducible matrix (corrected) and positive vector.
-/
def Matrix.IsIrreducible' {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) : Prop :=
  ∀ i j : n, ∃ k : ℕ, k > 0 ∧ (A ^ k) i j > 0

def Matrix.IsPositiveVec {n : Type*} [Fintype n] (v : n → ℝ) : Prop :=
  ∀ i, 0 < v i

/-
Definition of non-negative vector and basic lemmas relating positive and irreducible matrices.
-/
def Matrix.IsNonnegVec {n : Type*} [Fintype n] (v : n → ℝ) : Prop :=
  ∀ i, 0 ≤ v i

lemma Matrix.isNonneg_of_isPositive {n : Type*} [Fintype n] (A : Matrix n n ℝ) (h : A.IsPositive) : A.IsNonneg := by
  intro i j
  exact le_of_lt (h i j)

lemma Matrix.isIrreducible_of_isPositive {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) (h : A.IsPositive) : A.IsIrreducible' := by
  intro i j
  use 1
  constructor
  · norm_num
  · simp
    exact h i j

/-
If A is irreducible and non-negative, and v is a non-negative non-zero eigenvector, then v is strictly positive.
-/
lemma Matrix.isPositiveVec_of_eigenvector {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv_nonneg : Matrix.IsNonnegVec v) (hv_ne_zero : v ≠ 0)
    (r : ℝ) (h_eig : A.mulVec v = r • v) :
    Matrix.IsPositiveVec v := by
      -- Consider the set $I$ of indices where $v_i = 0$. Since $v \neq 0$, $I$ is non-empty.
      set I := {i | v i = 0} with hI_def
      by_cases hI_empty : I = ∅;
      · exact fun i => lt_of_le_of_ne ( hv_nonneg i ) ( Ne.symm <| by rw [ Set.ext_iff ] at hI_empty; specialize hI_empty i; aesop );
      · -- Since $A$ is irreducible, there exists some $j \in I$ and $k \notin I$ such that $(A^m)_{jk} > 0$ for some $m$.
        obtain ⟨j, hjI, k, hkI, hm⟩ : ∃ j ∈ I, ∃ k ∉ I, ∃ m : ℕ, m > 0 ∧ (A ^ m) j k > 0 := by
          obtain ⟨j, hjI⟩ : ∃ j, j ∈ I := by
            exact Set.nonempty_iff_ne_empty.2 hI_empty
          obtain ⟨k, hkI⟩ : ∃ k, k ∉ I := by
            exact Function.ne_iff.mp hv_ne_zero |> Exists.imp fun k hk => by aesop;
          obtain ⟨m, hm_pos, hm⟩ : ∃ m : ℕ, m > 0 ∧ (A ^ m) j k > 0 := by
            exact hA_irr j k
          use j, hjI, k, hkI, m, hm_pos, hm;
        -- Since $v$ is an eigenvector of $A$, we have $(A^m v)_j = r^m v_j$.
        obtain ⟨m, hm_pos, hm_gt⟩ := hm;
        have h_eig_m : (A ^ m).mulVec v j = r ^ m * v j := by
          have h_eig_m : ∀ m : ℕ, (A ^ m).mulVec v = r ^ m • v := by
            intro m; induction m <;> simp_all +decide [ pow_succ', Matrix.mulVec_smul ] ;
            simp_all +decide [ ← Matrix.mulVec_mulVec, Matrix.mulVec_smul ];
            rw [ smul_smul, mul_comm ];
          exact congr_fun ( h_eig_m m ) j;
        simp_all +decide [ Matrix.mulVec, dotProduct ];
        contrapose! h_eig_m;
        refine' ne_of_gt ( lt_of_lt_of_le _ ( Finset.single_le_sum ( fun i _ => mul_nonneg ( show 0 ≤ ( A ^ m ) j i from _ ) ( hv_nonneg i ) ) ( Finset.mem_univ k ) ) );
        · exact mul_pos hm_gt ( lt_of_le_of_ne ( hv_nonneg k ) ( Ne.symm hkI ) );
        · -- Since $A$ is non-negative, each entry of $A^m$ is non-negative.
          have hA_pow_nonneg : ∀ m : ℕ, ∀ i j, 0 ≤ (A ^ m) i j := by
            intro m i j; induction' m with m ih generalizing i j <;> simp_all +decide [ pow_succ', Matrix.mul_apply ] ;
            · exact?;
            · exact Finset.sum_nonneg fun _ _ => mul_nonneg ( hA_nonneg _ _ ) ( ih _ _ );
          exact hA_pow_nonneg m j i

/-
For a non-negative matrix A, |Av| <= A|v|.
-/
def vecAbs {n : Type*} (v : n → ℝ) : n → ℝ := fun i => |v i|

lemma Matrix.abs_mulVec_le_mulVec_abs {n : Type*} [Fintype n] (A : Matrix n n ℝ) (hA : A.IsNonneg) (v : n → ℝ) :
    vecAbs (A.mulVec v) ≤ A.mulVec (vecAbs v) := by
      intro i
      simp [Matrix.mulVec, vecAbs];
      convert Finset.abs_sum_le_sum_abs _ _ |> le_trans <| Finset.sum_le_sum fun j _ => ?_ using 1;
      · infer_instance;
      · infer_instance;
      · simp [vecAbs];
        rw [ abs_of_nonneg ( hA i j ) ]

/-
If A is irreducible and non-negative, and v is a non-negative non-zero eigenvector, then its eigenvalue is positive.
-/
lemma Matrix.eigenvalue_pos_of_nonneg_eigenvector {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv_nonneg : Matrix.IsNonnegVec v) (hv_ne_zero : v ≠ 0)
    (r : ℝ) (h_eig : A.mulVec v = r • v) :
    r > 0 := by
      -- By Lemma 25, $v$ is strictly positive.
      have hv_strict_pos : Matrix.IsPositiveVec v := by
        exact?;
      have h_r_pos : ∀ i, 0 < (A.mulVec v) i := by
        intro i
        have h_sum_pos : ∃ j, 0 < A i j ∧ 0 < v j := by
          obtain ⟨ k, hk ⟩ := hA_irr i i;
          induction' k with k ih generalizing i <;> simp_all +decide [ pow_succ', Matrix.mul_apply ];
          obtain ⟨ j, hj ⟩ := Finset.exists_ne_zero_of_sum_ne_zero hk.ne';
          exact ⟨ j, lt_of_le_of_ne ( hA_nonneg i j ) ( Ne.symm <| by aesop ), hv_strict_pos j ⟩;
        obtain ⟨ j, hj₁, hj₂ ⟩ := h_sum_pos; exact lt_of_lt_of_le ( mul_pos hj₁ hj₂ ) ( Finset.single_le_sum ( fun a _ => mul_nonneg ( hA_nonneg i a ) ( hv_nonneg a ) ) ( Finset.mem_univ j ) ) ;
      rcases isEmpty_or_nonempty n with ( h | h ) <;> simp_all +decide [ funext_iff ];
      exact lt_of_not_ge fun hr => by nlinarith [ h_r_pos h.some, hv_strict_pos h.some ] ;

/-
Check if Complex is available.
-/
#check Complex

/-
If A is irreducible and non-negative, and v is a non-negative non-zero vector, then Av is not zero.
-/
lemma Matrix.mulVec_ne_zero_of_nonneg_of_ne_zero {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv_nonneg : Matrix.IsNonnegVec v) (hv_ne_zero : v ≠ 0) :
    A.mulVec v ≠ 0 := by
      -- By contradiction, assume $A.mulVec v = 0$.
      by_contra h_contra;
      -- Apply the lemma Matrix.isPositiveVec_of_eigenvector to conclude that v is strictly positive.
      have h_pos_eigenvec : ∃ r : ℝ, A.mulVec v = r • v ∧ r > 0 := by
        exact ⟨ 0, by simp +decide [ h_contra ], by linarith [ eigenvalue_pos_of_nonneg_eigenvector A hA_nonneg hA_irr v hv_nonneg hv_ne_zero 0 ( by simp +decide [ h_contra ] ) ] ⟩;
      simp_all +decide [ funext_iff ];
      exact hv_ne_zero.elim fun x hx => hx ( by obtain ⟨ r, hr₁, hr₂ ⟩ := h_pos_eigenvec; cases hr₁ x <;> linarith )

/-
Define the map on the simplex.
-/
def simplexMap {n : Type*} [Fintype n] (A : Matrix n n ℝ) (v : n → ℝ) : n → ℝ :=
  (1 / ∑ i, (A.mulVec v) i) • A.mulVec v

/-
The map simplexMap sends the standard simplex to itself.
-/
lemma simplexMap_mem_stdSimplex {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) :
    simplexMap A v ∈ stdSimplex ℝ n := by
      refine' ⟨ _, _ ⟩;
      · intro i
        simp [simplexMap];
        exact mul_nonneg ( inv_nonneg.2 ( Finset.sum_nonneg fun _ _ => by rw [ Matrix.mulVec, dotProduct ] ; exact Finset.sum_nonneg fun _ _ => mul_nonneg ( hA_nonneg _ _ ) ( hv.1 _ ) ) ) ( by rw [ Matrix.mulVec, dotProduct ] ; exact Finset.sum_nonneg fun _ _ => mul_nonneg ( hA_nonneg _ _ ) ( hv.1 _ ) );
      · unfold simplexMap;
        by_cases h : ∑ i, A.mulVec v i = 0 <;> simp_all +decide [ Matrix.mulVec, dotProduct ];
        · rw [ Finset.sum_eq_zero_iff_of_nonneg ] at h;
          · -- Since $A$ is irreducible and non-negative, and $v$ is a non-negative non-zero vector, $A.mulVec v$ cannot be zero.
            have h_mulVec_ne_zero : A.mulVec v ≠ 0 := by
              apply Matrix.mulVec_ne_zero_of_nonneg_of_ne_zero A hA_nonneg hA_irr v (fun i => by
                exact hv.1 i) (by
              rintro rfl; simp_all +decide [ stdSimplex ]);
            exact h_mulVec_ne_zero ( funext fun i => by simpa [ Matrix.mulVec, dotProduct ] using h i ( Finset.mem_univ i ) );
          · exact fun i _ => Finset.sum_nonneg fun j _ => mul_nonneg ( hA_nonneg i j ) ( hv.1 j );
        · simp +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, h ]

/-
The map simplexMap is continuous on the standard simplex.
-/
lemma continuousOn_simplexMap {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible') :
    ContinuousOn (simplexMap A) (stdSimplex ℝ n) := by
      refine' ContinuousOn.smul _ _;
      · refine' ContinuousOn.div continuousOn_const _ _;
        · exact Continuous.continuousOn ( continuous_finset_sum _ fun i _ => Continuous.dotProduct ( continuous_const ) continuous_id' );
        · intro x hx
          have h_pos : ∀ i, 0 ≤ (A.mulVec x) i := by
            exact fun i => Finset.sum_nonneg fun j _ => mul_nonneg ( hA_nonneg i j ) ( hx.1 j );
          have h_nonzero : A.mulVec x ≠ 0 := by
            apply Matrix.mulVec_ne_zero_of_nonneg_of_ne_zero A hA_nonneg hA_irr x (fun i => hx.1 i) (by
            rintro rfl; simp_all +decide [ stdSimplex ]);
          exact fun h => h_nonzero <| funext fun i => le_antisymm ( le_trans ( Finset.single_le_sum ( fun i _ => h_pos i ) ( Finset.mem_univ i ) ) h.le ) ( h_pos i );
      · exact Continuous.continuousOn ( continuous_const.matrix_mulVec continuous_id' )

/-
If v is a fixed point of simplexMap A, then v is an eigenvector of A.
-/
lemma eigenvector_of_fixed_point_simplexMap {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) (h_fixed : simplexMap A v = v) :
    A.mulVec v = (∑ i, (A.mulVec v) i) • v := by
      unfold simplexMap at h_fixed;
      by_cases h : ∑ i, A.mulVec v i = 0 <;> simp_all +decide [ funext_iff, Matrix.mulVec ];
      · simp_all +decide [ show v = 0 by ext; simp +decide [ ← h_fixed ] ];
      · exact fun x => by rw [ ← h_fixed x, inv_mul_eq_div, mul_div_cancel₀ _ h ] ;

/-
The sum of the entries of Av is positive for v in the standard simplex.
-/
lemma sum_mulVec_pos {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ)
    (hA_nonneg : A.IsNonneg) (hA_irr : A.IsIrreducible')
    (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) :
    0 < ∑ i, (A.mulVec v) i := by
      have h_pos : A.mulVec v ≠ 0 := by
        apply Matrix.mulVec_ne_zero_of_nonneg_of_ne_zero A hA_nonneg hA_irr v hv.1 (by
        exact fun h => by simpa [ h ] using hv.2;);
      -- Since $A$ is non-negative and $v$ is in the standard simplex, each entry of $A.mulVec v$ is non-negative.
      have h_nonneg : ∀ i, 0 ≤ (A.mulVec v) i := by
        exact fun i => by rw [ Matrix.mulVec, dotProduct ] ; exact Finset.sum_nonneg fun j _ => mul_nonneg ( hA_nonneg i j ) ( hv.1 j ) ;
      exact lt_of_lt_of_le ( lt_of_le_of_ne ( h_nonneg ( Classical.choose ( Function.ne_iff.mp h_pos ) ) ) ( Ne.symm ( Classical.choose_spec ( Function.ne_iff.mp h_pos ) ) ) ) ( Finset.single_le_sum ( fun i _ => h_nonneg i ) ( Finset.mem_univ _ ) )

/-
Check system responsiveness.
-/
#check 1

#check stdSimplex

#check Matrix.IsPositive

#check Set.MapsTo

/-
The Collatz-Wielandt ratio for a non-negative vector v. Defined as min_i ((Av)_i / v_i). If v_i = 0, the term is infinity.
-/
def CW {n : Type*} [Fintype n] (A : Matrix n n ℝ) (v : n → ℝ) : WithTop ℝ :=
  Finset.univ.inf (fun i => if v i = 0 then ⊤ else ((A.mulVec v) i) / v i)

/-
Definition of the components of the Collatz-Wielandt ratio and a lemma stating that for a positive matrix and a vector in the simplex, the result of matrix-vector multiplication is strictly positive in every component.
-/
def CW_component {n : Type*} [Fintype n] (A : Matrix n n ℝ) (i : n) (v : n → ℝ) : WithTop ℝ :=
  if v i = 0 then ⊤ else ((A.mulVec v) i) / v i

lemma mulVec_component_pos {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) (i : n) :
    0 < (A.mulVec v) i := by
      -- Since $v$ is in the standard simplex, there exists some $j$ such that $v_j > 0$.
      obtain ⟨j, hj⟩ : ∃ j, v j > 0 := by
        exact not_forall_not.mp fun h'j => by have := hv.2; exact absurd this ( ne_of_lt ( lt_of_le_of_lt ( Finset.sum_nonpos fun i _ => le_of_not_gt ( h'j i ) ) ( by norm_num ) ) ) ;
      exact lt_of_lt_of_le ( mul_pos ( hA i j ) hj ) ( Finset.single_le_sum ( fun k _ => mul_nonneg ( le_of_lt ( hA i k ) ) ( hv.1 k ) ) ( Finset.mem_univ j ) )

lemma CW_component_tendsto_top {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n)
    (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) (hvi : v i = 0) :
    Filter.Tendsto (CW_component A i) (nhdsWithin v (stdSimplex ℝ n)) (nhds ⊤) := by
      -- Let $c = (A v) i$. Since $c > 0$, there exists a neighborhood of $v$ where $(A u) i > c / 2$.
      obtain ⟨c, hc_pos, hc⟩ : ∃ c : ℝ, 0 < c ∧ ∀ᶠ u in nhdsWithin v (stdSimplex ℝ n), (A.mulVec u) i > c / 2 := by
        have hc_pos : 0 < (A.mulVec v) i := by
          exact?;
        refine' ⟨ A.mulVec v i, hc_pos, _ ⟩;
        exact mem_nhdsWithin_of_mem_nhds ( ContinuousAt.preimage_mem_nhds ( show ContinuousAt ( fun u => A.mulVec u i ) v from Continuous.continuousAt ( by exact continuous_apply i |> Continuous.comp <| continuous_const.matrix_mulVec continuous_id' ) ) <| Ioi_mem_nhds <| half_lt_self hc_pos );
      -- Since $u$ is in the simplex, $u i ≥ 0$. Thus, for $u$ close enough to $v$, if $u i > 0$, then $(A u) i / u i > (c / 2) / u i$.
      have h_div : ∀ᶠ u in nhdsWithin v (stdSimplex ℝ n), u i > 0 → (CW_component A i) u > (c / 2) / u i := by
        filter_upwards [ hc ] with u hu hu';
        unfold CW_component;
        rw [ if_neg hu'.ne' ] ; exact WithTop.coe_lt_coe.mpr ( by rw [ div_lt_div_iff_of_pos_right hu' ] ; linarith );
      -- Since $u i → 0$, $(c / 2) / u i$ can be made arbitrarily large, specifically larger than $a$.
      have h_arbitrarily_large : ∀ a : ℝ, ∀ᶠ u in nhdsWithin v (stdSimplex ℝ n), u i > 0 → (CW_component A i) u > a := by
        intro a
        have h_arbitrarily_large : ∀ᶠ u in nhdsWithin v (stdSimplex ℝ n), u i > 0 → (c / 2) / u i > a := by
          have h_arbitrarily_large : ∀ᶠ u in nhdsWithin v (stdSimplex ℝ n), u i > 0 → u i < (c / 2) / (|a| + 1) := by
            have h_arbitrarily_large : Filter.Tendsto (fun u : n → ℝ => u i) (nhdsWithin v (stdSimplex ℝ n)) (nhds 0) := by
              exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( continuous_apply i ) _ _ hvi );
            filter_upwards [ h_arbitrarily_large.eventually ( gt_mem_nhds <| show 0 < c / 2 / ( |a| + 1 ) by positivity ) ] with u hu hu' using hu;
          filter_upwards [ h_arbitrarily_large ] with u hu hu' using by rw [ gt_iff_lt ] ; rw [ lt_div_iff₀ hu' ] ; cases abs_cases a <;> nlinarith [ hu hu', mul_div_cancel₀ ( c / 2 ) ( by linarith : ( |a| + 1 ) ≠ 0 ) ] ;
        filter_upwards [ h_div, h_arbitrarily_large ] with u hu₁ hu₂ hu₃ using lt_of_le_of_lt ( mod_cast hu₂ hu₃ |> le_of_lt ) ( hu₁ hu₃ );
      rw [ tendsto_order ];
      simp +zetaDelta at *;
      intro a' ha';
      rcases a' with ( _ | a' );
      · filter_upwards [ h_arbitrarily_large 0 ] with u hu;
        by_cases hi : u i = 0 <;> simp_all +decide [ CW_component ];
      · filter_upwards [ h_arbitrarily_large a', self_mem_nhdsWithin ] with u hu hu';
        by_cases hi : u i = 0 <;> simp_all +decide [ CW_component ];
        exact WithTop.coe_lt_coe.mpr ( hu ( lt_of_le_of_ne ( hu'.1 i ) ( Ne.symm hi ) ) )

example : ContinuousInf (WithTop ℝ) := by infer_instance

example : Continuous (fun x : ℝ => (x : WithTop ℝ)) := by
  -- The function `x ↦ ↑x` is the identity function on `ℝ`, which is continuous by definition.
  apply Continuous.mk; exact (by
  intro s hs; exact (by
  cases hs;
  · rcases ‹_› with ⟨ a, rfl | rfl ⟩ <;> simp +decide [ Set.preimage ];
    · cases a using WithTop.recTopCoe <;> simp +decide [ Set.Ioi_def ];
      exact?;
    · cases a using WithTop.recTopCoe <;> simp +decide [ Set.Iio_def ];
      exact isOpen_Iio;
  · exact isOpen_univ;
  · rename_i s t hs ht
    have h_cont : Continuous (fun x : ℝ => (x : WithTop ℝ)) := by
      apply Continuous.mk; intro s hs; exact (by
      induction hs;
      · rename_i s hs; rcases hs with ⟨ a, rfl | rfl ⟩ <;> simp +decide [ Set.preimage ] ;
        · cases a using WithTop.recTopCoe <;> simp +decide [ Set.preimage ];
          exact?;
        · induction a using WithTop.recTopCoe <;> simp +decide [ *, Set.Iio_def ];
          exact?;
      · exact isOpen_univ;
      · exact IsOpen.inter ‹_› ‹_›;
      · simp +zetaDelta at *;
        exact isOpen_biUnion fun s hs => by solve_by_elim;)
      skip
    have h_open : IsOpen (s ∩ t) := by
      apply_rules [ IsOpen.inter, hs, ht ]
    exact h_cont.isOpen_preimage _ h_open
    skip;
  · simp_all +decide [ Set.preimage ];
    rename_i S hS;
    rw [ show { x : ℝ | ∃ t ∈ S, ( x : WithTop ℝ ) ∈ t } = ⋃ t ∈ S, { x : ℝ | ( x : WithTop ℝ ) ∈ t } by ext; aesop ] ; exact isOpen_biUnion fun t ht => by
          refine' TopologicalSpace.GenerateOpen.recOn ( hS t ht ) _ _ _ _;
          · rintro _ ⟨ a, rfl | rfl ⟩ <;> [ exact isOpen_lt continuous_const ( by continuity ) ; exact isOpen_lt ( by continuity ) continuous_const ];
            · cases a using WithTop.recTopCoe <;> simp +decide [ Set.Ioi_def ];
              exact?;
            · cases a using WithTop.recTopCoe <;> simp +decide [ Set.Iio_def ];
              exact?;
          · exact isOpen_univ;
          · exact fun s t hs ht hs' ht' => by simpa only [ Set.setOf_and ] using hs'.inter ht';
          · simp +decide [ Set.mem_iUnion ];
            intro S hS hS'; rw [ show { x : ℝ | ∃ t ∈ S, ( x : WithTop ℝ ) ∈ t } = ⋃ t ∈ S, { x : ℝ | ( x : WithTop ℝ ) ∈ t } by ext; aesop ] ; exact isOpen_biUnion fun t ht => hS' t ht;;);)

example : OrderTopology (WithTop ℝ) := by infer_instance

/-
Limit of f(x)/g(x) in WithTop R is top if f(x) -> c > 0 and g(x) -> 0+
-/
lemma tendsto_withTop_div_zero {α : Type*} [TopologicalSpace α] {f g : α → ℝ} {a : α} {c : ℝ}
    (hf : Filter.Tendsto f (nhds a) (nhds c)) (hc : 0 < c)
    (hg : Filter.Tendsto g (nhds a) (nhds 0)) (hg_nonneg : ∀ᶠ x in nhds a, 0 ≤ g x) :
    Filter.Tendsto (fun x => if g x = 0 then ⊤ else ((f x / g x) : WithTop ℝ)) (nhds a) (nhds ⊤) := by
      -- Given that $g(x) \to 0$ and $g(x) \geq 0$, we can find a neighborhood where $g(x) < \frac{c}{2(|M| + 1)}$.
      have h_neighborhood : ∀ M : ℝ, ∃ U ∈ nhds a, ∀ x ∈ U, g x = 0 ∨ (f x / g x) > M := by
        intro M
        obtain ⟨U, hU⟩ : ∃ U ∈ nhds a, ∀ x ∈ U, g x = 0 ∨ g x < (c / 2) / (|M| + 1) := by
          exact ⟨ { x | g x < c / 2 / ( |M| + 1 ) }, hg.eventually ( gt_mem_nhds <| by positivity ), fun x hx => Classical.or_iff_not_imp_left.2 fun hx' => hx ⟩;
        -- Given that $f(x) \to c$ and $c > 0$, we can find a neighborhood where $f(x) > \frac{c}{2}$.
        obtain ⟨V, hV⟩ : ∃ V ∈ nhds a, ∀ x ∈ V, f x > c / 2 := by
          exact ⟨ { x | f x > c / 2 }, hf.eventually ( lt_mem_nhds ( half_lt_self hc ) ), fun x hx => hx ⟩;
        refine' ⟨ U ∩ V ∩ { x | 0 ≤ g x }, _, _ ⟩ <;> simp_all +decide [ Set.inter_assoc, Set.inter_comm, Set.inter_left_comm ];
        · exact hg_nonneg;
        · intro x hxU hxV hxg; specialize hU; specialize hV; cases hU.2 x hxU <;> simp_all +decide [ div_eq_mul_inv ] ;
          cases eq_or_lt_of_le hxg <;> simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ];
          exact Or.inr ( by cases abs_cases M <;> nlinarith [ inv_mul_cancel₀ ( by linarith : ( |M| + 1 ) ≠ 0 ), inv_pos.2 ( by linarith : 0 < g x ), mul_inv_cancel₀ ( by linarith : ( g x ) ≠ 0 ), hV.2 x hxV, mul_pos hc ( inv_pos.2 ( by linarith : 0 < g x ) ) ] );
      rw [ tendsto_order ];
      refine' ⟨ fun M hM => _, fun M hM => _ ⟩;
      · cases M using WithTop.recTopCoe <;> simp_all +decide;
        rcases h_neighborhood ‹_› with ⟨ U, hU₁, hU₂ ⟩ ; filter_upwards [ hU₁ ] with x hx ; specialize hU₂ x hx ; aesop;
      · exact False.elim <| hM.not_le <| le_top

lemma continuous_withTop_coe : Continuous (fun x : ℝ => (x : WithTop ℝ)) := by
  -- The preimage of an open set in WithTop ℝ under the coercion is open in ℝ.
  have h_preimage_open : ∀ U : Set (WithTop ℝ), IsOpen U → IsOpen (Set.preimage (fun x : ℝ => (x : WithTop ℝ)) U) := by
    intro U hU;
    induction hU;
    · rename_i s hs;
      rcases hs with ⟨ a, rfl | rfl ⟩ <;> norm_num [ Set.preimage ];
      · cases a using WithTop.recTopCoe <;> simp +decide [ Set.Ioi_def ];
        exact isOpen_Ioi;
      · cases a using WithTop.recTopCoe <;> simp +decide [ Set.preimage ];
        exact isOpen_Iio;
    · exact isOpen_univ;
    · exact IsOpen.inter ‹_› ‹_›;
    · simp +zetaDelta at *;
      exact isOpen_biUnion fun s hs => by solve_by_elim;
  exact?

lemma continuousOn_CW_component {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n) :
    ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
      -- First, handle the case where `v i = 0`.
      have h_zero_diverges : ∀ v ∈ stdSimplex ℝ n, v i = 0 → Filter.Tendsto (CW_component A i) (nhdsWithin v (stdSimplex ℝ n)) (nhds ⊤) := by
        exact?;
      intro v hv; by_cases hvi : v i = 0 <;> simp_all +decide [ ContinuousWithinAt ] ;
      · convert h_zero_diverges v hv hvi using 2 ; unfold CW_component ; aesop;
      · refine' Filter.Tendsto.congr' _ _;
        use fun x => ( A.mulVec x ) i / x i;
        · rw [ Filter.EventuallyEq, eventually_nhdsWithin_iff ];
          filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_singleton.preimage ( continuous_apply i ) ) hvi ] with x hx hx' using by unfold CW_component; aesop;
        · convert Filter.Tendsto.comp ( continuous_withTop_coe.tendsto _ ) ( Filter.Tendsto.div ( Continuous.continuousWithinAt ( show Continuous fun x : n → ℝ => ( A.mulVec x ) i from ?_ ) ) ( Continuous.continuousWithinAt ( show Continuous fun x : n → ℝ => x i from ?_ ) ) hvi ) using 1;
          · unfold CW_component; aesop;
          · fun_prop (disch := solve_by_elim);
          · exact continuous_apply i

lemma continuousOn_CW_component' {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n) :
    ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
      exact?

lemma continuousOn_CW_component_v2 {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n) :
    ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
      exact?

lemma continuousAt_CW_component_of_ne_zero {n : Type*} [Fintype n] (A : Matrix n n ℝ) (i : n)
    (v : n → ℝ) (hvi : v i ≠ 0) :
    ContinuousAt (CW_component A i) v := by
      -- The function CW_component is a composition of continuous functions.
      have h_cont_comp : ContinuousAt (fun u : n → ℝ => ((A.mulVec u) i) / u i) v := by
        refine' ContinuousAt.div ( Continuous.continuousAt _ ) ( continuousAt_pi.1 continuousAt_id i ) hvi;
        fun_prop;
      refine' ContinuousAt.congr _ _;
      exact fun u => if u i = 0 then ⊤ else ( A.mulVec u i / u i : ℝ );
      · rw [ ContinuousAt ] at *;
        rw [ Filter.tendsto_congr' ];
        convert Filter.Tendsto.comp ( show Filter.Tendsto ( fun x : ℝ => ( x : WithTop ℝ ) ) ( nhds ( A.mulVec v i / v i ) ) ( nhds ( ↑ ( A.mulVec v i / v i ) ) ) from ?_ ) h_cont_comp using 1;
        · rw [ if_neg hvi ];
        · exact continuous_withTop_coe.tendsto _;
        · filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_singleton.preimage ( continuous_apply i ) ) hvi ] with u hu using by aesop;
      · filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_singleton.preimage ( continuous_apply i ) ) hvi ] with u hu using by unfold CW_component; aesop;

lemma continuousOn_CW {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    ContinuousOn (CW A) (stdSimplex ℝ n) := by
      intro v hv;
      -- Since each CW_component A i is continuous on the simplex, the infimum of these functions is continuous.
      have h_inf_cont : ContinuousOn (fun v => Finset.univ.inf (fun i => CW_component A i v)) (stdSimplex ℝ n) := by
        have h_cont : ∀ i, ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
          exact?
        exact?;
      exact h_inf_cont v hv

lemma continuousOn_CW_component_v3 {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n) :
    ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
      exact?

lemma continuousOn_CW_component_final {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) (i : n) :
    ContinuousOn (CW_component A i) (stdSimplex ℝ n) := by
  intro v hv
  by_cases hvi : v i = 0
  · -- Case v i = 0
    rw [ContinuousWithinAt]
    rw [CW_component, if_pos hvi]
    apply CW_component_tendsto_top A hA i v hv hvi
  · -- Case v i != 0
    apply ContinuousAt.continuousWithinAt
    apply continuousAt_CW_component_of_ne_zero A i v hvi

lemma continuousOn_CW_final {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    ContinuousOn (CW A) (stdSimplex ℝ n) := by
      -- Apply the fact that the infimum of finitely many continuous functions is continuous.
      apply continuousOn_CW A hA

lemma CW_ne_top {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (v : n → ℝ) (hv : v ∈ stdSimplex ℝ n) :
    CW A v ≠ ⊤ := by
      -- Since $v$ is in the standard simplex, it has at least one non-zero component $i$.
      obtain ⟨i, hi⟩ : ∃ i, v i ≠ 0 := by
        exact not_forall.mp fun h => by simpa [ h ] using hv.2;
      exact ne_of_lt ( lt_of_le_of_lt ( Finset.inf_le ( Finset.mem_univ i ) ) ( by aesop ) )

lemma exists_CW_maximizer {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    ∃ v ∈ stdSimplex ℝ n, IsMaxOn (CW A) (stdSimplex ℝ n) v := by
      apply_rules [ IsCompact.exists_isMaxOn ];
      · exact?;
      · refine' ⟨ fun i => 1 / Fintype.card n, _, _ ⟩ <;> norm_num;
      · exact?

/-
Define the Perron vector as the maximizer of the Collatz-Wielandt ratio, and the Perron root as the maximum value (handling the top case by defaulting to 0, though it won't happen).
-/
noncomputable def perronVector {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) : n → ℝ :=
  Classical.choose (exists_CW_maximizer A hA)

noncomputable def perronRoot {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) : ℝ :=
  match CW A (perronVector A hA) with
  | ⊤ => 0
  | some r => r

/-
The Perron vector is in the standard simplex.
-/
lemma perronVector_mem_stdSimplex {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    perronVector A hA ∈ stdSimplex ℝ n := by
  exact (Classical.choose_spec (exists_CW_maximizer A hA)).1

/-
The Perron root is positive.
-/
lemma perronRoot_pos {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    0 < perronRoot A hA := by
      -- By definition, A is positive, which means all entries a_ij are positive.
      -- For any vector v in the standard simplex, each term (Av)_k / v_k, where v_k > 0, is a sum of positive terms divided by a positive number, hence positive.
      have h_min_pos : ∀ v ∈ stdSimplex ℝ n, ∀ k, (A.mulVec v k) / v k > 0 ∨ CW_component A k v = ⊤ := by
        intro v hv k;
        by_cases hk : v k = 0 <;> simp +decide [ *, CW_component ];
        -- Since $v$ is in the standard simplex, each component $v_k$ is positive.
        have hv_pos : 0 < v k := by
          exact lt_of_le_of_ne ( hv.1 k ) ( Ne.symm hk );
        refine' div_pos _ hv_pos;
        exact?;
      -- Since the minimum of positive numbers is positive unless the set is empty, and CW A v is the minimum of (Av)_k / v_k over all k, it follows that CW A v > 0 for any v in the standard simplex.
      have h_CW_pos : ∀ v ∈ stdSimplex ℝ n, 0 < CW A v := by
        intro v hv; specialize h_min_pos v hv; simp_all +decide [ CW, CW_component ] ;
        intro k; specialize h_min_pos k; aesop;
      convert h_CW_pos ( perronVector A hA ) ( perronVector_mem_stdSimplex A hA );
      unfold perronRoot;
      cases h : CW A ( perronVector A hA ) <;> simp +decide [ h ];
      exact absurd h ( ne_of_lt ( lt_top_iff_ne_top.mpr ( CW_ne_top A _ ( perronVector_mem_stdSimplex A hA ) ) ) )

/-
The Perron root times the Perron vector is less than or equal to A times the Perron vector.
-/
lemma perronRoot_le_mulVec {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    (perronRoot A hA) • (perronVector A hA) ≤ A.mulVec (perronVector A hA) := by
      intro i
      have h_comp : CW A (perronVector A hA) ≤ CW_component A i (perronVector A hA) := by
        exact Finset.inf_le ( Finset.mem_univ i );
      unfold CW_component at h_comp;
      split_ifs at h_comp <;> simp_all +decide [ div_eq_inv_mul ];
      · exact mulVec_component_pos A hA _ ( perronVector_mem_stdSimplex A hA ) i |> le_of_lt;
      · unfold perronRoot;
        cases h : CW A ( perronVector A hA ) <;> simp_all +decide [ mul_comm ];
        · exact absurd h ( CW_ne_top A _ ( perronVector_mem_stdSimplex A hA ) );
        · norm_cast at *;
          rwa [ inv_mul_eq_div, le_div_iff₀ ( lt_of_le_of_ne ( by have := perronVector_mem_stdSimplex A hA; exact this.1 i ) ( Ne.symm ‹_› ) ) ] at h_comp

/-
The Collatz-Wielandt ratio is homogeneous of degree 0, i.e., scaling the vector by a positive constant does not change the ratio.
-/
lemma CW_homogenous {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (v : n → ℝ) (c : ℝ) (hc : 0 < c) :
    CW A (c • v) = CW A v := by
      unfold CW;
      simp +decide [ Matrix.mulVec, mul_div_mul_left, hc.ne' ]

/-
If A is a positive matrix and v is a non-negative non-zero vector, then Av is a strictly positive vector.
-/
lemma Matrix.isPositiveVec_mulVec_of_isPositive_of_isNonnegVec_of_ne_zero {n : Type*} [Fintype n] [Nonempty n]
    (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (hv : Matrix.IsNonnegVec v) (hv_ne : v ≠ 0) :
    Matrix.IsPositiveVec (A.mulVec v) := by
      intro i
      have h_sum_pos : ∑ j, A i j * v j > 0 := by
        -- Since $v \neq 0$, there exists some $j$ such that $v_j > 0$.
        obtain ⟨j, hj⟩ : ∃ j, v j > 0 := by
          exact Function.ne_iff.mp hv_ne |> Exists.imp fun j hj => lt_of_le_of_ne ( hv j ) ( Ne.symm hj );
        exact lt_of_lt_of_le ( mul_pos ( hA i j ) hj ) ( Finset.single_le_sum ( fun j _ => mul_nonneg ( le_of_lt ( hA i j ) ) ( hv j ) ) ( Finset.mem_univ j ) );
      exact h_sum_pos

/-
If Av >= rv and Av != rv, then CW(Av) > r. This relies on A being positive.
-/
lemma CW_gt_of_le_of_ne {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (hv : Matrix.IsNonnegVec v) (hv_ne : v ≠ 0)
    (r : ℝ) (hr_le : r • v ≤ A.mulVec v) (hr_ne : A.mulVec v ≠ r • v) :
    CW A (A.mulVec v) > (r : WithTop ℝ) := by
      -- Since $A.mulVec v$ is strictly positive, each component $(A.mulVec v) i$ is positive. Therefore, the ratio $(A.mulVec (A.mulVec v)) i / (A.mulVec v) i$ is well-defined.
      have h_pos : ∀ i, 0 < (A.mulVec v) i := by
        apply Matrix.isPositiveVec_mulVec_of_isPositive_of_isNonnegVec_of_ne_zero A hA v hv hv_ne;
      -- Since $A$ is positive and $A.mulVec v$ is strictly positive, each component $(A.mulVec (A.mulVec v)) i$ is strictly greater than $r * (A.mulVec v) i$.
      have h_ratio_gt_r : ∀ i, (A.mulVec (A.mulVec v)) i / (A.mulVec v) i > r := by
        intro i
        have h_sum_pos : ∑ j, A i j * (A.mulVec v j - r * v j) > 0 := by
          -- Since $A$ is positive and $A.mulVec v \neq r • v$, there exists some $j$ such that $A.mulVec v j > r * v j$.
          obtain ⟨j, hj⟩ : ∃ j, A.mulVec v j > r * v j := by
            exact not_forall_not.mp fun h => hr_ne <| funext fun i => le_antisymm ( le_of_not_gt fun hi => h i hi ) ( hr_le i );
          exact lt_of_lt_of_le ( mul_pos ( hA i j ) ( sub_pos.mpr hj ) ) ( Finset.single_le_sum ( fun j _ => mul_nonneg ( le_of_lt ( hA i j ) ) ( sub_nonneg.mpr ( hr_le j ) ) ) ( Finset.mem_univ j ) );
        simp_all +decide [ Matrix.mulVec, dotProduct, mul_sub ];
        rw [ lt_div_iff₀ ( h_pos i ) ] ; simp_all +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ] ;
      unfold CW; aesop;

/-
The Collatz-Wielandt ratio of the Perron vector is equal to the Perron root (as a WithTop Real).
-/
lemma CW_perronVector_eq_perronRoot {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    CW A (perronVector A hA) = (perronRoot A hA : WithTop ℝ) := by
      unfold perronRoot;
      cases h : CW A ( perronVector A hA ) <;> simp +decide [ h ];
      exact absurd h ( CW_ne_top A _ ( perronVector_mem_stdSimplex A hA ) )

/-
The Perron vector is an eigenvector corresponding to the Perron root.
-/
lemma perronVector_is_eigenvector {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    A.mulVec (perronVector A hA) = (perronRoot A hA) • (perronVector A hA) := by
      by_contra h_neq;
      -- Apply `CW_gt_of_le_of_ne` with `v = perronVector A hA` and `r = perronRoot A hA`.
      have h_CW_gt : CW A (A.mulVec (perronVector A hA)) > (perronRoot A hA : WithTop ℝ) := by
        apply_rules [ CW_gt_of_le_of_ne ];
        · exact fun i => Classical.choose_spec ( exists_CW_maximizer A hA ) |>.1 |> fun h => by have := h.1 i; aesop;
        · exact fun h => h_neq <| by simp +decide [ h ] ;
        · exact?;
      -- Let `w = A.mulVec (perronVector A hA)`. `w` is a positive vector, so `w ≠ 0`.
      set w := A.mulVec (perronVector A hA)
      have hw_pos : Matrix.IsPositiveVec w := by
        apply Matrix.isPositiveVec_mulVec_of_isPositive_of_isNonnegVec_of_ne_zero A hA (perronVector A hA) (by
        exact fun i => Classical.choose_spec ( exists_CW_maximizer A hA ) |>.1 |> fun h => by have := h.1 i; aesop;) (by
        rintro h; simp_all +decide [ Matrix.IsPositiveVec ] ;
        exact h_neq ( by aesop ))
      have hw_ne_zero : w ≠ 0 := by
        exact fun h => by simpa [ h ] using hw_pos ( Classical.arbitrary n ) ;
      -- Let `u = (1 / ∑ i, w i) • w`. Then `u ∈ stdSimplex`.
      set u := (1 / ∑ i, w i) • w
      have hu_mem : u ∈ stdSimplex ℝ n := by
        refine' ⟨ fun i => _, _ ⟩;
        · exact mul_nonneg ( one_div_nonneg.mpr ( Finset.sum_nonneg fun _ _ => le_of_lt ( hw_pos _ ) ) ) ( le_of_lt ( hw_pos _ ) );
        · simp [u];
          rw [ ← Finset.mul_sum _ _ _, inv_mul_cancel₀ ( ne_of_gt ( Finset.sum_pos ( fun _ _ => hw_pos _ ) Finset.univ_nonempty ) ) ];
      -- By definition of `perronRoot` (as the max of CW on simplex), `CW A u ≤ perronRoot A hA`.
      have h_CW_u_le_perronRoot : CW A u ≤ (perronRoot A hA : WithTop ℝ) := by
        have h_CW_u_le_perronRoot : ∀ v ∈ stdSimplex ℝ n, CW A v ≤ (perronRoot A hA : WithTop ℝ) := by
          intro v hv_mem
          have h_CW_le_perronRoot : CW A v ≤ CW A (perronVector A hA) := by
            exact Classical.choose_spec ( exists_CW_maximizer A hA ) |>.2 hv_mem;
          exact h_CW_le_perronRoot.trans ( by rw [ CW_perronVector_eq_perronRoot ] );
        exact h_CW_u_le_perronRoot u hu_mem;
      -- By homogeneity `CW_homogenous`, `CW A u = CW A w`.
      have h_CW_u_eq_CW_w : CW A u = CW A w := by
        apply CW_homogenous;
        exact one_div_pos.mpr ( Finset.sum_pos ( fun _ _ => hw_pos _ ) Finset.univ_nonempty );
      exact h_CW_gt.not_le ( h_CW_u_eq_CW_w ▸ h_CW_u_le_perronRoot )

/-
The Perron vector is strictly positive.
-/
lemma perronVector_pos {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    Matrix.IsPositiveVec (perronVector A hA) := by
      apply Matrix.isPositiveVec_of_eigenvector A (Matrix.isNonneg_of_isPositive A hA) (Matrix.isIrreducible_of_isPositive A hA) (perronVector A hA) (by
      exact fun i => perronVector_mem_stdSimplex A hA |>.1 i) (by
      intro h; have := perronVector_mem_stdSimplex A hA; simp_all +decide [ funext_iff ] ;
      simp_all +decide [ funext_iff, stdSimplex ]) (perronRoot A hA) (by
      exact?)

/-
For a non-negative matrix A and a complex vector v, the absolute value of Av is less than or equal to A times the absolute value of v.
-/
def vecAbsC {n : Type*} (v : n → ℂ) : n → ℝ := fun i => ‖v i‖

lemma Matrix.abs_mulVec_le_mulVec_abs_complex {n : Type*} [Fintype n] (A : Matrix n n ℝ) (hA : A.IsNonneg) (v : n → ℂ) :
    vecAbsC ((A.map Complex.ofReal).mulVec v) ≤ A.mulVec (vecAbsC v) := by
      intro i;
      convert norm_sum_le _ _ using 2 ; simp +decide [ Matrix.mulVec, dotProduct ];
      exact Finset.sum_congr rfl fun j _ => by rw [ abs_of_nonneg ( hA i j ) ] ; rfl;

/-
The Perron root is greater than or equal to the magnitude of any complex eigenvalue.
-/
lemma perronRoot_ge_norm_eigenvalue {n : Type*} [Fintype n] [Nonempty n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (μ : ℂ) (v : n → ℂ) (hv_ne : v ≠ 0) (h_eig : (A.map Complex.ofReal).mulVec v = μ • v) :
    ‖μ‖ ≤ perronRoot A hA := by
      -- By `Matrix.abs_mulVec_le_mulVec_abs_complex`, $|\mu| y \le A y$.
      have h_abs_le : ‖μ‖ • vecAbsC v ≤ A.mulVec (vecAbsC v) := by
        have h_abs_le : vecAbsC ((A.map Complex.ofReal).mulVec v) ≤ A.mulVec (vecAbsC v) := by
          apply Matrix.abs_mulVec_le_mulVec_abs_complex A (Matrix.isNonneg_of_isPositive A hA) v;
        convert h_abs_le using 1 ; ext i ; simp +decide [ h_eig, vecAbsC ];
      -- This implies $CW(y) \ge |\mu|$.
      have h_CW_ge : CW A (vecAbsC v) ≥ ‖μ‖ := by
        refine' Finset.le_inf fun i _ => _;
        by_cases hi : vecAbsC v i = 0 <;> simp_all +decide [ Pi.smul_apply, div_le_iff₀ ];
        rw [ le_div_iff₀ ( lt_of_le_of_ne ( by exact norm_nonneg _ ) ( Ne.symm hi ) ) ] ; simpa using h_abs_le i;
      -- Since $r$ is the maximum of CW over the simplex, and we can scale $y$ to be in the simplex (by homogeneity), $r \ge CW(y) \ge |\mu|$.
      have h_r_ge_CW_y : CW A (perronVector A hA) ≥ CW A (vecAbsC v) := by
        have h_r_ge_CW_y : ∀ w ∈ stdSimplex ℝ n, CW A (perronVector A hA) ≥ CW A w := by
          exact Classical.choose_spec ( exists_CW_maximizer A hA ) |>.2;
        convert h_r_ge_CW_y ( ( ∑ i, vecAbsC v i ) ⁻¹ • vecAbsC v ) _ using 1;
        · rw [ CW_homogenous ];
          exact inv_pos.mpr ( lt_of_lt_of_le ( norm_pos_iff.mpr ( Classical.choose_spec ( Function.ne_iff.mp hv_ne ) ) ) ( Finset.single_le_sum ( fun i _ => norm_nonneg ( v i ) ) ( Finset.mem_univ ( Classical.choose ( Function.ne_iff.mp hv_ne ) ) ) ) );
        · refine' ⟨ _, _ ⟩;
          · exact fun i => mul_nonneg ( inv_nonneg.2 ( Finset.sum_nonneg fun _ _ => norm_nonneg _ ) ) ( norm_nonneg _ );
          · simp +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul, show ( ∑ i, vecAbsC v i ) ≠ 0 from ne_of_gt ( lt_of_lt_of_le ( norm_pos_iff.mpr ( Classical.choose_spec ( Function.ne_iff.mp hv_ne ) ) ) ( Finset.single_le_sum ( fun i _ => norm_nonneg ( v i ) ) ( Finset.mem_univ ( Classical.choose ( Function.ne_iff.mp hv_ne ) ) ) ) ) ];
      convert h_CW_ge.trans h_r_ge_CW_y using 1;
      rw [ CW_perronVector_eq_perronRoot ] ; norm_cast;

/-
The transpose of a positive matrix is positive.
-/
lemma Matrix.transpose_isPositive {n : Type*} [Fintype n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    A.transpose.IsPositive := by
      exact fun i j => hA j i

/-
The Perron root of A is equal to the Perron root of A transpose.
-/
lemma perronRoot_transpose_eq {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    perronRoot A.transpose (Matrix.transpose_isPositive A hA) = perronRoot A hA := by
      by_contra h_neq;
      -- Without loss of generality, assume that the Perron root of A is greater than the Perron root of A transpose.
      wlog h_wlog : perronRoot A.transpose (Matrix.transpose_isPositive A hA) < perronRoot A hA generalizing A hA;
      · apply this A.transpose (Matrix.transpose_isPositive A hA) (Ne.symm h_neq) (lt_of_le_of_ne (le_of_not_gt h_wlog) (Ne.symm h_neq));
      · -- Let $v$ be the Perron vector of $A$ and $u$ be the Perron vector of $A^T$.
        obtain ⟨v, hv⟩ : ∃ v ∈ stdSimplex ℝ n, A.mulVec v = (perronRoot A hA) • v ∧ Matrix.IsPositiveVec v := by
          refine' ⟨ perronVector A hA, perronVector_mem_stdSimplex A hA, perronVector_is_eigenvector A hA, perronVector_pos A hA ⟩
        obtain ⟨u, hu⟩ : ∃ u ∈ stdSimplex ℝ n, (A.transpose).mulVec u = (perronRoot A.transpose (Matrix.transpose_isPositive A hA)) • u ∧ Matrix.IsPositiveVec u := by
          have := perronVector_is_eigenvector A.transpose ( Matrix.transpose_isPositive A hA );
          refine' ⟨ perronVector A.transpose ( Matrix.transpose_isPositive A hA ), perronVector_mem_stdSimplex A.transpose ( Matrix.transpose_isPositive A hA ), this, perronVector_pos A.transpose ( Matrix.transpose_isPositive A hA ) ⟩;
        -- Taking the dot product of both sides of $A v = r v$ with $u$, we get $u^T A v = r u^T v$.
        have h_dot : ∑ i, u i * (A.mulVec v) i = perronRoot A hA * ∑ i, u i * v i := by
          simp +decide [ hv.2.1, Finset.mul_sum _ _ _, mul_assoc, mul_left_comm, Finset.sum_mul ];
        -- Taking the dot product of both sides of $A^T u = \rho u$ with $v$, we get $u^T A v = \rho u^T v$.
        have h_dot_transpose : ∑ i, u i * (A.mulVec v) i = perronRoot A.transpose (Matrix.transpose_isPositive A hA) * ∑ i, u i * v i := by
          have h_dot_transpose : ∑ i, u i * (A.mulVec v) i = ∑ i, (A.transpose.mulVec u) i * v i := by
            simp +decide [ Matrix.mulVec, dotProduct, mul_comm ];
            simp +decide only [Finset.mul_sum _ _ _, mul_left_comm];
            exact Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring );
          simp_all +decide [ Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm ];
        exact h_wlog.ne ( mul_left_cancel₀ ( show ( ∑ i, u i * v i ) ≠ 0 from ne_of_gt <| Finset.sum_pos ( fun i _ => mul_pos ( hu.2.2 i ) ( hv.2.2 i ) ) ⟨ Classical.arbitrary n, Finset.mem_univ _ ⟩ ) <| by linarith )

/-
Any non-negative non-zero eigenvector of a positive matrix has eigenvalue equal to the Perron root.
-/
lemma eigenvalue_eq_perronRoot_of_nonneg_eigenvector {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (hv : Matrix.IsNonnegVec v) (hv_ne : v ≠ 0) (μ : ℝ) (h_eig : A.mulVec v = μ • v) :
    μ = perronRoot A hA := by
      -- Let $u$ be the Perron vector of $A^T$.
      obtain ⟨u, hu⟩ : ∃ u : n → ℝ, Matrix.IsPositiveVec u ∧ A.transpose.mulVec u = (perronRoot A hA) • u := by
        have := perronVector_is_eigenvector A.transpose ( Matrix.transpose_isPositive A hA );
        refine' ⟨ perronVector A.transpose ( Matrix.transpose_isPositive A hA ), _, _ ⟩;
        · exact?;
        · rw [ this, perronRoot_transpose_eq ];
      -- Multiply by $u^T$: $u^T A v = \mu u^T v$.
      have h_mul : ∑ i, u i * (A.mulVec v) i = μ * ∑ i, u i * v i := by
        simp +decide [ h_eig, mul_assoc, mul_left_comm, Finset.mul_sum _ _ _ ];
      -- Also $u^T A = (A^T u)^T = (r u)^T = r u^T$ where $r = \text{perronRoot} A^T = \text{perronRoot} A$.
      have h_mul_transpose : ∑ i, u i * (A.mulVec v) i = perronRoot A hA * ∑ i, u i * v i := by
        have h_mul_transpose : ∑ i, u i * (A.mulVec v) i = ∑ i, (A.transpose.mulVec u) i * v i := by
          simp +decide [ Matrix.mulVec, dotProduct, mul_comm ];
          simpa only [ Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm ] using Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring );
        simp_all +decide [ Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm ];
      -- Since $u > 0$ and $v \ge 0, v \ne 0$, the dot product $u^T v > 0$.
      have h_dot_pos : 0 < ∑ i, u i * v i := by
        -- Since $u$ is strictly positive and $v$ is non-negative and non-zero, there exists some $i$ such that $v_i > 0$.
        obtain ⟨i, hi⟩ : ∃ i, v i > 0 := by
          exact Function.ne_iff.mp hv_ne |> Exists.imp fun i hi => lt_of_le_of_ne ( hv i ) ( Ne.symm hi );
        exact lt_of_lt_of_le ( mul_pos ( hu.1 i ) hi ) ( Finset.single_le_sum ( fun i _ => mul_nonneg ( le_of_lt ( hu.1 i ) ) ( hv i ) ) ( Finset.mem_univ i ) );
      nlinarith

/-
The Perron vector is unique up to scalar multiplication among non-negative non-zero eigenvectors.
-/
lemma perronVector_unique {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (hv : Matrix.IsNonnegVec v) (hv_ne : v ≠ 0) (μ : ℝ) (h_eig : A.mulVec v = μ • v) :
    ∃ c : ℝ, v = c • perronVector A hA := by
      by_contra h_nonunique;
      -- Let $c = \min_i (v_i / p_i)$.
      obtain ⟨c, hc⟩ : ∃ c, ∀ i, v i ≥ c * perronVector A hA i ∧ ∃ i, v i = c * perronVector A hA i := by
        obtain ⟨c, hc⟩ : ∃ c, c ∈ Set.image (fun i => v i / perronVector A hA i) Set.univ ∧ ∀ i ∈ Set.image (fun i => v i / perronVector A hA i) Set.univ, c ≤ i := by
          exact ⟨ Finset.min' ( Set.toFinset ( Set.image ( fun i => v i / perronVector A hA i ) Set.univ ) ) ⟨ _, Set.mem_toFinset.mpr ( Set.mem_image_of_mem _ ( Set.mem_univ ( Classical.arbitrary n ) ) ) ⟩, Set.mem_toFinset.mp ( Finset.min'_mem _ _ ), fun i hi => Finset.min'_le _ _ ( Set.mem_toFinset.mpr hi ) ⟩;
        simp +zetaDelta at *;
        exact ⟨ c, fun i => ⟨ by have := hc.2 i; rw [ le_div_iff₀ ( show 0 < perronVector A hA i from perronVector_pos A hA i ) ] at this; linarith, by obtain ⟨ y, rfl ⟩ := hc.1; exact ⟨ y, by rw [ div_mul_cancel₀ _ ( ne_of_gt ( perronVector_pos A hA y ) ) ] ⟩ ⟩ ⟩;
      -- Let $w = v - c \cdot p$. Then $w$ is an eigenvector with eigenvalue $r$.
      set w : n → ℝ := v - c • perronVector A hA
      have hw_eig : A.mulVec w = μ • w := by
        have hw_eig : A.mulVec (c • perronVector A hA) = μ • (c • perronVector A hA) := by
          have hw_eig : A.mulVec (perronVector A hA) = μ • perronVector A hA := by
            convert eigenvalue_eq_perronRoot_of_nonneg_eigenvector A hA v hv hv_ne μ h_eig ▸ perronVector_is_eigenvector A hA using 1;
          rw [ Matrix.mulVec_smul, hw_eig, smul_smul, mul_comm ];
          rw [ MulAction.mul_smul ];
        rw [ Matrix.mulVec_sub, h_eig, hw_eig, smul_sub ];
      -- Since $w$ is an eigenvector with eigenvalue $r$ and $w \ge 0$, by `Matrix.isPositiveVec_of_eigenvector`, $w$ must be strictly positive.
      have hw_pos : Matrix.IsPositiveVec w := by
        have hw_pos : Matrix.IsNonnegVec w ∧ w ≠ 0 := by
          exact ⟨ fun i => sub_nonneg.2 ( hc i |>.1 ), fun hw => h_nonunique ⟨ c, sub_eq_zero.1 hw ⟩ ⟩;
        apply Matrix.isPositiveVec_of_eigenvector A (Matrix.isNonneg_of_isPositive A hA) (Matrix.isIrreducible_of_isPositive A hA) w hw_pos.left hw_pos.right μ hw_eig;
      obtain ⟨ i, hi ⟩ := hc ( Classical.arbitrary n ) |>.2; specialize hw_pos i; aesop;

/-
If v is an eigenvector with eigenvalue mu such that |mu| = r, then |v| is an eigenvector of A with eigenvalue r.
-/
lemma abs_eigenvector_is_eigenvector_of_norm_eq_perronRoot {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (μ : ℂ) (v : n → ℂ) (hv_ne : v ≠ 0) (h_eig : (A.map Complex.ofReal).mulVec v = μ • v) (h_norm : ‖μ‖ = perronRoot A hA) :
    A.mulVec (vecAbsC v) = (perronRoot A hA) • (vecAbsC v) := by
      -- By Lemma 25, $r x \le A x$.
      have h_le : perronRoot A hA • vecAbsC v ≤ A.mulVec (vecAbsC v) := by
        have h_abs : vecAbsC ((A.map Complex.ofReal).mulVec v) = perronRoot A hA • vecAbsC v := by
          ext i; simp +decide [ h_eig, h_norm ] ;
          simp +decide [ ← h_norm, vecAbsC ];
        exact h_abs ▸ Matrix.abs_mulVec_le_mulVec_abs_complex A ( Matrix.isNonneg_of_isPositive A hA ) v;
      by_contra h_neq;
      have h_gt : CW A (A.mulVec (vecAbsC v)) > (perronRoot A hA : WithTop ℝ) := by
        apply_rules [ CW_gt_of_le_of_ne ];
        · exact fun i => norm_nonneg _;
        · exact fun h => hv_ne <| funext fun i => norm_eq_zero.mp <| congr_fun h i;
      -- Since $A.mulVec (vecAbsC v)$ is a positive vector, we can scale it to be in the simplex.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, 0 < c ∧ c • A.mulVec (vecAbsC v) ∈ stdSimplex ℝ n := by
        have h_pos : ∀ i, 0 < (A.mulVec (vecAbsC v)) i := by
          intro i
          have h_pos : ∃ j, 0 < (A i j) * ‖v j‖ := by
            by_cases h_zero : ∀ j, v j = 0;
            · exact False.elim ( hv_ne ( funext h_zero ) );
            · exact Exists.elim ( not_forall.mp h_zero ) fun j hj => ⟨ j, mul_pos ( hA i j ) ( norm_pos_iff.mpr hj ) ⟩;
          obtain ⟨ j, hj ⟩ := h_pos;
          exact lt_of_lt_of_le hj ( by simpa [ Matrix.mulVec, dotProduct ] using Finset.single_le_sum ( fun a _ => mul_nonneg ( le_of_lt ( hA i a ) ) ( norm_nonneg ( v a ) ) ) ( Finset.mem_univ j ) );
        refine' ⟨ 1 / ∑ i, ( A.mulVec ( vecAbsC v ) ) i, _, _ ⟩ <;> simp_all +decide [ stdSimplex ];
        · exact Finset.sum_pos ( fun i _ => h_pos i ) Finset.univ_nonempty;
        · exact ⟨ Finset.sum_nonneg fun _ _ => le_of_lt ( h_pos _ ), by rw [ ← Finset.mul_sum _ _ _, inv_mul_cancel₀ ( ne_of_gt ( Finset.sum_pos ( fun _ _ => h_pos _ ) Finset.univ_nonempty ) ) ] ⟩;
      -- By Lemma 25, $CW(A.mulVec (vecAbsC v)) \le r$.
      have h_le_r : CW A (c • A.mulVec (vecAbsC v)) ≤ (perronRoot A hA : WithTop ℝ) := by
        have := Classical.choose_spec ( exists_CW_maximizer A hA );
        convert this.2 hc.2 using 1;
        rw [ show CW A ( Classical.choose ( exists_CW_maximizer A hA ) ) = ( perronRoot A hA : WithTop ℝ ) from CW_perronVector_eq_perronRoot A hA ];
        rfl;
      have h_eq : CW A (c • A.mulVec (vecAbsC v)) = CW A (A.mulVec (vecAbsC v)) := by
        apply CW_homogenous A (A.mulVec (vecAbsC v)) c hc.left;
      exact h_gt.not_le ( h_eq ▸ h_le_r )

/-
For a positive matrix, the only eigenvalue with modulus equal to the Perron root is the Perron root itself.
-/
lemma eigenvalue_eq_perronRoot_of_norm_eq_perronRoot {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (μ : ℂ) (v : n → ℂ) (hv_ne : v ≠ 0) (h_eig : (A.map Complex.ofReal).mulVec v = μ • v) (h_norm : ‖μ‖ = perronRoot A hA) :
    μ = perronRoot A hA := by
      -- By definition of absolute value, $|v| = c p$ for some $c > 0$. Thus $|v| > 0$, so $v_i \ne 0$ for all $i$.
      have hv_pos : Matrix.IsPositiveVec (vecAbsC v) := by
        have h_abs_eigenvector : A.mulVec (vecAbsC v) = perronRoot A hA • vecAbsC v := by
          convert abs_eigenvector_is_eigenvector_of_norm_eq_perronRoot A hA μ v hv_ne h_eig h_norm;
        apply Matrix.isPositiveVec_of_eigenvector A (Matrix.isNonneg_of_isPositive A hA) (Matrix.isIrreducible_of_isPositive A hA) (vecAbsC v) (by
        exact fun i => norm_nonneg _) (by
        contrapose! hv_ne; ext i; simp_all +decide [ funext_iff, Complex.ext_iff ] ;
        simp_all +decide [ vecAbsC ]) (perronRoot A hA) h_abs_eigenvector;
      -- So $|(A v)_i| = |(\mu v)_i| = r |v_i| = (A |v|)_i = \sum_j A_{ij} |v_j|$.
      have h_eq : ∀ i, ‖((A.map Complex.ofReal).mulVec v) i‖ = ∑ j, A i j * ‖v j‖ := by
        intro i
        have h_abs_eq : ‖(A.map Complex.ofReal).mulVec v i‖ = perronRoot A hA * ‖v i‖ := by
          aesop
        have h_sum_eq : ∑ j, A i j * ‖v j‖ = perronRoot A hA * ‖v i‖ := by
          have h_sum_eq : A.mulVec (vecAbsC v) = (perronRoot A hA) • (vecAbsC v) := by
            apply abs_eigenvector_is_eigenvector_of_norm_eq_perronRoot A hA μ v hv_ne h_eig h_norm;
          simpa [ Matrix.mulVec, dotProduct ] using congr_fun h_sum_eq i
        rw [h_abs_eq, h_sum_eq];
      -- Since $|(A v)_i| = \sum_j A_{ij} |v_j|$, by the equality case of the triangle inequality, all terms $A_{ij} v_j$ must have the same argument.
      have h_arg : ∀ i j, A i j ≠ 0 → ∃ θ : ℝ, ∀ k, A i k ≠ 0 → v k = Complex.exp (θ * Complex.I) * ‖v k‖ := by
        intro i j hij
        have h_arg_eq : ∀ k, A i k ≠ 0 → Complex.arg (v k) = Complex.arg (v j) := by
          intro k hk
          have h_arg_eq : Complex.re (starRingEnd ℂ (v j) * v k) = ‖v j‖ * ‖v k‖ := by
            have h_arg_eq : ‖∑ x, A i x • v x‖^2 = (∑ x, A i x * ‖v x‖)^2 := by
              simp_all +decide [ Matrix.mulVec, dotProduct ];
            have h_arg_eq : ∑ x, ∑ y, A i x * A i y * Complex.re (starRingEnd ℂ (v x) * v y) = ∑ x, ∑ y, A i x * A i y * ‖v x‖ * ‖v y‖ := by
              convert h_arg_eq using 1 <;> simp +decide [ Complex.normSq, Complex.sq_norm, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] ; ring!;
              · simp +decide only [Finset.sum_add_distrib];
              · simp +decide only [pow_two, Finset.mul_sum _ _ _, mul_comm, mul_left_comm,
                                  mul_assoc];
            contrapose! h_arg_eq;
            refine' ne_of_lt ( Finset.sum_lt_sum _ _ );
            · intro x hx;
              refine' Finset.sum_le_sum fun y hy => _;
              have h_arg_eq : Complex.re (starRingEnd ℂ (v x) * v y) ≤ ‖v x‖ * ‖v y‖ := by
                simpa [ Complex.normSq, Complex.norm_def ] using Complex.re_le_norm ( starRingEnd ℂ ( v x ) * v y );
              simpa only [ mul_assoc ] using mul_le_mul_of_nonneg_left h_arg_eq ( mul_nonneg ( le_of_lt ( hA i x ) ) ( le_of_lt ( hA i y ) ) );
            · refine' ⟨ j, Finset.mem_univ _, Finset.sum_lt_sum _ _ ⟩;
              · intro x hx;
                have h_arg_eq : Complex.re (starRingEnd ℂ (v j) * v x) ≤ ‖v j‖ * ‖v x‖ := by
                  simpa [ Complex.normSq, Complex.norm_def ] using Complex.re_le_norm ( starRingEnd ℂ ( v j ) * v x );
                simpa only [ mul_assoc ] using mul_le_mul_of_nonneg_left h_arg_eq ( mul_nonneg ( le_of_lt ( hA i j ) ) ( le_of_lt ( hA i x ) ) );
              · refine' ⟨ k, Finset.mem_univ _, _ ⟩;
                have h_arg_eq : Complex.re (starRingEnd ℂ (v j) * v k) < ‖v j‖ * ‖v k‖ := by
                  exact lt_of_le_of_ne ( by simpa [ Complex.normSq, Complex.norm_def ] using Complex.re_le_norm ( starRingEnd ℂ ( v j ) * v k ) ) h_arg_eq;
                simpa only [ mul_assoc ] using mul_lt_mul_of_pos_left h_arg_eq ( mul_pos ( lt_of_le_of_ne ( le_of_lt ( hA i j ) ) ( Ne.symm hij ) ) ( lt_of_le_of_ne ( le_of_lt ( hA i k ) ) ( Ne.symm hk ) ) );
          rw [ Complex.arg_eq_arg_iff ];
          · by_cases hj : v j = 0 <;> by_cases hk : v k = 0 <;> simp_all +decide [ Complex.ext_iff, div_eq_mul_inv ];
            · have := hv_pos k; simp_all +decide [ vecAbsC ] ;
              exact False.elim ( this ( Complex.ext hk.1 hk.2 ) );
            · field_simp;
              rw [ div_eq_iff, div_eq_iff ];
              · have h_arg_eq : (‖v j‖ * (v k).re - (v j).re * ‖v k‖)^2 + (‖v j‖ * (v k).im - (v j).im * ‖v k‖)^2 = 0 := by
                  nlinarith [ sq_nonneg ( ‖v j‖ - ‖v k‖ ), Complex.normSq_apply ( v j ), Complex.normSq_apply ( v k ), Complex.sq_norm ( v j ), Complex.sq_norm ( v k ) ];
                exact ⟨ by nlinarith only [ h_arg_eq ], by nlinarith only [ h_arg_eq ] ⟩;
              · exact ne_of_gt ( hv_pos k );
              · exact ne_of_gt ( hv_pos k );
          · intro h; specialize hv_pos k; simp_all +decide [ Matrix.IsPositiveVec ] ;
            exact hv_pos.ne' ( by simp +decide [ h, vecAbsC ] );
          · intro h; simp_all +decide [ Matrix.IsPositiveVec ] ;
            exact absurd ( hv_pos j ) ( by simp +decide [ h, vecAbsC ] );
        use Complex.arg (v j);
        intro k hk; rw [ ← Complex.norm_mul_exp_arg_mul_I ( v k ) ] ; simp +decide [ h_arg_eq k hk ] ; ring;
      -- Since $A$ is positive, all $A_{ij}$ are positive, so all $v_j$ must have the same argument.
      have h_arg_all : ∃ θ : ℝ, ∀ j, v j = Complex.exp (θ * Complex.I) * ‖v j‖ := by
        exact Exists.elim ( h_arg ( Classical.arbitrary n ) ( Classical.arbitrary n ) ( ne_of_gt ( hA ( Classical.arbitrary n ) ( Classical.arbitrary n ) ) ) ) fun θ hθ => ⟨ θ, fun j => hθ j ( ne_of_gt ( hA ( Classical.arbitrary n ) j ) ) ⟩;
      -- Since $v = e^{i \theta} |v|$, we have $A v = A (e^{i \theta} |v|) = e^{i \theta} A |v| = e^{i \theta} r |v| = r v$.
      obtain ⟨θ, hθ⟩ := h_arg_all
      have h_mul : (A.map Complex.ofReal).mulVec v = (perronRoot A hA : ℂ) • v := by
        have h_mul : (A.map Complex.ofReal).mulVec (fun j => Complex.exp (θ * Complex.I) * ‖v j‖) = (perronRoot A hA : ℂ) • (fun j => Complex.exp (θ * Complex.I) * ‖v j‖) := by
          have h_mul : A.mulVec (vecAbsC v) = (perronRoot A hA : ℝ) • vecAbsC v := by
            apply abs_eigenvector_is_eigenvector_of_norm_eq_perronRoot A hA μ v hv_ne h_eig h_norm
            skip
          generalize_proofs at *; (
          ext i; simp +decide [ Matrix.mulVec, dotProduct, h_mul ] ; ring;
          convert congr_arg ( fun x : ℝ => Complex.exp ( θ * Complex.I ) * x ) ( congr_fun h_mul i ) using 1 <;> simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ];
          · simp +decide [ Matrix.mulVec, dotProduct, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ];
            exact Finset.sum_congr rfl fun _ _ => by rw [ mul_comm ( Complex.exp _ ) ] ; rfl;
          · exact Or.inl ( mul_comm _ _ ))
        generalize_proofs at *; (
        convert h_mul using 1 <;> congr! 1 <;> simp +decide [ ← hθ ]);
      exact smul_left_injective _ hv_ne <| h_eig.symm.trans h_mul

/-
The derivative of the characteristic polynomial evaluated at x is equal to the trace of the adjugate of (xI - A).
-/
lemma charpoly_derivative_eval_eq_trace_adjugate {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) (x : ℝ) :
    (Matrix.charpoly A).derivative.eval x = Matrix.trace (Matrix.adjugate (x • 1 - A)) := by
      rw [ Matrix.charpoly, Matrix.det_apply' ];
      simp +decide [ Polynomial.eval_finset_sum, Polynomial.eval_prod, Matrix.trace, Matrix.adjugate_apply, Matrix.det_apply' ];
      rw [ Finset.sum_congr rfl ];
      rotate_right;
      use fun σ => ∑ i, ( Equiv.Perm.sign σ : ℝ ) * ( if σ i = i then 1 else 0 ) * ∏ j ∈ Finset.univ.erase i, ( x • 1 - A ) ( σ j ) j;
      · rw [ Finset.sum_comm ];
        refine' Finset.sum_congr rfl fun i hi => _;
        refine' Finset.sum_congr rfl fun σ _ => _;
        by_cases hi' : σ i = i <;> simp +decide [ hi', Matrix.updateRow_apply ];
        · rw [ ← Finset.prod_erase_mul _ _ hi ];
          simp +decide [ hi', Pi.single_apply ];
          refine' Finset.prod_congr rfl fun j hj => _ ; aesop;
        · rw [ Finset.prod_eq_zero_iff ];
          use σ.symm i;
          simp +decide [ hi', Pi.single_apply ];
          grind;
      · intro σ _;
        erw [ Polynomial.derivative_prod ];
        erw [ Polynomial.eval_finset_sum ];
        rw [ Finset.mul_sum _ _ _ ];
        refine' Finset.sum_congr rfl fun i _ => _;
        by_cases hi : σ i = i <;> simp +decide [ hi, Polynomial.eval_prod ];
        simp +decide [ Polynomial.eval_multiset_prod, Matrix.one_apply ];
        exact congr_arg _ ( Multiset.map_congr rfl fun j hj => by aesop )

/-
Any real eigenvector corresponding to the Perron root is a scalar multiple of the Perron vector.
-/
lemma eigenvector_eq_smul_perronVector {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive)
    (v : n → ℝ) (h_eig : A.mulVec v = (perronRoot A hA) • v) :
    ∃ c : ℝ, v = c • perronVector A hA := by
      -- If $v$ is a scalar multiple of the Perron vector, then we are done.
      by_cases hv_zero : v = 0;
      · exact ⟨ 0, by simpa ⟩;
      · -- If $v$ is not non-negative, then consider $c = \max_i (-v_i / p_i) + 1$.
        set c := sSup (Set.image (fun i => -v i / perronVector A hA i) Set.univ) + 1;
        -- Then $v + c p$ is strictly positive.
        have hv_pos : ∀ i, 0 < v i + c * perronVector A hA i := by
          intro i
          have h_pos : -v i / perronVector A hA i < c := by
            exact lt_add_of_le_of_pos ( le_csSup ( by exact Set.Finite.bddAbove ( Set.toFinite _ ) ) ( Set.mem_image_of_mem _ ( Set.mem_univ _ ) ) ) zero_lt_one;
          rw [ div_lt_iff₀ ] at h_pos <;> nlinarith [ show 0 < perronVector A hA i from perronVector_pos A hA i ];
        -- By `perronVector_unique`, $v + c p$ is a scalar multiple of $p$.
        obtain ⟨k, hk⟩ : ∃ k : ℝ, v + c • perronVector A hA = k • perronVector A hA := by
          apply perronVector_unique A hA (v + c • perronVector A hA) (by
          exact fun i => le_of_lt ( hv_pos i )) (by
          exact fun h => hv_zero <| by ext i; have := congr_fun h i; norm_num at *; linarith [ hv_pos i ] ;) (perronRoot A hA) (by
          rw [ Matrix.mulVec_add, Matrix.mulVec_smul, h_eig, smul_add ];
          rw [ perronVector_is_eigenvector ] ; ext i ; simp +decide [ mul_assoc, mul_comm, mul_left_comm ]);
        exact ⟨ k - c, by ext i; have := congr_fun hk i; norm_num at *; linarith ⟩

/-
Check if Matrix.rank is available.
-/
#check Matrix.rank

/-
Define the left Perron vector and prove it is a positive eigenvector of A transpose with the same eigenvalue.
-/
noncomputable def leftPerronVector {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) : n → ℝ :=
  perronVector A.transpose (Matrix.transpose_isPositive A hA)

lemma leftPerronVector_pos {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    Matrix.IsPositiveVec (leftPerronVector A hA) :=
  perronVector_pos A.transpose (Matrix.transpose_isPositive A hA)

lemma leftPerronVector_is_eigenvector {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    A.transpose.mulVec (leftPerronVector A hA) = (perronRoot A hA) • (leftPerronVector A hA) := by
  rw [← perronRoot_transpose_eq A hA]
  exact perronVector_is_eigenvector A.transpose (Matrix.transpose_isPositive A hA)

/-
The geometric multiplicity of the Perron root is 1.
-/
lemma geometric_multiplicity_one {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    Module.finrank ℝ (LinearMap.ker (Matrix.toLin' (perronRoot A hA • 1 - A))) = 1 := by
      -- By `eigenvector_eq_smul_perronVector`, any such eigenvector is a scalar multiple of the Perron vector.
      have h_ker_eq_span : LinearMap.ker (Matrix.toLin' ((perronRoot A hA) • 1 - A)) = Submodule.span ℝ {perronVector A hA} := by
        refine' le_antisymm _ _;
        · intro v hv; simp_all +decide [ Matrix.sub_mulVec, Matrix.smul_eq_diagonal_mul ] ;
          obtain ⟨ c, hc ⟩ := eigenvector_eq_smul_perronVector A hA v ( by
            exact eq_of_sub_eq_zero hv ▸ rfl );
          exact hc.symm ▸ Submodule.smul_mem _ _ ( Submodule.subset_span ( Set.mem_singleton _ ) );
        · simp +decide [ Matrix.sub_mulVec, perronVector_is_eigenvector ];
      rw [ h_ker_eq_span, finrank_span_singleton ];
      exact fun h => by have := perronVector_mem_stdSimplex A hA; simp_all +decide [ stdSimplex ] ;

/-
If the geometric multiplicity is 1, the rank of (rI - A) is n - 1.
-/
lemma rank_eq_card_sub_one_of_geometric_multiplicity_one {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) (r : ℝ)
    (h_geom : Module.finrank ℝ (LinearMap.ker (Matrix.toLin' (r • 1 - A))) = 1) :
    Matrix.rank (r • 1 - A) = Fintype.card n - 1 := by
      have := LinearMap.finrank_range_add_finrank_ker ( Matrix.toLin' ( r • 1 - A ) ) ; simp_all +decide [ Matrix.rank ] ;
      exact eq_tsub_of_add_eq this

/-
Check Matrix.adjugate_apply
-/
#check Matrix.adjugate_apply

/-
Check Matrix.rank_transpose
-/
#check Matrix.rank_transpose

/-
Check if Fintype instance for subtype is available.
-/
example {n : Type*} [Fintype n] [DecidableEq n] (i : n) : Fintype { x // x ≠ i } := by infer_instance

#check Matrix.vecMul
#check Matrix.vecMulVec

/-
If the rank of a matrix is n-1, its determinant is 0.
-/
lemma det_eq_zero_of_rank_eq_card_sub_one {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ)
    (h_rank : Matrix.rank A = Fintype.card n - 1) :
    Matrix.det A = 0 := by
      rw [ Matrix.rank ] at h_rank;
      contrapose! h_rank;
      rw [ @LinearMap.finrank_range_of_inj ];
      · simp +decide [ Module.finrank_pi ];
        exact ne_of_gt ( Nat.sub_lt ( Fintype.card_pos ) zero_lt_one );
      · exact fun x y hxy => by simpa [ h_rank, isUnit_iff_ne_zero ] using congr_arg ( fun z => A⁻¹.mulVec z ) hxy;

/-
If the rank of a matrix is n-1, the rank of its adjugate is at most 1.
-/
lemma rank_adjugate_le_one_of_rank_eq_card_sub_one {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ)
    (h_rank : Matrix.rank A = Fintype.card n - 1) :
    Matrix.rank (Matrix.adjugate A) ≤ 1 := by
      -- Since the rank of A is n-1, the determinant of A is zero.
      have h_det_zero : Matrix.det A = 0 := by
        exact?
      generalize_proofs at *; (
      -- Since $A * \text{adj}(A) = 0$, the image of $\text{adj}(A)$ is contained in the kernel of $A$.
      have h_image_adj_subset_kernel_A : LinearMap.range (Matrix.toLin' A.adjugate) ≤ LinearMap.ker (Matrix.toLin' A) := by
        have h_image_adj_subset_kernel_A : A * A.adjugate = 0 := by
          simp +decide [ h_det_zero, Matrix.mul_adjugate ]
        generalize_proofs at * ; (
        intro x hx; obtain ⟨ y, rfl ⟩ := hx; simp +decide [ ← Matrix.mul_assoc, h_image_adj_subset_kernel_A ] ;)
      generalize_proofs at *; (
      have := LinearMap.finrank_range_add_finrank_ker ( Matrix.toLin' A ) ; simp_all +decide [ Matrix.rank ] ;
      exact le_trans ( Submodule.finrank_mono h_image_adj_subset_kernel_A ) ( by linarith! [ Nat.sub_add_cancel ( show 1 ≤ Fintype.card n from Fintype.card_pos ) ] ) ;))

#check Matrix.adjugate_apply

#print Matrix.rank

/-
If M has rank n-1, and v is in the kernel and u is in the left kernel (both non-zero), then the adjugate of M is a scalar multiple of the outer product v u^T.
-/
lemma adjugate_eq_smul_vecMulVec_of_rank_eq_card_sub_one {n : Type*} [Fintype n] [DecidableEq n] (M : Matrix n n ℝ)
    (u v : n → ℝ) (hu : u ≠ 0) (hv : v ≠ 0)
    (h_rank : Matrix.rank M = Fintype.card n - 1)
    (h_ker : M.mulVec v = 0)
    (h_left_ker : M.vecMul u = 0) :
    ∃ c : ℝ, Matrix.adjugate M = c • Matrix.vecMulVec v u := by
      by_contra h_contra;
      -- Since adj(M) has rank 1, there exists a vector w such that adj(M) = w • u^T.
      obtain ⟨w, hw⟩ : ∃ w : n → ℝ, M.adjugate = Matrix.vecMulVec w u := by
        have h_adj_rank : ∀ i : n, ∃ c : ℝ, M.adjugate i = c • u := by
          intro i
          have h_adj_row : Matrix.vecMul (M.adjugate i) M = 0 := by
            have h_adj_row : M.adjugate * M = 0 := by
              simp +decide [ Matrix.adjugate_mul ];
              have h_det_zero : Matrix.rank M < Fintype.card n := by
                exact h_rank.symm ▸ Nat.pred_lt ( ne_bot_of_gt ( Fintype.card_pos_iff.mpr ⟨ i ⟩ ) );
              contrapose! h_det_zero;
              have := Matrix.rank_mul_le_left M ( M⁻¹ ) ; simp_all +decide [ isUnit_iff_ne_zero ] ;
            exact funext fun j => by simpa [ Matrix.mul_apply ] using congr_fun ( congr_fun h_adj_row i ) j;
          have h_adj_row : ∀ w : n → ℝ, Matrix.vecMul w M = 0 → ∃ c : ℝ, w = c • u := by
            have h_adj_row : Module.finrank ℝ (LinearMap.ker (Matrix.toLin' (Matrix.transpose M))) = 1 := by
              have := LinearMap.finrank_range_add_finrank_ker ( Matrix.toLin' M.transpose ) ; simp_all +decide [ Matrix.rank ] ;
              have h_adj_row : Module.finrank ℝ (LinearMap.range (Matrix.toLin' M.transpose)) = Fintype.card n - 1 := by
                convert h_rank using 1;
                convert Matrix.rank_transpose M using 1;
              linarith [ Nat.sub_add_cancel ( show 1 ≤ Fintype.card n from Fintype.card_pos_iff.mpr ⟨ i ⟩ ) ];
            have h_adj_row : Submodule.span ℝ {u} = LinearMap.ker (Matrix.toLin' (Matrix.transpose M)) := by
              refine' Submodule.eq_of_le_of_finrank_eq _ _;
              · simp_all +decide [ ← Matrix.mulVec_transpose ];
              · rw [ h_adj_row, finrank_span_singleton ] ; aesop;
            intro w hw; replace h_adj_row := SetLike.ext_iff.mp h_adj_row w; simp_all +decide [ Submodule.mem_span_singleton ] ;
            simp_all +decide [ funext_iff, Matrix.vecMul, Matrix.mulVec ];
            simp_all +decide [ dotProduct, mul_comm ];
            exact ⟨ h_adj_row.choose, fun x => h_adj_row.choose_spec x ▸ rfl ⟩;
          exact h_adj_row _ ‹_›;
        choose c hc using h_adj_rank;
        use c;
        ext i j; simp +decide [ hc, Matrix.vecMulVec ] ;
      -- Since $M * adj(M) = 0$, substituting $adj(M) = w • u^T$ gives $M * (w • u^T) = 0$. This implies that $w$ is in the kernel of $M$.
      have h_w_kernel : M.mulVec w = 0 := by
        have h_w_kernel : M * Matrix.vecMulVec w u = 0 := by
          simp +decide [ ← hw, Matrix.mul_adjugate ];
          exact Or.inl ( by rw [ Matrix.rank ] at h_rank; exact Matrix.exists_mulVec_eq_zero_iff.mp ⟨ v, hv, h_ker ⟩ );
        simp_all +decide [ ← Matrix.ext_iff, Matrix.mulVec, Matrix.vecMulVec ];
        simp_all +decide [ funext_iff, Matrix.mul_apply ];
        simp_all +decide [ ← mul_assoc, ← Finset.mul_sum _ _ _, ← Finset.sum_mul, Matrix.mulVec, dotProduct ];
        exact fun i => Or.resolve_right ( h_w_kernel i hu.choose ) hu.choose_spec;
      -- Since $v$ spans the kernel of $M$, there exists a scalar $c$ such that $w = c • v$.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, w = c • v := by
        have h_kernel : LinearMap.ker (Matrix.mulVecLin M) = Submodule.span ℝ {v} := by
          refine' Submodule.eq_of_le_of_finrank_eq _ _;
          · intro x hx; have := LinearMap.finrank_range_add_finrank_ker ( Matrix.mulVecLin M ) ; simp_all +decide [ Matrix.rank ] ;
            have h_kernel : Module.finrank ℝ (LinearMap.ker (Matrix.mulVecLin M)) = 1 := by
              linarith [ Nat.sub_add_cancel ( show 1 ≤ Fintype.card n from Fintype.card_pos_iff.mpr ⟨ Classical.choose ( Function.ne_iff.mp hv ) ⟩ ) ];
            have h_kernel : Submodule.span ℝ {v} = LinearMap.ker (Matrix.mulVecLin M) := by
              exact Submodule.eq_of_le_of_finrank_eq ( Submodule.span_le.mpr ( Set.singleton_subset_iff.mpr ( by aesop ) ) ) ( by rw [ h_kernel, finrank_span_singleton ] ; aesop );
            exact h_kernel.symm ▸ hx;
          · rw [ finrank_span_singleton ];
            · have := LinearMap.finrank_range_add_finrank_ker ( Matrix.mulVecLin M );
              simp_all +decide [ Matrix.rank ];
              linarith [ Nat.sub_add_cancel ( show 1 ≤ Fintype.card n from Fintype.card_pos_iff.mpr ⟨ Classical.choose ( Function.ne_iff.mp hv ) ⟩ ) ];
            · exact hv
        exact Submodule.mem_span_singleton.mp ( h_kernel ▸ LinearMap.mem_ker.mpr h_w_kernel ) |> fun ⟨ c, hc ⟩ => ⟨ c, hc.symm ⟩;
      simp_all +decide [ Matrix.vecMulVec, funext_iff ];
      exact h_contra c |> fun ⟨ x, y, hxy ⟩ => hxy <| by ring;

/-
If a matrix has rank k, there exists a k x k submatrix with non-zero determinant.
-/
lemma exists_submatrix_det_ne_zero_of_rank_eq {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) (k : ℕ) (h_rank : Matrix.rank A = k) :
    ∃ (r c : Fin k → n), (A.submatrix r c).det ≠ 0 := by
      by_contra! h_contra;
      -- Since the rank of A is k, there exist k linearly independent rows in A.
      obtain ⟨rows, hrows⟩ : ∃ rows : Fin k → n, LinearIndependent ℝ (fun i => A.row (rows i)) := by
        have := h_rank ▸ Matrix.rank_eq_finrank_span_row A;
        have := ( exists_linearIndependent ℝ ( Set.range A.row ) );
        obtain ⟨ b, hb₁, hb₂, hb₃ ⟩ := this;
        have h_card : Set.ncard b = k := by
          have h_card : Set.ncard b = Module.finrank ℝ (Submodule.span ℝ b) := by
            have h_card : Set.Finite b := by
              exact Set.Finite.subset ( Set.toFinite ( Set.range A.row ) ) hb₁;
            have := h_card.fintype;
            rw [ Set.ncard_eq_toFinset_card' ];
            rw [ finrank_span_set_eq_card ] ; aesop;
          rw [ h_card, hb₂, this ];
        -- Since $b$ is a subset of the range of $A.row$ with cardinality $k$, we can choose $k$ distinct elements from $b$.
        obtain ⟨rows, hrows⟩ : ∃ rows : Fin k → n → ℝ, (∀ i, rows i ∈ b) ∧ LinearIndependent ℝ rows := by
          have h_card : ∃ rows : Fin k → n → ℝ, (∀ i, rows i ∈ b) ∧ Function.Injective rows := by
            have h_card : Nonempty (Fin k ≃ b) := by
              have h_card : Fintype b := by
                exact Set.Finite.fintype ( Set.Finite.subset ( Set.toFinite ( Set.range A.row ) ) hb₁ );
              exact ⟨ Fintype.equivOfCardEq <| by simp +decide [ ← ‹Set.ncard b = k›, Set.ncard_eq_toFinset_card' ] ⟩;
            exact ⟨ _, fun i => h_card.some i |>.2, Subtype.coe_injective.comp h_card.some.injective ⟩;
          obtain ⟨ rows, hrows₁, hrows₂ ⟩ := h_card;
          refine' ⟨ rows, hrows₁, _ ⟩;
          convert hb₃.comp _ _;
          rotate_left;
          exacts [ fun i => ⟨ rows i, hrows₁ i ⟩, fun i j hij => hrows₂ <| by simpa using hij, funext fun i => rfl ];
        choose f hf using fun i => hb₁ ( hrows.1 i );
        exact ⟨ f, by simpa only [ hf ] using hrows.2 ⟩;
      -- Consider the k x k matrix B formed by these rows. B has rank k.
      set B : Matrix (Fin k) n ℝ := fun i j => A (rows i) j;
      -- Since B has rank k, there exist k linearly independent columns in B.
      obtain ⟨cols, hcols⟩ : ∃ cols : Fin k → n, LinearIndependent ℝ (fun i => B.col (cols i)) := by
        have hB_rank : Matrix.rank B = k := by
          have hB_rank : LinearMap.range (Matrix.mulVecLin B.transpose) = Submodule.span ℝ (Set.range (fun i => A.row (rows i))) := by
            ext; simp [B];
            simp +decide [ funext_iff, Matrix.vecMul, Submodule.mem_span_range_iff_exists_fun ];
            rfl;
          have hB_rank : Module.finrank ℝ (Submodule.span ℝ (Set.range (fun i => A.row (rows i)))) = k := by
            rw [ finrank_span_eq_card ] <;> aesop;
          convert hB_rank using 1;
          rw [ ← ‹LinearMap.range B.transpose.mulVecLin = Submodule.span ℝ ( Set.range fun i => A.row ( rows i ) ) ›, Matrix.rank ];
          rw [ ← Matrix.rank, ← Matrix.rank, Matrix.rank_transpose ];
        have hB_col_rank : Module.finrank ℝ (Submodule.span ℝ (Set.range (fun j => B.col j))) = k := by
          convert hB_rank using 1;
          exact?;
        have := ( exists_linearIndependent ℝ ( Set.range fun j => B.col j ) );
        obtain ⟨ b, hb₁, hb₂, hb₃ ⟩ := this;
        have h_card_b : Set.ncard b = k := by
          have h_card_b : Module.finrank ℝ (Submodule.span ℝ b) = k := by
            rw [ hb₂, hB_col_rank ];
          have h_card_b : Module.finrank ℝ (Submodule.span ℝ b) = Set.ncard b := by
            have h_finite : Set.Finite b := by
              exact Set.Finite.subset ( Set.toFinite ( Set.range fun j => B.col j ) ) hb₁
            have := h_finite.fintype;
            rw [ Set.ncard_eq_toFinset_card' ];
            rw [ finrank_span_set_eq_card ] ; aesop;
          linarith;
        obtain ⟨cols, hcols⟩ : ∃ cols : Fin k → n, b = Set.range (fun i => B.col (cols i)) := by
          have h_card_b : ∃ cols : Fin k → n, b = Set.range (fun i => B.col (cols i)) := by
            have h_card_b : ∃ cols : Fin k → (Fin k → ℝ), b = Set.range cols := by
              have h_card_b : Nonempty (Fin k ≃ b) := by
                have h_card_b : Fintype b := by
                  exact Set.Finite.fintype ( Set.Finite.subset ( Set.toFinite ( Set.range fun j => B.col j ) ) hb₁ );
                exact ⟨ Fintype.equivOfCardEq <| by simp +decide [ Set.ncard_eq_toFinset_card' ] at *; linarith ⟩;
              obtain ⟨ e ⟩ := h_card_b;
              use fun i => e i |>.1;
              ext x; simp [Set.mem_range];
              exact ⟨ fun hx => ⟨ e.symm ⟨ x, hx ⟩, by simp +decide ⟩, by rintro ⟨ y, rfl ⟩ ; exact e y |>.2 ⟩
            obtain ⟨ cols, hcols ⟩ := h_card_b;
            choose f hf using fun i => hb₁ ( hcols.symm ▸ Set.mem_range_self i );
            exact ⟨ f, by aesop ⟩;
          exact h_card_b;
        use cols;
        convert hb₃.comp _ _;
        rotate_left;
        use fun i => ⟨ B.col ( cols i ), hcols.symm ▸ Set.mem_range_self i ⟩;
        · intro i j hij;
          have := Finset.card_image_iff.mp ( show Finset.card ( Finset.image ( fun i => B.col ( cols i ) ) Finset.univ ) = Finset.card ( Finset.univ : Finset ( Fin k ) ) from ?_ ) ; aesop;
          rw [ ← Set.ncard_coe_finset ] ; aesop;
        · rfl;
      -- Consider the k x k matrix C formed by these columns of B. C is A.submatrix rows cols.
      set C : Matrix (Fin k) (Fin k) ℝ := fun i j => A (rows i) (cols j);
      -- Since C is a k x k matrix with rank k, its determinant is non-zero.
      have hC_det : C.det ≠ 0 := by
        rw [ Fintype.linearIndependent_iff ] at hcols;
        intro h_det_zero
        have h_lin_dep : ∃ g : Fin k → ℝ, g ≠ 0 ∧ ∑ i, g i • B.col (cols i) = 0 := by
          obtain ⟨ g, hg ⟩ := Matrix.exists_mulVec_eq_zero_iff.mpr h_det_zero;
          exact ⟨ g, hg.1, by ext i; simpa [ Matrix.mulVec, dotProduct, mul_comm ] using congr_fun hg.2 i ⟩;
        exact h_lin_dep.elim fun g hg => hg.1 ( funext fun i => hcols g hg.2 i );
      exact hC_det ( h_contra rows cols )

/-
If a n x n submatrix of a (n+1) x (n+1) matrix has non-zero determinant, then there exists a standard submatrix (obtained by deleting one row and one column) with non-zero determinant.
-/
lemma exists_submatrix_succAbove_det_ne_zero_of_det_ne_zero {n : ℕ} (A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ)
    (r c : Fin n → Fin (n + 1)) (h_det : (A.submatrix r c).det ≠ 0) :
    ∃ i j : Fin (n + 1), (A.submatrix i.succAbove j.succAbove).det ≠ 0 := by
      -- Since $r$ and $c$ are injective, their ranges omit exactly one element each.
      have hr_range : ∃ i : Fin (n + 1), ∀ j : Fin n, r j ≠ i := by
        by_contra! h_contra;
        exact absurd ( Fintype.card_le_of_surjective r fun x => by obtain ⟨ j, rfl ⟩ := h_contra x; exact ⟨ j, rfl ⟩ ) ( by simp +decide )
      have hc_range : ∃ j : Fin (n + 1), ∀ k : Fin n, c k ≠ j := by
        by_contra! h_contra;
        exact absurd ( Fintype.card_le_of_surjective c fun x => by obtain ⟨ k, rfl ⟩ := h_contra x; exact ⟨ k, rfl ⟩ ) ( by simp +decide );
      obtain ⟨ i, hi ⟩ := hr_range
      obtain ⟨ j, hj ⟩ := hc_range
      have h_submatrix : ∃ σ : Fin n ≃ { x : Fin (n + 1) // x ≠ i }, ∀ k : Fin n, r k = σ k := by
        have h_submatrix : Function.Injective r := by
          intro i j hij;
          exact Classical.not_not.1 fun hi => h_det <| Matrix.det_zero_of_row_eq hi <| by aesop;
        have h_submatrix : Finset.image r Finset.univ = Finset.univ.erase i := by
          exact Finset.eq_of_subset_of_card_le ( Finset.image_subset_iff.mpr fun x _ => Finset.mem_erase_of_ne_of_mem ( hi x ) ( Finset.mem_univ _ ) ) ( by rw [ Finset.card_image_of_injective _ h_submatrix ] ; simp +decide [ Finset.card_erase_of_mem ( Finset.mem_univ i ) ] );
        have h_submatrix : Finset.image (fun k : Fin n => ⟨r k, hi k⟩ : Fin n → { x : Fin (n + 1) // x ≠ i }) Finset.univ = Finset.univ := by
          simp_all +decide [ Finset.ext_iff ];
        have h_submatrix : Function.Bijective (fun k : Fin n => ⟨r k, hi k⟩ : Fin n → { x : Fin (n + 1) // x ≠ i }) := by
          exact ⟨ fun x y hxy => by simpa [ Fin.ext_iff ] using ‹Function.Injective r› ( by simpa [ Fin.ext_iff ] using congr_arg Subtype.val hxy ), fun x => by replace h_submatrix := Finset.ext_iff.mp h_submatrix x; aesop ⟩;
        exact ⟨ Equiv.ofBijective _ h_submatrix, fun k => rfl ⟩
      have h_submatrix' : ∃ τ : Fin n ≃ { x : Fin (n + 1) // x ≠ j }, ∀ k : Fin n, c k = τ k := by
        have h_submatrix' : Function.Injective c := by
          intro k l hkl; have := Matrix.det_ne_zero_of_left_inverse ( show ( A.submatrix r c ) * ( ( A.submatrix r c ) ⁻¹ ) = 1 from ?_ ) ; simp_all +decide [ Matrix.det_eq_zero_of_row_eq_zero ] ;
          · contrapose! h_det;
            exact Matrix.det_zero_of_column_eq h_det ( by aesop );
          · exact Matrix.mul_nonsing_inv _ ( show IsUnit _ from isUnit_iff_ne_zero.mpr h_det );
        exact ⟨ Equiv.ofBijective ( fun k => ⟨ c k, hj k ⟩ ) ⟨ fun a b h => h_submatrix' <| by simpa using h, fun a => by
          have := Finset.eq_of_subset_of_card_le ( show Finset.image c Finset.univ ⊆ Finset.univ.erase j from Finset.image_subset_iff.mpr fun k _ => Finset.mem_erase_of_ne_of_mem ( hj k ) ( Finset.mem_univ _ ) ) ; simp_all +decide [ Finset.card_image_of_injective _ h_submatrix' ] ;
          replace this := Finset.ext_iff.mp this a; aesop; ⟩, fun k => rfl ⟩
      obtain ⟨ σ, hσ ⟩ := h_submatrix
      obtain ⟨ τ, hτ ⟩ := h_submatrix';
      -- The submatrix $A.submatrix r c$ is equivalent to $A.submatrix i.succAbove j.succAbove$ up to permutation of rows and columns.
      have h_submatrix_eq : ∃ P Q : Matrix (Fin n) (Fin n) ℝ, P.det ≠ 0 ∧ Q.det ≠ 0 ∧ A.submatrix r c = P * A.submatrix i.succAbove j.succAbove * Q := by
        use Matrix.of (fun k l => if σ k = Fin.succAbove i l then 1 else 0), Matrix.of (fun k l => if τ l = Fin.succAbove j k then 1 else 0);
        refine' ⟨ _, _, _ ⟩;
        · -- Since σ is a permutation, the matrix P is a permutation matrix, and its determinant is ±1.
          have hP_perm : ∃ σ' : Equiv.Perm (Fin n), ∀ k l, (if σ k = Fin.succAbove i l then 1 else 0 : ℝ) = if σ' k = l then 1 else 0 := by
            have hP_perm : ∀ k : Fin n, ∃ l : Fin n, σ k = Fin.succAbove i l := by
              intro k; have := σ k |>.2; simp_all +decide [ Fin.succAbove ] ;
              use ⟨ if ( σ k : Fin ( n + 1 ) ) < i then ( σ k : Fin ( n + 1 ) ) |> Fin.val else ( σ k : Fin ( n + 1 ) ) |> Fin.val - 1, by
                split_ifs <;> simp_all +decide [ Fin.val_add, Fin.coe_sub_one ];
                · exact lt_of_lt_of_le ‹_› ( Nat.le_of_lt_succ ( Fin.is_lt i ) );
                · exact Nat.lt_of_lt_of_le ( Nat.pred_lt ( ne_bot_of_gt ( Fin.pos_iff_ne_zero.mpr ( by specialize hi k; aesop ) ) ) ) ( Nat.le_of_lt_succ ( Fin.is_lt _ ) ) ⟩
              generalize_proofs at *;
              split_ifs <;> simp_all +decide [ Fin.ext_iff, Fin.val_add, Fin.val_one ];
              grind;
            choose f hf using hP_perm;
            have hP_perm : Function.Injective f := by
              intro k l hkl; have := σ.injective ( show σ k = σ l from Subtype.ext <| by aesop ) ; aesop;
            exact ⟨ Equiv.ofBijective f ⟨ hP_perm, Finite.injective_iff_surjective.mp hP_perm ⟩, fun k l => by aesop ⟩;
          obtain ⟨ σ', hσ' ⟩ := hP_perm; simp_all +decide [ Matrix.det_apply' ] ;
          rw [ Finset.sum_eq_single ( σ'⁻¹ ) ] <;> simp_all +decide [ Equiv.Perm.sign_inv ];
          intro b hb; rw [ Finset.prod_eq_zero_iff ] ; simp_all +decide [ Equiv.Perm.ext_iff ] ;
          exact hb.imp fun x hx => by contrapose! hx; simpa using σ'.injective ( by aesop ) ;
        · -- Since τ is a bijection, the matrix Q is a permutation matrix.
          have hQ_perm : ∃ P : Equiv.Perm (Fin n), ∀ k l, (Matrix.of (fun k l => if ↑(τ l) = j.succAbove k then 1 else 0)) k l = if P l = k then 1 else 0 := by
            have hQ_perm : ∀ l : Fin n, ∃ k : Fin n, τ l = j.succAbove k := by
              intro l; exact (by
              have := Fin.exists_succAbove_eq ( show ( τ l : Fin ( n + 1 ) ) ≠ j from τ l |>.2 ) ; tauto;);
            choose P hP using hQ_perm;
            use Equiv.ofBijective P (by
            have hP_inj : Function.Injective P := by
              intro l l' h; have := τ.injective ( Subtype.ext <| by aesop : τ l = τ l' ) ; aesop;
            generalize_proofs at *;
            exact ⟨ hP_inj, Finite.injective_iff_surjective.mp hP_inj ⟩)
            generalize_proofs at *;
            simp +decide [ hP ];
          obtain ⟨ P, hP ⟩ := hQ_perm; simp_all +decide [ Matrix.det_apply' ] ;
          simp_all +decide [ Finset.prod_ite ];
          rw [ Finset.sum_eq_single ( P ) ] <;> simp_all +decide [ Finset.ext_iff ];
          · intro k; specialize hP ( P k ) k; aesop;
          · grind;
        · ext k l; simp +decide [ Matrix.mul_apply, hσ, hτ ] ;
          rw [ Finset.sum_eq_single ( Classical.choose ( Fin.exists_succAbove_eq ( show ( τ l : Fin ( n + 1 ) ) ≠ j from by aesop ) ) ) ] <;> simp +decide [ Classical.choose_spec ( Fin.exists_succAbove_eq ( show ( τ l : Fin ( n + 1 ) ) ≠ j from by aesop ) ) ];
          · rw [ Finset.sum_eq_single ( Classical.choose ( Fin.exists_succAbove_eq ( show ( σ k : Fin ( n + 1 ) ) ≠ i from by aesop ) ) ) ] <;> simp +decide [ Classical.choose_spec ( Fin.exists_succAbove_eq ( show ( σ k : Fin ( n + 1 ) ) ≠ i from by aesop ) ) ];
            intro b hb h; have := Classical.choose_spec ( Fin.exists_succAbove_eq ( show ( σ k : Fin ( n + 1 ) ) ≠ i from by aesop ) ) ; aesop;
          · intro b hb h; have := Classical.choose_spec ( Fin.exists_succAbove_eq ( show ( τ l : Fin ( n + 1 ) ) ≠ j from by aesop ) ) ; aesop;
      obtain ⟨ P, Q, hP, hQ, h ⟩ := h_submatrix_eq; use i, j; simp_all +decide [ Matrix.det_mul ] ;

/-
If a standard submatrix (obtained by deleting row i and column j) has non-zero determinant, then the adjugate is non-zero.
-/
lemma adjugate_ne_zero_of_exists_submatrix_succAbove_det_ne_zero {n : ℕ} (A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ)
    (i j : Fin (n + 1)) (h : (A.submatrix i.succAbove j.succAbove).det ≠ 0) :
    Matrix.adjugate A ≠ 0 := by
      intro h_zero;
      have h_adj_zero : A.adjugate j i = (-1) ^ (i.val + j.val) * (A.submatrix i.succAbove j.succAbove).det := by
        rw [ Matrix.adjugate_apply, Matrix.det_succ_row _ i ];
        rw [ Finset.sum_eq_single j ] <;> aesop;
      replace h_zero := congr_fun ( congr_fun h_zero j ) i; aesop;

/-
If a matrix over Fin n (n > 0) has rank n-1, its adjugate is not zero.
-/
lemma adjugate_ne_zero_of_rank_eq_card_sub_one_fin {n : ℕ} (hn : n ≠ 0) (A : Matrix (Fin n) (Fin n) ℝ)
    (h_rank : Matrix.rank A = n - 1) :
    Matrix.adjugate A ≠ 0 := by
      rcases n with ( _ | n ) <;> simp_all +decide [ Matrix.adjugate_apply ];
      obtain ⟨ r, c, h ⟩ := exists_submatrix_det_ne_zero_of_rank_eq A n h_rank;
      exact fun h' => by have := adjugate_ne_zero_of_exists_submatrix_succAbove_det_ne_zero A _ _ ( exists_submatrix_succAbove_det_ne_zero_of_det_ne_zero A r c h |> Classical.choose_spec |> Classical.choose_spec ) ; aesop;

/-
If a matrix has rank n-1, its adjugate is not zero.
-/
lemma adjugate_ne_zero_of_rank_eq_card_sub_one {n : Type*} [Fintype n] [DecidableEq n] [Nonempty n] (A : Matrix n n ℝ)
    (h_rank : Matrix.rank A = Fintype.card n - 1) :
    Matrix.adjugate A ≠ 0 := by
      obtain ⟨e, he⟩ : ∃ e : n ≃ Fin (Fintype.card n), True := by
        exact ⟨ Fintype.equivFin n, trivial ⟩;
      have h_reindex : Matrix.rank (Matrix.reindex e e A) = Matrix.rank A := by
        exact?;
      have h_adj_ne_zero : Matrix.adjugate (Matrix.reindex e e A) ≠ 0 := by
        apply adjugate_ne_zero_of_rank_eq_card_sub_one_fin;
        · exact Fintype.card_ne_zero;
        · exact h_reindex.trans h_rank;
      contrapose! h_adj_ne_zero;
      rw [ Matrix.adjugate_reindex ] ; aesop

/-
The adjugate of (rI - A) is a non-zero scalar multiple of the outer product of the Perron vector and the left Perron vector.
-/
lemma adjugate_perron_root_eq_smul_vecMulVec {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    ∃ c : ℝ, c ≠ 0 ∧ Matrix.adjugate (perronRoot A hA • 1 - A) = c • Matrix.vecMulVec (perronVector A hA) (leftPerronVector A hA) := by
      obtain ⟨c, hc⟩ : ∃ c : ℝ, Matrix.adjugate (perronRoot A hA • 1 - A) = c • Matrix.vecMulVec (perronVector A hA) (leftPerronVector A hA) := by
        apply adjugate_eq_smul_vecMulVec_of_rank_eq_card_sub_one;
        · exact fun h => by have := leftPerronVector_pos A hA; simp_all +decide [ funext_iff, Matrix.IsPositiveVec ] ;
        · exact ne_of_apply_ne ( fun v => v ( Classical.arbitrary n ) ) ( ne_of_gt ( perronVector_pos A hA _ ) );
        · convert rank_eq_card_sub_one_of_geometric_multiplicity_one A ( perronRoot A hA ) ( geometric_multiplicity_one A hA ) using 1;
        · have := perronVector_is_eigenvector A hA; simp_all +decide [ Matrix.sub_mulVec, Matrix.smul_eq_diagonal_mul ] ;
        · have := leftPerronVector_is_eigenvector A hA;
          simp_all +decide [ ← Matrix.mulVec_transpose, Matrix.vecMul_sub, Matrix.vecMul_smul ];
          simp_all +decide [ Matrix.sub_mulVec, Matrix.smul_eq_diagonal_mul ];
      have h_adj_ne_zero : Matrix.adjugate (perronRoot A hA • 1 - A) ≠ 0 := by
        apply adjugate_ne_zero_of_rank_eq_card_sub_one;
        apply rank_eq_card_sub_one_of_geometric_multiplicity_one;
        exact?;
      aesop

/-
The trace of the adjugate of (rI - A) is non-zero.
-/
lemma trace_adjugate_perron_root_ne_zero {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    Matrix.trace (Matrix.adjugate (perronRoot A hA • 1 - A)) ≠ 0 := by
      -- By `adjugate_perron_root_eq_smul_vecMulVec`, the adjugate is `c * (v u^T)` for some `c \ne 0`.
      obtain ⟨c, hc_ne_zero, hc⟩ : ∃ c : ℝ, c ≠ 0 ∧ Matrix.adjugate (perronRoot A hA • 1 - A) = c • Matrix.vecMulVec (perronVector A hA) (leftPerronVector A hA) := by
        exact?;
      -- The trace is `c * trace(v u^T)`.
      have h_trace : Matrix.trace (Matrix.adjugate (perronRoot A hA • 1 - A)) = c * ∑ i, (perronVector A hA) i * (leftPerronVector A hA) i := by
        simp +decide [ hc, Matrix.trace, Matrix.vecMulVec ];
        rw [ Finset.mul_sum _ _ _ ];
      -- Since `v` and `u` are strictly positive vectors, their dot product is strictly positive.
      have h_dot_pos : 0 < ∑ i, (perronVector A hA) i * (leftPerronVector A hA) i := by
        exact Finset.sum_pos ( fun i _ => mul_pos ( perronVector_pos A hA i ) ( leftPerronVector_pos A hA i ) ) Finset.univ_nonempty;
      exact h_trace.symm ▸ mul_ne_zero hc_ne_zero h_dot_pos.ne'

#check charpoly_derivative_eval_eq_trace_adjugate

/-
The derivative of the characteristic polynomial evaluated at the Perron root is non-zero.
-/
lemma charpoly_derivative_eval_perronRoot_ne_zero {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    (Matrix.charpoly A).derivative.eval (perronRoot A hA) ≠ 0 := by
      rw [ charpoly_derivative_eval_eq_trace_adjugate ] ; exact trace_adjugate_perron_root_ne_zero A hA;

/-
The algebraic multiplicity of the Perron root is 1.
-/
lemma algebraic_multiplicity_one {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    (Matrix.charpoly A).rootMultiplicity (perronRoot A hA) = 1 := by
      -- By definition of $perronRoot$, we know that $perronRoot$ is a root of the characteristic polynomial of $A$.
      have h_root : Polynomial.IsRoot (Matrix.charpoly A) (perronRoot A hA) := by
        have h_cauchy_interlace : Matrix.det (perronRoot A hA • 1 - A) = 0 := by
          have h_det_zero : ∃ v : n → ℝ, v ≠ 0 ∧ (perronRoot A hA • 1 - A).mulVec v = 0 := by
            have h_eigenvalue : ∃ v : n → ℝ, v ≠ 0 ∧ A.mulVec v = (perronRoot A hA) • v := by
              exact ⟨ perronVector A hA, fun h => by simpa [ h ] using perronVector_mem_stdSimplex A hA |>.2, perronVector_is_eigenvector A hA ⟩;
            obtain ⟨ v, hv_ne_zero, hv_eigenvalue ⟩ := h_eigenvalue; use v; simp_all +decide [ sub_smul, Matrix.sub_mulVec ] ;
            simp +decide [ Matrix.smul_eq_diagonal_mul ];
          exact Matrix.exists_mulVec_eq_zero_iff.mp h_det_zero;
        simp_all +decide [ Matrix.charpoly, Matrix.det_apply' ];
        simp_all +decide [ Polynomial.eval_finset_sum, Polynomial.eval_mul, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_one, Matrix.charmatrix, Matrix.one_apply ];
        convert h_cauchy_interlace using 4 ; aesop;
      have h_deriv_ne_zero : (Matrix.charpoly A).derivative.eval (perronRoot A hA) ≠ 0 := by
        exact?;
      exact le_antisymm ( Nat.le_of_not_lt fun h => h_deriv_ne_zero <| by simpa [ h_root ] using Polynomial.isRoot_iterate_derivative_of_lt_rootMultiplicity h ) ( Nat.one_le_iff_ne_zero.mpr <| by aesop )

/-
The Perron-Frobenius theorem for positive matrices:
1. There exists a positive real eigenvalue (Perron root) with a positive eigenvector (Perron vector).
2. The algebraic multiplicity of the Perron root is 1.
3. The Perron root is strictly greater than the magnitude of any other eigenvalue.
4. The only eigenvalue with magnitude equal to the Perron root is the Perron root itself.
-/
theorem perron_frobenius_positive {n : Type*} [Fintype n] [Nonempty n] [DecidableEq n] (A : Matrix n n ℝ) (hA : A.IsPositive) :
    (0 < perronRoot A hA) ∧
    (Matrix.IsPositiveVec (perronVector A hA)) ∧
    (A.mulVec (perronVector A hA) = (perronRoot A hA) • (perronVector A hA)) ∧
    ((Matrix.charpoly A).rootMultiplicity (perronRoot A hA) = 1) ∧
    (∀ μ : ℂ, ∀ w : n → ℂ, w ≠ 0 → (A.map Complex.ofReal).mulVec w = μ • w → ‖μ‖ ≤ perronRoot A hA) ∧
    (∀ μ : ℂ, ∀ w : n → ℂ, w ≠ 0 → (A.map Complex.ofReal).mulVec w = μ • w → ‖μ‖ = perronRoot A hA → μ = perronRoot A hA) := by
      refine' ⟨ perronRoot_pos A hA, perronVector_pos A hA, perronVector_is_eigenvector A hA, algebraic_multiplicity_one A hA, _, _ ⟩;
      · exact?;
      · exact?
