/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d2aff0bc-973e-482f-9986-cfb95c172e8c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module proves that PSL(2, p) is a simple group for any prime p ≥ 5.
The proof relies on Iwasawa's Lemma (`MulAction.IwasawaStructure.isSimpleGroup`).
We construct an Iwasawa structure for the action of PSL(2, p) on the projective line `Projectivization (ZMod p) (Fin 2 → ZMod p)`.
The subgroups `T(x)` in the Iwasawa structure are defined as conjugates of the subgroup `A_inf` (image of upper unitriangular matrices).
We prove that `T(x)` is abelian, the family `T` is closed under conjugation, and the subgroups `T(x)` generate PSL(2, p).
Combined with the facts that PSL(2, p) is perfect, the action is faithful and primitive, this establishes the simplicity of PSL(2, p).
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 03d13e69-4257-4851-8b81-144a5c307062

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7df7d826-7cf3-4804-9225-30d201aca997

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def check_PSL_group (p : ℕ) [Fact p.Prime] : Group (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) := by infer_instance

/-
The linear map corresponding to a matrix in SL(2, p) is injective.
-/
lemma SL2_toLin'_injective (p : ℕ) [Fact p.Prime] (A : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :
  Function.Injective (Matrix.toLin' (A : Matrix (Fin 2) (Fin 2) (ZMod p))) := by
    intro x y hxy;
    apply_fun fun z => ( A : Matrix ( Fin 2 ) ( Fin 2 ) ( ZMod p ) ) ⁻¹.mulVec z at hxy ; simp_all +decide [ Matrix.nonsing_inv_apply_not_isUnit, isUnit_iff_ne_zero ]

/-
Projectivization.map is congruent with respect to the linear map argument.
-/
universe u v w z

lemma Projectivization.map_congr {K : Type u} {V : Type v} [DivisionRing K] [AddCommGroup V] [Module K V] {L : Type w} {W : Type z} [DivisionRing L] [AddCommGroup W] [Module L W] {σ : K →+* L} {f g : V →ₛₗ[σ] W} (hf : Function.Injective f) (hg : Function.Injective g) (h : f = g) : Projectivization.map f hf = Projectivization.map g hg := by
  subst h
  rfl

/-
Define the map representing the action of an element of SL(2, p) on the projective line.
-/
def SL2_action_map (p : ℕ) [Fact p.Prime] (g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :
  Projectivization (ZMod p) (Fin 2 → ZMod p) → Projectivization (ZMod p) (Fin 2 → ZMod p) :=
  Projectivization.map (Matrix.toLin' (g : Matrix (Fin 2) (Fin 2) (ZMod p))) (SL2_toLin'_injective p g)

/-
The action of the identity matrix is the identity map.
-/
lemma SL2_action_map_one (p : ℕ) [Fact p.Prime] (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  SL2_action_map p 1 x = x := by
    unfold SL2_action_map;
    induction x using Quotient.inductionOn' ; aesop

/-
The action of SL(2, p) on the projective line respects multiplication.
-/
lemma SL2_action_map_mul (p : ℕ) [Fact p.Prime] (g h : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  SL2_action_map p (g * h) x = SL2_action_map p g (SL2_action_map p h x) := by
    -- By definition of SL2_action_map, we have that it is a projectivization map.
    unfold SL2_action_map;
    induction x using Quotient.inductionOn' ; aesop

/-
Define the action of SL(2, p) on the projective line.
-/
instance SL2_mulAction (p : ℕ) [Fact p.Prime] : MulAction (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) where
  smul g x := SL2_action_map p g x
  one_smul := SL2_action_map_one p
  mul_smul := SL2_action_map_mul p

/-
The center of SL(2, p) acts trivially on the projective line.
-/
lemma SL2_center_acts_trivially (p : ℕ) [Fact p.Prime] (g : Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  g • x = x := by
  obtain ⟨g, hg⟩ := g
  rw [Subgroup.mem_center_iff] at hg
  -- The center of SL(2, p) is {I, -I}
  -- But we don't strictly need to know the elements, just that they are scalar matrices.
  -- Actually, for SL(n), the center consists of scalar matrices cI where c^n = 1.
  -- For n=2, c^2 = 1.
  -- A scalar matrix cI acts as multiplication by c on vectors.
  -- Projectivization identifies v and c*v.
  -- So scalar matrices act trivially.
  -- We need to show g is a scalar matrix.
  -- Mathlib should have a theorem about the center of SL(n).
  -- Since $g$ commutes with all elements of $SL(2, p)$, it must be a scalar matrix.
  have h_scalar : ∃ c : ZMod p, g = Matrix.diagonal ![c, c] := by
    simp_all +decide [ Matrix.SpecialLinearGroup.ext_iff, Matrix.mul_apply ];
    have := hg ⟨ Matrix.of ![![1, 1], ![0, 1]], by simp +decide [ Matrix.det_fin_two ] ⟩ ; have := hg ⟨ Matrix.of ![![1, 0], ![1, 1]], by simp +decide [ Matrix.det_fin_two ] ⟩ ; simp_all +decide [ ← Matrix.ext_iff, Fin.forall_fin_two ] ;
  rcases h_scalar with ⟨ c, hc ⟩ ; simp_all +decide [ Matrix.SpecialLinearGroup.ext_iff ] ; (
  -- Since $c$ is a unit in $ZMod p$, multiplication by $c$ is an invertible operation on the projective line.
  have h_unit : IsUnit c := by
    have := g.2; aesop;
  generalize_proofs at *; (
  rcases x with ⟨ x, hx ⟩ ; rcases h_unit with ⟨ u, rfl ⟩ ; simp_all +decide [ Matrix.SpecialLinearGroup.ext_iff ] ; (
  erw [ Quotient.eq ] ; simp_all +decide [ Projectivization.map ] ; (
  refine' ⟨ u, _ ⟩ ; ext i ; fin_cases i <;> simp +decide [ Matrix.mulVec ] ; ring!;
  · exact?;
  · exact?))));

/-
Define the action of PSL(2, p) on the projective line.
-/
def PSL2_action_map (p : ℕ) [Fact p.Prime] :
  Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p) → Projectivization (ZMod p) (Fin 2 → ZMod p) → Projectivization (ZMod p) (Fin 2 → ZMod p) :=
  Quotient.lift (SL2_action_map p) (by
    intro g1 g2 h
    have h_rel : g1⁻¹ * g2 ∈ Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
      change (QuotientGroup.leftRel (Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)))).r g1 g2 at h
      rw [QuotientGroup.leftRel_apply] at h
      exact h
    let z := g1⁻¹ * g2
    have h_eq : g2 = g1 * z := by
      simp [z]
    funext x
    rw [h_eq, SL2_action_map_mul]
    have h_z_act : SL2_action_map p z x = x := SL2_center_acts_trivially p ⟨z, h_rel⟩ x
    rw [h_z_act]
  )

/-
The action of PSL(2, p) on the projective line respects multiplication.
-/
lemma PSL2_mul_smul (p : ℕ) [Fact p.Prime] (g h : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  PSL2_action_map p (g * h) x = PSL2_action_map p g (PSL2_action_map p h x) := by
    obtain ⟨ g, rfl ⟩ := QuotientGroup.mk_surjective g; obtain ⟨ h, rfl ⟩ := QuotientGroup.mk_surjective h;
    convert SL2_action_map_mul p g h x using 1

/-
The identity element of PSL(2, p) acts as the identity map on the projective line.
-/
lemma PSL2_one_smul (p : ℕ) [Fact p.Prime] (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  PSL2_action_map p 1 x = x := by
  have h1 : (1 : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) = QuotientGroup.mk 1 := rfl
  rw [h1]
  -- PSL2_action_map is defined as Quotient.lift ...
  -- So PSL2_action_map p (QuotientGroup.mk 1) = SL2_action_map p 1
  rw [PSL2_action_map, Quotient.lift_mk]
  apply SL2_action_map_one

/-
Define the action of PSL(2, p) on the projective line.
-/
instance PSL2_mulAction (p : ℕ) [Fact p.Prime] : MulAction (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) where
  smul := PSL2_action_map p
  one_smul := PSL2_one_smul p
  mul_smul := PSL2_mul_smul p

def check_PSL2_smul (p : ℕ) [Fact p.Prime] : SMul (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) := by infer_instance

/-
If an element of SL(2, p) acts trivially on the projective line, it is in the center.
-/
lemma SL2_act_trivial_implies_center (p : ℕ) [Fact p.Prime] (g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) (h : ∀ x : Projectivization (ZMod p) (Fin 2 → ZMod p), SL2_action_map p g x = x) :
  g ∈ Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
  -- If g acts trivially on the projective line, then g v is a scalar multiple of v for all v.
  -- This implies g is a scalar matrix.
  -- Since det(g) = 1, g must be c • I where c^2 = 1.
  -- Such matrices are exactly the center of SL(2, p).
  have h_center : ∀ x : Projectivization (ZMod p) (Fin 2 → ZMod p), Projectivization.map (Matrix.toLin' (g : Matrix (Fin 2) (Fin 2) (ZMod p))) (SL2_toLin'_injective p g) x = x := by
    exact h;
  -- If g acts trivially on the projective line, then for any vector v, g(v) is a scalar multiple of v. This implies that g commutes with any matrix in SL(2, p), hence g is in the center.
  have h_scalar : ∀ v : Fin 2 → ZMod p, v ≠ 0 → ∃ c : ZMod p, g.val.mulVec v = c • v := by
    intro v hv_nonzero
    specialize h_center (Projectivization.mk (ZMod p) v hv_nonzero);
    rw [ Projectivization.map_mk, Projectivization.mk_eq_mk_iff ] at h_center;
    exact ⟨ h_center.choose.val, by simpa [ mul_comm ] using h_center.choose_spec.symm ⟩;
  -- Since g is a scalar matrix, we can write g = cI for some scalar c.
  obtain ⟨c, hc⟩ : ∃ c : ZMod p, g.val = c • 1 := by
    obtain ⟨c₁, hc₁⟩ := h_scalar (Pi.single 0 1) (by
    exact ne_of_apply_ne ( fun x => x 0 ) one_ne_zero)
    obtain ⟨c₂, hc₂⟩ := h_scalar (Pi.single 1 1) (by
    exact ne_of_apply_ne ( fun x => x 1 ) one_ne_zero);
    simp_all +decide [ funext_iff, Fin.forall_fin_two, Matrix.mulVec, dotProduct ];
    obtain ⟨ c, hc ⟩ := h_scalar ( fun i => if i = 0 then 1 else 1 ) ( by simp +decide ) ; use c ; ext i j ; fin_cases i <;> fin_cases j <;> aesop;
  rw [ Subgroup.mem_center_iff ] ; aesop

/-
The action of PSL(2, p) on the projective line is faithful.
-/
lemma PSL2_faithful_action (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  FaithfulSMul (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) := by
    constructor;
    intro m₁ m₂ h_eq
    obtain ⟨g₁, hg₁⟩ : ∃ g₁ : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), m₁ = Quotient.mk'' g₁ := by
      exact Quotient.exists_rep m₁ |> fun ⟨ g₁, hg₁ ⟩ => ⟨ g₁, hg₁.symm ⟩
    obtain ⟨g₂, hg₂⟩ : ∃ g₂ : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), m₂ = Quotient.mk'' g₂ := by
      obtain ⟨ g₂, rfl ⟩ := Quotient.exists_rep m₂; exact ⟨ g₂, rfl ⟩ ;
    have h_center : g₁⁻¹ * g₂ ∈ Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
      have h_center : ∀ x : Projectivization (ZMod p) (Fin 2 → ZMod p), SL2_action_map p (g₁⁻¹ * g₂) x = x := by
        intro x
        have h_eq' : SL2_action_map p g₁ x = SL2_action_map p g₂ x := by
          aesop;
        have h_eq'' : SL2_action_map p g₁⁻¹ (SL2_action_map p g₁ x) = x := by
          rw [ ← SL2_action_map_mul p ] ; simp +decide [ hg₁ ] ;
          exact?;
        convert h_eq'' using 1;
        rw [h_eq'];
        exact?;
      exact?;
    rw [ hg₁, hg₂, QuotientGroup.eq ];
    exact h_center

def check_PSL2_SMul (p : ℕ) [Fact p.Prime] : SMul (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) := by infer_instance

/-
For any two distinct points in the projective line, there exist representatives with determinant 1.
-/
lemma exists_rep_det_one (p : ℕ) [Fact p.Prime] (P1 P2 : Projectivization (ZMod p) (Fin 2 → ZMod p)) (h : P1 ≠ P2) :
  ∃ (v1 v2 : Fin 2 → ZMod p) (h1 : v1 ≠ 0) (h2 : v2 ≠ 0),
    Projectivization.mk (ZMod p) v1 h1 = P1 ∧
    Projectivization.mk (ZMod p) v2 h2 = P2 ∧
    Matrix.det (Matrix.of ![![v1 0, v2 0], ![v1 1, v2 1]]) = 1 := by
      rcases P1 with ⟨v1, hv1⟩; rcases P2 with ⟨v2, hv2⟩; simp_all +decide [ Projectivization.mk_eq_mk_iff ] ;
      -- Since $v1$ and $v2$ are linearly independent, we can scale $v2$ by a scalar $c$ such that the determinant of the matrix formed by $v1$ and $c*v2$ is 1.
      obtain ⟨c, hc⟩ : ∃ c : ZMod p, c * (v1 0 * v2 1 - v2 0 * v1 1) = 1 := by
        have h_det_nonzero : v1 0 * v2 1 - v2 0 * v1 1 ≠ 0 := by
          contrapose! h;
          -- Since $v1$ and $v2$ are linearly dependent, there exists a scalar $c$ such that $v1 = c • v2$.
          obtain ⟨c, hc⟩ : ∃ c : ZMod p, v1 = c • v2 := by
            by_cases hv20 : v2 0 = 0 <;> by_cases hv21 : v2 1 = 0 <;> simp_all +decide [ funext_iff, Fin.forall_fin_two ];
            · exact ⟨ v1 1 / v2 1, by rw [ div_mul_cancel₀ _ hv21 ] ⟩;
            · exact ⟨ v1 0 / v2 0, by rw [ div_mul_cancel₀ _ hv20 ] ⟩;
            · use v1 1 / v2 1;
              grind;
          exact Quotient.sound ⟨ Units.mk0 c ( by aesop ), by aesop ⟩;
        exact ⟨ _, inv_mul_cancel₀ h_det_nonzero ⟩;
      refine' ⟨ v1, _, c • v2, _, _ ⟩ <;> simp_all +decide [ funext_iff, Fin.forall_fin_two ];
      · rfl;
      · refine' ⟨ _, _ ⟩;
        exact fun h => by simp +decide [ h ] at hc;
        exact Quotient.sound ⟨ Units.mk0 c ( by aesop_cat ), by aesop_cat ⟩;
      · linear_combination' hc

/-
SL(2, p) acts 2-transitively on the projective line.
-/
lemma SL2_exists_g_of_pairs (p : ℕ) [Fact p.Prime] (x1 x2 y1 y2 : Projectivization (ZMod p) (Fin 2 → ZMod p)) (hx : x1 ≠ x2) (hy : y1 ≠ y2) :
  ∃ g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), SL2_action_map p g x1 = y1 ∧ SL2_action_map p g x2 = y2 := by
  obtain ⟨vx1, vx2, hvx1, hvx2, hx1_eq, hx2_eq, h_det_x⟩ := exists_rep_det_one p x1 x2 hx
  obtain ⟨vy1, vy2, hvy1, hvy2, hy1_eq, hy2_eq, h_det_y⟩ := exists_rep_det_one p y1 y2 hy
  let Mx := Matrix.of ![![vx1 0, vx2 0], ![vx1 1, vx2 1]]
  let My := Matrix.of ![![vy1 0, vy2 0], ![vy1 1, vy2 1]]
  have h_det_Mx : Mx.det = 1 := h_det_x
  have h_det_My : My.det = 1 := h_det_y
  let g_x : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) := ⟨Mx, h_det_Mx⟩
  let g_y : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) := ⟨My, h_det_My⟩
  let g := g_y * g_x⁻¹
  use g
  constructor
  · -- g • x1 = y1
    -- g • x1 = g_y • (g_x⁻¹ • x1)
    -- We need to show g_x • e1 = x1 (or something similar)
    -- Actually, g_x maps basis vectors to vx1, vx2.
    -- Let e1 = ![1, 0], e2 = ![0, 1].
    -- g_x.val.mulVec e1 = vx1
    -- g_x.val.mulVec e2 = vx2
    -- So g_x • [e1] = [vx1] = x1
    -- g_x • [e2] = [vx2] = x2
    -- Similarly for g_y.
    -- Then g • x1 = g_y • g_x⁻¹ • x1 = g_y • [e1] = y1
    rw [ ← hx1_eq, ← hy1_eq ];
    unfold SL2_action_map;
    erw [ Projectivization.map_mk ];
    rw [ Projectivization.mk_eq_mk_iff ];
    simp +zetaDelta at *;
    use 1; ext i; fin_cases i <;> norm_num [ Matrix.vecHead, Matrix.vecTail ] <;> ring;
    · linear_combination' -h_det_x * vy1 0;
    · linear_combination -h_det_x * vy1 1
  · -- g • x2 = y2
    convert hy2_eq using 1;
    rw [ ← hx2_eq ];
    unfold SL2_action_map;
    erw [ Projectivization.map_mk ];
    rw [ Projectivization.mk_eq_mk_iff ];
    refine' ⟨ 1, _ ⟩ ; ext i ; fin_cases i <;> norm_num [ Matrix.mulVec ];
    · simp +zetaDelta at *;
      linear_combination -h_det_x * vy2 0;
    · simp +zetaDelta at *;
      linear_combination -h_det_x * vy2 1

/-
The action of PSL(2, p) on the projective line is 2-transitive.
-/
lemma PSL2_two_transitive (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  MulAction.IsMultiplyPretransitive (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) 2 := by
    refine' ⟨ _ ⟩;
    intro x y
    obtain ⟨g, hg⟩ : ∃ g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), ∀ i : Fin 2, SL2_action_map p g (x i) = y i := by
      convert SL2_exists_g_of_pairs p ( x 0 ) ( x 1 ) ( y 0 ) ( y 1 ) ?_ ?_ using 1 <;> simp +decide [ Fin.forall_fin_two ];
    use Quotient.mk'' g; ext i; exact (by
    convert hg i using 1);

/-
For p >= 5, there exists a unit u such that u^2 != 1.
-/
lemma exists_unit_sq_ne_one (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  ∃ u : (ZMod p)ˣ, u ^ 2 ≠ 1 := by
  have h_card_fin : Fintype.card (ZMod p)ˣ = p - 1 := ZMod.card_units p
  have h_card_nat : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_eq_fintype_card, h_card_fin]
  have h_sols : ({x : (ZMod p)ˣ | x ^ 2 = 1}).ncard ≤ 2 := by
    -- x^2 - 1 = 0 has at most 2 roots in a field
    -- The set of solutions to $x^2 = 1$ in a field is exactly $\{1, -1\}$.
    have h_solutions : {x : (ZMod p)ˣ | x^2 = 1} ⊆ {1, -1} := by
      intro x hx
      have h_eq : (x : ZMod p) ^ 2 = 1 := by
        simpa using congr_arg ( fun x : ( ZMod p ) ˣ => ( x : ZMod p ) ) hx;
      aesop;
    exact le_trans ( Set.ncard_le_ncard h_solutions ) ( Set.ncard_insert_le _ _ ) |> le_trans <| by norm_num;
  have h_univ : (Set.univ : Set (ZMod p)ˣ).ncard = p - 1 := by
    rw [Set.ncard_univ, h_card_nat]
  -- p - 1 >= 4
  have h_ineq : 4 ≤ p - 1 := by
    exact Nat.le_sub_one_of_lt hp
  -- So ncard univ > ncard sols
  -- Thus there exists x in univ \ sols
  have h_univ : Set.ncard (Set.univ \ { x : (ZMod p)ˣ | x^2 = 1 }) > 0 := by
    rw [ Set.ncard_diff ] <;> norm_num [ Set.ncard_univ ] at * ; omega;
  obtain ⟨ u, hu ⟩ := Set.nonempty_of_ncard_ne_zero h_univ.ne'; use u; aesop;

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    rw [ inv_eq_of_mul_eq_one_right ];
    norm_num [ ← Matrix.one_fin_two, ← Matrix.ext_iff ];
    rw [ mul_inv_cancel₀ ];
    · exact ⟨ ⟨ rfl, by ring ⟩, inv_mul_cancel₀ ( Units.ne_zero u ) ⟩;
    · aesop;
    · exact mul_inv_cancel₀ ( Units.ne_zero u )

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection' (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_calc_helper (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    exact commutator_of_diagonal_and_transvection' p u y

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_calc (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_calc_v2 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection_calc p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_v2 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection_calc p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_v3 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection_calc_v2 p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_calc_v3 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection_calc_v2 p u y using 1

/-
The commutator of a diagonal matrix and a transvection is a transvection.
-/
lemma commutator_of_diagonal_and_transvection_calc_v4 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) (y : ZMod p) :
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
  let C := Matrix.of ![![1, y], ![0, 1]]
  let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
  let C_inv := Matrix.of ![![1, -y], ![0, 1]]
  B * C * B_inv * C_inv = Matrix.of ![![1, (u_val ^ 2 - 1) * y], ![0, 1]] := by
    convert commutator_of_diagonal_and_transvection_calc_v3 p u y using 1

/-
If an action is 2-transitive, it is primitive.
-/
lemma IsPreprimitive_of_two_transitive {G : Type u} {X : Type v} [Group G] [MulAction G X] [Nontrivial X] (h : MulAction.IsMultiplyPretransitive G X 2) : MulAction.IsPreprimitive G X := by
  exact?

/-
The action of PSL(2, p) on the projective line is primitive for p >= 5.
-/
lemma PSL2_is_primitive (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  MulAction.IsPreprimitive (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) := by
    convert IsPreprimitive_of_two_transitive _ using 1;
    · refine' ⟨ _, _, _ ⟩;
      exact Projectivization.mk _ ( fun i => if i = 0 then 1 else 0 ) ( by intros h; simpa using congr_fun h 0 );
      exact Projectivization.mk _ ( fun i => if i = 0 then 0 else 1 ) ( by intros h; simpa using congr_fun h 1 );
      simp +decide [ Projectivization.mk_eq_mk_iff ];
      intro x hx; have := congr_fun hx 0; have := congr_fun hx 1; simp_all +decide ;
    · exact?

/-
Definition of a transvection matrix.
-/
def transvection_matrix (p : ℕ) (y : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p) :=
  Matrix.of ![![1, y], ![0, 1]]

/-
The determinant of a transvection matrix is 1.
-/
lemma transvection_matrix_det (p : ℕ) [Fact p.Prime] (y : ZMod p) :
  Matrix.det (transvection_matrix p y) = 1 := by
    unfold transvection_matrix; norm_num

/-
Definition of a transvection in SL(2, p).
-/
def SL2_transvection (p : ℕ) [Fact p.Prime] (y : ZMod p) : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) :=
  ⟨transvection_matrix p y, transvection_matrix_det p y⟩

/-
Transvections are in the commutator subgroup of SL(2, p) for p >= 5.
-/
lemma SL2_transvection_in_commutator (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (y : ZMod p) :
  SL2_transvection p y ∈ commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
    -- Use `exists_unit_sq_ne_one` to find `u` such that `u^2 - 1` is a unit.
    obtain ⟨u, hu⟩ : ∃ u : (ZMod p)ˣ, u^2 ≠ 1 := exists_unit_sq_ne_one p hp
    let u_val : ZMod p := u
    let u_inv : ZMod p := u⁻¹
    let B := Matrix.of ![![u_val, 0], ![0, u_inv]]
    let C := Matrix.of ![![1, y], ![0, 1]]
    let B_inv := Matrix.of ![![u_inv, 0], ![0, u_val]]
    let C_inv := Matrix.of ![![1, -y], ![0, 1]];
    -- Since $u^2 - 1$ is invertible, we can write $y$ as $(u^2 - 1) * z$ for some $z$.
    obtain ⟨z, hz⟩ : ∃ z : ZMod p, y = (u_val ^ 2 - 1) * z := by
      have h_inv : (u_val ^ 2 - 1) ≠ 0 := by
        simp_all +decide [ sub_eq_iff_eq_add ];
        exact ⟨ by contrapose! hu; aesop, by contrapose! hu; aesop ⟩;
      exact ⟨ y / ( u_val ^ 2 - 1 ), by rw [ mul_div_cancel₀ _ h_inv ] ⟩;
    -- Therefore, $C$ is a commutator of $B$ and $C$.
    have hC_comm : ∃ g h : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), g * h * g⁻¹ * h⁻¹ = SL2_transvection p y := by
      use ⟨B, by
        norm_num [ B, C, B_inv, C_inv ];
        exact mul_inv_cancel₀ ( Units.ne_zero u )⟩, ⟨Matrix.of ![![1, z], ![0, 1]], by
        norm_num [ Matrix.det_fin_two ]⟩
      generalize_proofs at *;
      ext i j ; fin_cases i <;> fin_cases j <;> simp +decide [ *, Matrix.mul_apply, Matrix.inv_def ];
      · simp +decide [ B, Matrix.adjugate_fin_two ];
        exact mul_inv_cancel₀ ( Units.ne_zero u );
      · simp +decide [ B, Matrix.adjugate_fin_two ];
        simp +decide [ SL2_transvection, Matrix.SpecialLinearGroup ];
        simp +decide [ transvection_matrix, pow_two ] ; ring;
        rw [ show u_val * u_inv = 1 by exact mul_inv_cancel₀ ( Units.ne_zero u ) ] ; ring;
      · simp +decide [ B, Matrix.adjugate_fin_two ];
        exact?;
      · simp +decide [ B, Matrix.adjugate_fin_two ];
        exact inv_mul_cancel₀ ( Units.ne_zero u );
    exact hC_comm.elim fun g hg => hg.elim fun h hh => hh ▸ Subgroup.commutator_mem_commutator ( Subgroup.mem_top g ) ( Subgroup.mem_top h )

/-
Definition of transpose transvection matrices and their inclusion in SL(2, p).
-/
def transvection_matrix_transpose (p : ℕ) (x : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p) :=
  Matrix.of ![![1, 0], ![x, 1]]

lemma transvection_matrix_transpose_det (p : ℕ) [Fact p.Prime] (x : ZMod p) :
  Matrix.det (transvection_matrix_transpose p x) = 1 := by
  unfold transvection_matrix_transpose; norm_num

def SL2_transvection_transpose (p : ℕ) [Fact p.Prime] (x : ZMod p) : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) :=
  ⟨transvection_matrix_transpose p x, transvection_matrix_transpose_det p x⟩

/-
Transpose transvections are in the commutator subgroup of SL(2, p).
-/
def w_matrix (p : ℕ) : Matrix (Fin 2) (Fin 2) (ZMod p) :=
  Matrix.of ![![0, -1], ![1, 0]]

lemma w_matrix_det (p : ℕ) [Fact p.Prime] :
  Matrix.det (w_matrix p) = 1 := by
  unfold w_matrix; norm_num

def SL2_w (p : ℕ) [Fact p.Prime] : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) :=
  ⟨w_matrix p, w_matrix_det p⟩

lemma SL2_transvection_transpose_in_commutator (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (x : ZMod p) :
  SL2_transvection_transpose p x ∈ commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
    -- By the properties of the commutator subgroup, if an element is in the commutator subgroup, then its conjugate is also in the commutator subgroup.
    have h_conj : ∀ g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), SL2_transvection p (-x) ∈ commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) → g * SL2_transvection p (-x) * g⁻¹ ∈ commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
      exact fun g hg => Subgroup.Normal.mem_comm inferInstance ( by simpa using hg );
    convert h_conj ( ⟨ !![0, -1; 1, 0], ?_ ⟩ ) _ using 1 <;> norm_num [ SL2_transvection, SL2_transvection_transpose ];
    · ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.inv_def ];
      · simp +decide [ Matrix.vecMul, transvection_matrix, transvection_matrix_transpose ];
      · simp +decide [ Matrix.vecMul, transvection_matrix, transvection_matrix_transpose ];
      · simp +decide [ Matrix.vecMul, transvection_matrix, transvection_matrix_transpose ];
      · simp +decide [ transvection_matrix, transvection_matrix_transpose, Matrix.vecMul ];
    · convert SL2_transvection_in_commutator p hp ( -x ) using 1

/-
The set of elementary transvections (upper and lower) in SL(2, p).
-/
def elementary_transvections (p : ℕ) [Fact p.Prime] : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :=
  { A | ∃ y, A = SL2_transvection p y } ∪ { A | ∃ x, A = SL2_transvection_transpose p x }

/-
The matrix w is in the subgroup generated by elementary transvections.
-/
lemma w_mem_closure_elementary (p : ℕ) [Fact p.Prime] :
  SL2_w p ∈ Subgroup.closure (elementary_transvections p) := by
    -- We have the identity `w = [[0, -1], [1, 0]] = [[1, -1], [0, 1]] * [[1, 0], [1, 1]] * [[1, -1], [0, 1]]`.
    have h_identity : SL2_w p = (SL2_transvection p (-1)) * (SL2_transvection_transpose p 1) * (SL2_transvection p (-1)) := by
      ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, SL2_transvection, SL2_transvection_transpose, SL2_w ];
      · simp +decide [ w_matrix, transvection_matrix, transvection_matrix_transpose ];
      · unfold w_matrix transvection_matrix transvection_matrix_transpose; norm_num;
      · unfold w_matrix transvection_matrix transvection_matrix_transpose; norm_num;
      · simp +decide [ w_matrix, transvection_matrix, transvection_matrix_transpose ];
    exact h_identity.symm ▸ Subgroup.mul_mem _ ( Subgroup.mul_mem _ ( Subgroup.subset_closure ( Set.mem_union_left _ ⟨ -1, rfl ⟩ ) ) ( Subgroup.subset_closure ( Set.mem_union_right _ ⟨ 1, rfl ⟩ ) ) ) ( Subgroup.subset_closure ( Set.mem_union_left _ ⟨ -1, rfl ⟩ ) )

/-
Definition of the generalized Weyl element w(u).
-/
def w_gen (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) :=
  let u_val : ZMod p := u
  let u_inv : ZMod p := u⁻¹
  ⟨Matrix.of ![![0, u_val], ![-u_inv, 0]], by
    simp +decide [ Matrix.det_fin_two ];
    exact mul_inv_cancel₀ u.ne_zero⟩

/-
Product of an upper transvection and a lower transvection.
-/
lemma transvection_matrix_mul_transvection_matrix_transpose (p : ℕ) (u v : ZMod p) :
  transvection_matrix p u * transvection_matrix_transpose p v =
  Matrix.of ![![1 + u * v, u], ![v, 1]] := by
    -- By definition of matrix multiplication, we can expand the product.
    ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, transvection_matrix, transvection_matrix_transpose] ;

/-
First step of the decomposition of w(u).
-/
lemma w_gen_step1 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  (SL2_transvection p (u : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p)) *
  (SL2_transvection_transpose p (-(u⁻¹ : ZMod p)) : Matrix (Fin 2) (Fin 2) (ZMod p)) =
  Matrix.of ![![0, (u : ZMod p)], ![-(u⁻¹ : ZMod p), 1]] := by
    convert transvection_matrix_mul_transvection_matrix_transpose p u ( - ( u : ZMod p ) ⁻¹ ) using 1;
    field_simp;
    ring

/-
Second step of the decomposition of w(u).
-/
lemma w_gen_step2 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  Matrix.of ![![0, (u : ZMod p)], ![-(u⁻¹ : ZMod p), 1]] *
  (SL2_transvection p (u : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p)) =
  (w_gen p u : Matrix (Fin 2) (Fin 2) (ZMod p)) := by
    erw [ Matrix.mul_fin_two ];
    field_simp;
    convert rfl using 2 ; ring;
    exact?

/-
Decomposition of w(u) into elementary transvections.
-/
lemma w_gen_decomposition (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  w_gen p u = SL2_transvection p u * SL2_transvection_transpose p (-u⁻¹) * SL2_transvection p u := by
    -- By combining the results from w_gen_step1 and w_gen_step2, we can conclude the proof.
    have h_combined : (SL2_transvection p (u : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p)) * (SL2_transvection_transpose p (-(u⁻¹ : ZMod p)) : Matrix (Fin 2) (Fin 2) (ZMod p)) * (SL2_transvection p (u : ZMod p) : Matrix (Fin 2) (Fin 2) (ZMod p)) = (w_gen p u : Matrix (Fin 2) (Fin 2) (ZMod p)) := by
      rw [ ← w_gen_step2, ← w_gen_step1 ];
    -- Since the coercion from the subgroup to the matrix group is injective, we can conclude that the elements themselves are equal.
    apply Subtype.ext_iff.mpr;
    convert h_combined.symm using 1;
    norm_cast

/-
w(u) is in the subgroup generated by elementary transvections.
-/
lemma w_gen_mem_closure (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  w_gen p u ∈ Subgroup.closure (elementary_transvections p) := by
  rw [w_gen_decomposition]
  apply Subgroup.mul_mem
  apply Subgroup.mul_mem
  apply Subgroup.subset_closure
  left
  use u
  apply Subgroup.subset_closure
  right
  use -u⁻¹
  apply Subgroup.subset_closure
  left
  use u

/-
Decomposition of w(u) into elementary transvections (version 2).
-/
lemma w_gen_decomposition_v2 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  w_gen p u = SL2_transvection p u * SL2_transvection_transpose p (-u⁻¹) * SL2_transvection p u := by
    exact?

/-
Decomposition of w(u) into elementary transvections (version 3).
-/
lemma w_gen_decomposition_v3 (p : ℕ) [Fact p.Prime] (u : (ZMod p)ˣ) :
  w_gen p u = SL2_transvection p u * SL2_transvection_transpose p (-u⁻¹) * SL2_transvection p u := by
    exact?

/-
If the bottom-left entry of a matrix in SL(2, p) is non-zero, it is in the subgroup generated by elementary transvections.
-/
lemma SL2_mem_closure_of_c_ne_zero (p : ℕ) [Fact p.Prime] (A : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) (h : A.1 1 0 ≠ 0) :
  A ∈ Subgroup.closure (elementary_transvections p) := by
    -- Let `c = A 1 0`. Since `c != 0`, it is invertible.
    set c := A.val 1 0
    have hc_inv : ∃ c_inv : ZMod p, c * c_inv = 1 := by
      exact ⟨ c⁻¹, mul_inv_cancel₀ h ⟩;
    obtain ⟨c_inv, hc_inv⟩ := hc_inv
    set a := A.val 0 0
    set x := (1 - a) * c_inv
    set T1 := SL2_transvection p x
    set A' := T1 * A
    set c' := A'.val 1 0
    set y := -c'
    set T2 := SL2_transvection_transpose p y
    set A'' := T2 * A';
    -- Then `A''` is an upper transvection, hence in the closure.
    have hA''_transvection : ∃ z : ZMod p, A'' = SL2_transvection p z := by
      have hA''_transvection : A''.val 0 0 = 1 ∧ A''.val 1 0 = 0 ∧ A''.val 1 1 = 1 := by
        have hA''_transvection : A''.val 0 0 = 1 ∧ A''.val 1 0 = 0 := by
          simp +zetaDelta at *;
          simp +decide [ Matrix.mul_apply, SL2_transvection, SL2_transvection_transpose ];
          unfold transvection_matrix_transpose transvection_matrix; simp +decide [ hc_inv ] ;
          grind +ring;
        have hA''_transvection : A''.val 0 0 * A''.val 1 1 - A''.val 0 1 * A''.val 1 0 = 1 := by
          convert A''.prop using 1;
          rw [ Matrix.det_fin_two ];
        aesop;
      use A''.val 0 1;
      ext i j; fin_cases i <;> fin_cases j <;> aesop;
    -- Since `T1` and `T2` are in the closure, `A` is in the closure.
    have hT1_closure : T1 ∈ Subgroup.closure (elementary_transvections p) := by
      exact Subgroup.subset_closure ( Set.mem_union_left _ ⟨ x, rfl ⟩ )
    have hT2_closure : T2 ∈ Subgroup.closure (elementary_transvections p) := by
      exact Subgroup.subset_closure ( Set.mem_union_right _ ⟨ y, rfl ⟩ )
    have hA''_closure : A'' ∈ Subgroup.closure (elementary_transvections p) := by
      exact hA''_transvection.elim fun z hz => hz ▸ Subgroup.subset_closure ( Set.mem_union_left _ ⟨ z, rfl ⟩ );
    have hA_closure : A = T1⁻¹ * T2⁻¹ * A'' := by
      simp +zetaDelta at *;
      simp +decide [ ← mul_assoc ];
    exact hA_closure.symm ▸ Subgroup.mul_mem _ ( Subgroup.mul_mem _ ( Subgroup.inv_mem _ hT1_closure ) ( Subgroup.inv_mem _ hT2_closure ) ) hA''_closure

/-
If the bottom-left entry of a matrix in SL(2, p) is zero, it is in the subgroup generated by elementary transvections.
-/
lemma SL2_mem_closure_of_c_eq_zero (p : ℕ) [Fact p.Prime] (A : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) (h : A.1 1 0 = 0) :
  A ∈ Subgroup.closure (elementary_transvections p) := by
    have hA'_nonzero : (A 0 0) ≠ 0 := by
      have := A.2;
      rw [ Matrix.det_fin_two ] at this ; aesop;
    -- Let `L = SL2_transvection_transpose p 1`.
    set L : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) := SL2_transvection_transpose p 1;
    -- By `SL2_mem_closure_of_c_ne_zero`, `A'` is in the closure.
    have hA'_closure : L * A ∈ Subgroup.closure (elementary_transvections p) := by
      apply_rules [ SL2_mem_closure_of_c_ne_zero ];
      simp +decide [ *, Matrix.mul_apply ];
      exact one_ne_zero;
    have hL_inv_closure : L⁻¹ ∈ Subgroup.closure (elementary_transvections p) := by
      exact Subgroup.inv_mem _ ( Subgroup.subset_closure <| Set.mem_union_right _ ⟨ 1, rfl ⟩ );
    simpa using Subgroup.mul_mem _ hL_inv_closure hA'_closure

/-
SL(2, p) is generated by elementary transvections.
-/
lemma SL2_generated_by_elementary (p : ℕ) [Fact p.Prime] :
  Subgroup.closure (elementary_transvections p) = ⊤ := by
  ext A
  constructor
  · intro h; exact Subgroup.mem_top A
  · intro h
    by_cases h_c : A.1 1 0 = 0
    · exact SL2_mem_closure_of_c_eq_zero p A h_c
    · exact SL2_mem_closure_of_c_ne_zero p A h_c

/-
SL(2, p) is a perfect group for p >= 5.
-/
lemma SL2_is_perfect (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) = ⊤ := by
  rw [eq_top_iff, ← SL2_generated_by_elementary p, Subgroup.closure_le]
  rintro A hA
  rcases hA with ⟨y, rfl⟩ | ⟨x, rfl⟩
  · exact SL2_transvection_in_commutator p hp y
  · exact SL2_transvection_transpose_in_commutator p hp x

/-
PSL(2, p) is a perfect group for p >= 5.
-/
lemma PSL2_is_perfect (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  commutator (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) = ⊤ := by
    rw [ commutator_eq_closure ];
    refine' eq_top_iff.mpr _;
    intro x hx;
    obtain ⟨ g, rfl ⟩ := QuotientGroup.mk_surjective x;
    -- Since $g$ is in the top subgroup, it is in the commutator subgroup of $SL(2, p)$.
    have hg_comm : g ∈ commutator (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) := by
      rw [ SL2_is_perfect p hp ] at * ; aesop;
    rw [ commutator_eq_closure ] at hg_comm;
    refine' Subgroup.closure_induction _ _ _ _ hg_comm;
    · rintro _ ⟨ a, b, rfl ⟩;
      exact Subgroup.subset_closure ⟨ a, b, rfl ⟩;
    · exact OneMemClass.one_mem _;
    · exact fun x y hx hy hx' hy' => by simpa using Subgroup.mul_mem _ hx' hy';
    · exact fun x hx₁ hx₂ => by simpa using Subgroup.inv_mem _ hx₂;

/-
The subgroup of upper unitriangular matrices in SL(2, p).
-/
def U_inf (p : ℕ) [Fact p.Prime] : Subgroup (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :=
  Subgroup.closure { A | ∃ y, A = SL2_transvection p y }

/-
Multiplication of upper transvections corresponds to addition of the parameters.
-/
lemma SL2_transvection_mul (p : ℕ) [Fact p.Prime] (x y : ZMod p) :
  SL2_transvection p x * SL2_transvection p y = SL2_transvection p (x + y) := by
    unfold SL2_transvection;
    ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ transvection_matrix ] ; ring

/-
The subgroup of upper transvections is commutative.
-/
lemma U_inf_comm (p : ℕ) [Fact p.Prime] (a b : U_inf p) : a * b = b * a := by
  -- By definition of $U_\infty$, we know that every element is of the form $SL2_transvection p y$ for some $y \in \mathbb{F}_p$.
  have h_gen : ∀ (g : Matrix.SpecialLinearGroup (Fin 2) (ZMod p)), g ∈ U_inf p → ∃ y : ZMod p, g = SL2_transvection p y := by
    refine fun g hg => Subgroup.closure_induction ?_ ?_ ?_ ?_ hg <;> norm_num +zetaDelta at *;
    · exact ⟨ 0, by ext i j; fin_cases i <;> fin_cases j <;> rfl ⟩;
    · rintro x y hx hy a ha b hb; use a + b; simp +decide [ *, SL2_transvection_mul ] ;
    · rintro x hx y rfl; use -y; ext i j; fin_cases i <;> fin_cases j <;> norm_num [ SL2_transvection ] ;
      · unfold transvection_matrix; simp +decide [ Matrix.adjugate_fin_two ] ;
      · unfold transvection_matrix; norm_num [ Matrix.adjugate_fin_two ] ;
      · simp +decide [ transvection_matrix, Matrix.adjugate_fin_two ];
      · simp +decide [ transvection_matrix, Matrix.adjugate_fin_two ];
  rcases h_gen a a.2 with ⟨ y, hy ⟩ ; rcases h_gen b b.2 with ⟨ z, hz ⟩ ; simp_all +decide [ Subtype.ext_iff ] ;
  rw [ SL2_transvection_mul, SL2_transvection_mul ] ; ring

/-
The point at infinity in the projective line.
-/
def P_inf (p : ℕ) [Fact p.Prime] : Projectivization (ZMod p) (Fin 2 → ZMod p) :=
  Projectivization.mk (ZMod p) (fun i => if i = 0 then 1 else 0) (by
  exact fun h => by simpa using congr_fun h 0;)

/-
The subgroup A_inf of PSL(2, p) is the image of U_inf under the projection.
-/
def A_inf (p : ℕ) [Fact p.Prime] : Subgroup (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) :=
  Subgroup.map (QuotientGroup.mk' (Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)))) (U_inf p)

/-
The subgroup of upper transvections is an abelian group.
-/
instance U_inf_commGroup (p : ℕ) [Fact p.Prime] : CommGroup (U_inf p) :=
  { (inferInstance : Group (U_inf p)) with
    mul_comm := U_inf_comm p }

/-
The subgroup A_inf is abelian.
-/
lemma A_inf_comm (p : ℕ) [Fact p.Prime] (x y : A_inf p) : x * y = y * x := by
  rcases x with ⟨ x, hx ⟩ ; rcases y with ⟨ y, hy ⟩ ; simp_all +decide [ mul_comm ] ;
  obtain ⟨ x', hx', rfl ⟩ := Subgroup.mem_map.mp hx; obtain ⟨ y', hy', rfl ⟩ := Subgroup.mem_map.mp hy; simp_all +decide [ mul_comm ] ;
  have h_comm : x' * y' = y' * x' := by
    have h_comm : ∀ x y : U_inf p, x * y = y * x := by
      exact?;
    exact Subtype.ext_iff.mp ( h_comm ⟨ x', hx' ⟩ ⟨ y', hy' ⟩ );
  exact congr_arg ( QuotientGroup.mk ) h_comm

/-
The stabilizer of the point at infinity in PSL(2, p).
-/
def Stab_P_inf (p : ℕ) [Fact p.Prime] : Subgroup (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) :=
  MulAction.stabilizer (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (P_inf p)

/-
The Borel subgroup of upper triangular matrices in SL(2, p).
-/
def B_inf (p : ℕ) [Fact p.Prime] : Subgroup (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :=
  { carrier := { A | A.1 1 0 = 0 },
    one_mem' := by
      exact?,
    mul_mem' := by
      simp +decide [ Matrix.mul_apply ];
      aesop,
    inv_mem' := by
      simp +decide [ Matrix.adjugate_fin_two ] }

#check B_inf

/-
The subgroup of upper transvections is contained in the Borel subgroup.
-/
lemma U_inf_subset_B_inf (p : ℕ) [Fact p.Prime] : U_inf p ≤ B_inf p := by
  intro A hA;
  refine' Subgroup.closure_induction _ _ _ _ hA;
  · unfold B_inf; aesop;
  · exact Subgroup.one_mem _;
  · intro x y hx hy hx' hy'; exact (by
    exact Subgroup.mul_mem _ hx' hy');
  · simp_all +decide [ B_inf, Matrix.SpecialLinearGroup.ext_iff ]

/-
The subgroup of upper transvections is normal in the Borel subgroup.
-/
lemma U_inf_normal_in_B_inf (p : ℕ) [Fact p.Prime] :
  ∀ b ∈ B_inf p, ∀ u ∈ U_inf p, b * u * b⁻¹ ∈ U_inf p := by
    intro b hb u hu
    have h_conj : ∀ w : ZMod p, b * SL2_transvection p w * b⁻¹ ∈ U_inf p := by
      intro w
      have h_conj : b * SL2_transvection p w * b⁻¹ = SL2_transvection p (b.1 0 0 ^ 2 * w) := by
        ext i j ; fin_cases i <;> fin_cases j <;> simp +decide [ Matrix.mul_apply, sq, Matrix.inv_def ];
        · simp +decide [ Matrix.adjugate_fin_two, SL2_transvection ];
          simp_all +decide [ B_inf, transvection_matrix ];
          convert b.2 using 1;
          rw [ Matrix.det_fin_two ] ; aesop;
        · simp +decide [ Matrix.adjugate_fin_two, SL2_transvection ];
          simp +decide [ transvection_matrix ] ; ring;
        · simp_all +decide [ B_inf, Matrix.adjugate_fin_two ];
          simp_all +decide [ SL2_transvection ];
          simp_all +decide [ transvection_matrix ];
        · unfold SL2_transvection; norm_num [ Matrix.adjugate_fin_two ] ; ring;
          unfold transvection_matrix; norm_num; ring;
          field_simp;
          convert b.2 using 1 ; ring!;
          rw [ Matrix.det_fin_two ] ; ring!;
          have := hb; unfold B_inf at this; aesop;
      exact h_conj.symm ▸ Subgroup.subset_closure ⟨ _, rfl ⟩;
    refine' Subgroup.closure_induction _ _ _ _ hu;
    · aesop;
    · simp;
    · intro x y hx hy hx' hy'; convert Subgroup.mul_mem _ hx' hy' using 1; group;
    · intro x hx hx'; have := Subgroup.inv_mem _ hx'; simp_all +decide [ mul_assoc ] ;

/-
The canonical projection from SL(2, p) to PSL(2, p).
-/
def SL2_to_PSL2 (p : ℕ) [Fact p.Prime] : Matrix.SpecialLinearGroup (Fin 2) (ZMod p) →* Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p) :=
  QuotientGroup.mk' (Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)))

/-
The stabilizer of the point at infinity in PSL(2, p) is the image of the Borel subgroup.
-/
lemma Stab_P_inf_eq_map_B_inf (p : ℕ) [Fact p.Prime] :
  Stab_P_inf p = Subgroup.map (SL2_to_PSL2 p) (B_inf p) := by
    refine' le_antisymm _ _ <;> intro g;
    · simp +decide [ Stab_P_inf ];
      obtain ⟨ g, rfl ⟩ := QuotientGroup.mk_surjective g;
      intro hg
      use g;
      erw [ Projectivization.mk_eq_mk_iff ] at hg;
      simp_all +decide [ funext_iff, Fin.forall_fin_two, Matrix.mulVec, dotProduct ];
      exact ⟨ by exact Set.mem_setOf.mpr hg.2.symm, rfl ⟩;
    · rintro ⟨ x, hx, rfl ⟩;
      -- Since $x \in B_inf$, we have $x.1 1 0 = 0$. Therefore, the action of $x$ on $P_inf$ fixes $P_inf$.
      have h_fix : ∀ x : Matrix.SpecialLinearGroup (Fin 2) (ZMod p), x.1 1 0 = 0 → (SL2_action_map p x) (P_inf p) = P_inf p := by
        intro x hx;
        unfold SL2_action_map P_inf;
        simp +decide [ Projectivization.map, Projectivization.mk ];
        rw [ Quotient.eq'' ];
        refine' ⟨ Units.mk0 ( x.val 0 0 ) _, _ ⟩;
        all_goals simp_all +decide [ funext_iff, Fin.forall_fin_two, Matrix.mulVec ];
        have := x.2;
        rw [ Matrix.det_fin_two ] at this ; aesop;
      exact h_fix x hx

/-
A_inf is a subgroup of the stabilizer of the point at infinity.
-/
lemma A_inf_le_Stab_P_inf (p : ℕ) [Fact p.Prime] : A_inf p ≤ Stab_P_inf p := by
  rw [Stab_P_inf_eq_map_B_inf]
  apply Subgroup.map_mono
  apply U_inf_subset_B_inf

/-
The subgroup A_inf is normal in the stabilizer of the point at infinity.
-/
lemma A_inf_normal_Stab_P_inf (p : ℕ) [Fact p.Prime] :
  ∀ m ∈ Stab_P_inf p, ∀ a ∈ A_inf p, m * a * m⁻¹ ∈ A_inf p := by
    intro m hm a ha
    obtain ⟨b, hb⟩ : ∃ b ∈ B_inf p, m = SL2_to_PSL2 p b := by
      rw [ Stab_P_inf_eq_map_B_inf ] at hm; exact hm.imp fun x hx => by aesop;
    obtain ⟨u, hu⟩ : ∃ u ∈ U_inf p, a = SL2_to_PSL2 p u := by
      cases ha ; aesop;
    -- Then `m * a * m⁻¹ = \pi(b) * \pi(u) * \pi(b)^{-1} = \pi(b * u * b^{-1})`.
    have h_conj : m * a * m⁻¹ = SL2_to_PSL2 p (b * u * b⁻¹) := by
      aesop;
    exact h_conj.symm ▸ Subgroup.mem_map_of_mem _ ( U_inf_normal_in_B_inf p b hb.1 u hu.1 )

/-
Conjugation of a transvection by w yields a transpose transvection.
-/
lemma SL2_conjugation_by_w (p : ℕ) [Fact p.Prime] (x : ZMod p) :
  SL2_w p * SL2_transvection p (-x) * (SL2_w p)⁻¹ = SL2_transvection_transpose p x := by
    ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.inv_def ];
    · unfold SL2_w SL2_transvection SL2_transvection_transpose; norm_num [ Matrix.adjugate_fin_two ] ;
      unfold w_matrix transvection_matrix transvection_matrix_transpose; norm_num;
    · simp +decide [ Matrix.adjugate_fin_two, SL2_w, SL2_transvection, SL2_transvection_transpose ];
      simp +decide [ w_matrix, transvection_matrix, transvection_matrix_transpose ];
    · simp +decide [ SL2_transvection, SL2_transvection_transpose, w_matrix, Matrix.adjugate_fin_two ];
      unfold transvection_matrix transvection_matrix_transpose SL2_w;
      unfold w_matrix; norm_num;
    · simp +decide [ SL2_transvection, SL2_transvection_transpose, w_matrix, Matrix.adjugate_fin_two ];
      simp +decide [ SL2_w, w_matrix, transvection_matrix, transvection_matrix_transpose ]

/-
The subgroup of lower unitriangular matrices in SL(2, p).
-/
def U_inf_transpose (p : ℕ) [Fact p.Prime] : Subgroup (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)) :=
  Subgroup.closure { A | ∃ x, A = SL2_transvection_transpose p x }

/-
The subgroup of lower transvections is the conjugate of the subgroup of upper transvections by w.
-/
lemma U_inf_transpose_eq_conj (p : ℕ) [Fact p.Prime] :
  U_inf_transpose p = Subgroup.map (MulAut.conj (SL2_w p)).toMonoidHom (U_inf p) := by
    refine' le_antisymm _ _;
    · rw [ U_inf_transpose, Subgroup.closure_le ];
      rintro _ ⟨ x, rfl ⟩;
      refine' ⟨ _, Subgroup.subset_closure ⟨ -x, rfl ⟩, _ ⟩ ; simp +decide [ SL2_conjugation_by_w ];
    · rw [ Subgroup.map_le_iff_le_comap ];
      refine' fun x hx => Subgroup.closure_induction _ _ _ _ hx <;> simp +decide [ Subgroup.mem_closure ];
      · intro a
        have h_conj : SL2_w p * SL2_transvection p a * (SL2_w p)⁻¹ = SL2_transvection_transpose p (-a) := by
          convert SL2_conjugation_by_w p ( -a ) using 1 ; group
        rw [h_conj]
        exact Subgroup.subset_closure (by
        exact ⟨ _, rfl ⟩);
      · exact fun x y hx hy hx' hy' => by simpa [ mul_assoc ] using Subgroup.mul_mem _ hx' hy';

/-
The normal closure of the subgroup of upper transvections is the whole group SL(2, p).
-/
lemma U_inf_gen_SL2 (p : ℕ) [Fact p.Prime] :
  Subgroup.normalClosure (U_inf p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) = ⊤ := by
    -- Since $U_\infty$ and $U_\infty^T$ are conjugate by $w$, their normal closures are the same.
    have h_conj : Subgroup.normalClosure (U_inf p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) = Subgroup.normalClosure (U_inf_transpose p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) := by
      have h_conj : U_inf_transpose p = Subgroup.map (MulAut.conj (SL2_w p)).toMonoidHom (U_inf p) := by
        exact?;
      rw [ h_conj ];
      refine' le_antisymm _ _ <;> simp +decide [ Subgroup.normalClosure ];
      · simp +decide [ Group.conjugatesOfSet ];
        simp +decide [ conjugatesOf ];
        intro i hi b hb; obtain ⟨ c, rfl ⟩ := hb; exact Subgroup.subset_closure ( Set.mem_iUnion₂.mpr ⟨ _, hi, ⟨ c * ( SL2_w p ) ⁻¹, by group ⟩ ⟩ ) ;
      · simp +decide [ Set.subset_def, Group.conjugatesOfSet ];
        simp +decide [ conjugatesOf ];
        rintro x y hy z rfl;
        exact Subgroup.subset_closure <| Set.mem_iUnion₂.mpr ⟨ y, hy, ⟨ z * SL2_w p, by group ⟩ ⟩;
    -- Since $U_\infty$ and $U_\infty^T$ are conjugate by $w$, their normal closures are the same. Therefore, the normal closure of $U_\infty$ contains $U_\infty^T$.
    have h_contain_transpose : U_inf_transpose p ≤ Subgroup.normalClosure (U_inf p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) := by
      exact h_conj.symm ▸ Subgroup.le_normalClosure;
    have h_normal_closure : Subgroup.closure (elementary_transvections p) ≤ Subgroup.normalClosure (U_inf p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p))) := by
      rw [ Subgroup.closure_le ];
      rintro x ( ⟨ y, rfl ⟩ | ⟨ y, rfl ⟩ ) <;> [ exact Subgroup.subset_normalClosure ( Subgroup.subset_closure ⟨ y, rfl ⟩ ) ; exact h_contain_transpose ( Subgroup.subset_closure ⟨ y, rfl ⟩ ) ];
    exact le_antisymm ( le_top ) ( h_normal_closure.trans' ( by rw [ SL2_generated_by_elementary ] ) )

/-
The normal closure of A_inf is the whole group PSL(2, p).
-/
lemma A_inf_gen_PSL2 (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  Subgroup.normalClosure (A_inf p : Set (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p))) = ⊤ := by
    have h_normal_closure : Subgroup.map (QuotientGroup.mk' (Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)))) (Subgroup.normalClosure (U_inf p : Set (Matrix.SpecialLinearGroup (Fin 2) (ZMod p)))) = ⊤ := by
      rw [ U_inf_gen_SL2 p ];
      ext; simp [Subgroup.map];
    refine' le_antisymm _ _;
    · exact le_top;
    · rw [ ← h_normal_closure ];
      rw [ Subgroup.map_le_iff_le_comap ];
      refine' Subgroup.normalClosure_le_normal _;
      intro x hx;
      refine' Subgroup.subset_normalClosure _;
      exact Subgroup.mem_map_of_mem _ hx

#check MulAction.exists_smul_eq

/-
The subgroup T(x) for the Iwasawa structure, defined as a conjugate of A_inf.
-/
def PSL2_T (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) : Subgroup (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) :=
  letI := PSL2_is_primitive p hp
  let g := Classical.choose (MulAction.exists_smul_eq (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (P_inf p) x)
  Subgroup.map (MulAut.conj g).toMonoidHom (A_inf p)

/-
PSL(2, p) is non-trivial for p >= 5.
-/
lemma PSL2_nontrivial (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  Nontrivial (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) := by
    refine' ⟨ _, _ ⟩;
    exact QuotientGroup.mk ( ⟨ Matrix.of ![![1, 1], ![0, 1]], by simp +decide [ Matrix.det_fin_two ] ⟩ : Matrix.SpecialLinearGroup ( Fin 2 ) ( ZMod p ) );
    refine' ⟨ 1, _ ⟩ ; simp +decide [ Subgroup.mem_center_iff ];
    refine' ⟨ ⟨ Matrix.of ![![0, 1], ![-1, 0]], _ ⟩, _ ⟩ <;> simp +decide [ Matrix.SpecialLinearGroup.ext_iff ]

#print MulAction.IwasawaStructure
#print MulAction.IsQuasiPreprimitive

/-
The subgroup T(x) is abelian.
-/
lemma PSL2_T_is_comm (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  IsMulCommutative (PSL2_T p hp x) := by
    use fun a b => ?_;
    have := @A_inf_comm p ‹_›;
    obtain ⟨ a, ha ⟩ := a; obtain ⟨ b, hb ⟩ := b; obtain ⟨ a', ha' ⟩ := ha; obtain ⟨ b', hb' ⟩ := hb; aesop;

/-
T(x) is the conjugate of A_inf by any element mapping P_inf to x.
-/
lemma PSL2_T_eq_conj_of_smul_eq (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) (g : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (h : g • P_inf p = x) :
  PSL2_T p hp x = Subgroup.map (MulAut.conj g).toMonoidHom (A_inf p) := by
    -- By definition of $h_x$, we have $h_x • P_\infty = x$.
    obtain ⟨h_x, hh_x⟩ : ∃ h_x : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p), h_x • P_inf p = x ∧ PSL2_T p hp x = Subgroup.map (MulAut.conj h_x).toMonoidHom (A_inf p) := by
      refine' ⟨ _, _, rfl ⟩;
      convert Classical.choose_spec ( MulAction.exists_smul_eq _ _ x );
      have := PSL2_is_primitive p hp;
      cases this;
      assumption;
    -- Since $g$ and $h_x$ are both in the stabilizer of $P_\infty$, they differ by an element of the stabilizer.
    obtain ⟨k, hk⟩ : ∃ k : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p), k ∈ Stab_P_inf p ∧ g = h_x * k := by
      refine' ⟨ h_x⁻¹ * g, _, _ ⟩ <;> simp_all +decide [ MulAction.mul_smul ];
      simp_all +decide [ Stab_P_inf, MulAction.mul_smul ];
      rw [ ← hh_x.1, inv_smul_smul ];
    -- Since $k$ is in the stabilizer of $P_\infty$, conjugation by $k$ preserves $A_\infty$.
    have h_conj_k : Subgroup.map (MulAut.conj k).toMonoidHom (A_inf p) = A_inf p := by
      refine' le_antisymm _ _;
      · exact fun x hx => by obtain ⟨ y, hy, rfl ⟩ := Subgroup.mem_map.mp hx; exact A_inf_normal_Stab_P_inf p k hk.1 y hy;
      · intro a ha; use k⁻¹ * a * k; simp_all +decide [ mul_assoc ] ;
        have h_conj_k : ∀ m ∈ Stab_P_inf p, ∀ a ∈ A_inf p, m * a * m⁻¹ ∈ A_inf p := by
          exact?;
        simpa [ mul_assoc ] using h_conj_k k⁻¹ ( by simpa using hk.1 ) a ha;
    simp_all +decide [ mul_assoc, Subgroup.map_map ];
    rw [ ← h_conj_k, Subgroup.map_map ];
    exact?

/-
The subgroup T(x) satisfies the conjugation property.
-/
lemma PSL2_T_is_conj (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) (g : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (x : Projectivization (ZMod p) (Fin 2 → ZMod p)) :
  PSL2_T p hp (g • x) = Subgroup.map (MulAut.conj g).toMonoidHom (PSL2_T p hp x) := by
    -- By definition of $PSL2_T$, we know that $PSL2_T p hp (g • x)$ is the conjugate of $A_inf$ by $g * h$, where $h$ is an element such that $h • P_inf = x$.
    obtain ⟨h, hh⟩ : ∃ h : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p), h • P_inf p = x := by
      have := PSL2_is_primitive p hp; exact?;
    rw [ PSL2_T_eq_conj_of_smul_eq p hp ( g • x ) ( g * h ) ];
    · rw [ PSL2_T_eq_conj_of_smul_eq p hp x h hh ];
      ext; simp +decide [ mul_assoc, Subgroup.mem_map ] ;
    · rw [ ← hh, MulAction.mul_smul ]

/-
The subgroups T(x) generate the whole group.
-/
lemma PSL2_T_is_generator (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  iSup (PSL2_T p hp) = ⊤ := by
    -- By definition of $T(x)$, we have that the normal closure of $A_\infty$ is contained in the supremum of the $T(x)$ subgroups.
    have h_normal_closure : Subgroup.normalClosure (A_inf p : Set (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p))) ≤ iSup (PSL2_T p hp) := by
      have h_normal_closure : ∀ g : Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p), Subgroup.map (MulAut.conj g).toMonoidHom (A_inf p) ≤ iSup (PSL2_T p hp) := by
        intro g;
        rw [ ← PSL2_T_eq_conj_of_smul_eq p hp _ g rfl ];
        exact le_iSup _ _;
      rw [ Subgroup.normalClosure ];
      simp_all +decide [ Subgroup.closure_le, Group.conjugatesOfSet ];
      intro i hi; intro g hg; simp_all +decide [ conjugatesOf ] ;
      obtain ⟨ c, rfl ⟩ := hg; specialize h_normal_closure c; simp_all +decide [ Subgroup.map ] ;
      exact h_normal_closure ⟨ i, hi, rfl ⟩;
    exact le_antisymm ( le_top ) ( by simpa [ A_inf_gen_PSL2 p hp ] using h_normal_closure )

/-
The Iwasawa structure for PSL(2, p).
-/
def PSL2_IwasawaStructure (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  MulAction.IwasawaStructure (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) :=
  { T := PSL2_T p hp
    is_comm := PSL2_T_is_comm p hp
    is_conj := PSL2_T_is_conj p hp
    is_generator := PSL2_T_is_generator p hp }

/-
PSL(2, p) is a simple group for p >= 5.
-/
theorem PSL2_is_simple (p : ℕ) [Fact p.Prime] (hp : 5 ≤ p) :
  IsSimpleGroup (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) := by
    have := @MulAction.IwasawaStructure.isSimpleGroup;
    contrapose! this;
    refine' ⟨ Matrix.ProjectiveSpecialLinearGroup ( Fin 2 ) ( ZMod p ), inferInstance, Projectivization ( ZMod p ) ( Fin 2 → ZMod p ), inferInstance, _, _, _, _ ⟩;
    · exact?;
    · exact?;
    · have h_primitive : MulAction.IsPreprimitive (Matrix.ProjectiveSpecialLinearGroup (Fin 2) (ZMod p)) (Projectivization (ZMod p) (Fin 2 → ZMod p)) := by
        exact?;
      exact?;
    · refine' ⟨ _, _, this ⟩;
      · exact PSL2_IwasawaStructure p hp;
      · exact?
