/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e4956b09-5fe1-4f4a-bcad-2b94d29767a0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have proved the Reidemeister-Schreier theorem, specifically the result that a finite index subgroup of a finitely presented group is finitely presented (`finitely_presented_of_finite_index`). This was achieved by using the Reidemeister-Schreier rewriting process (encapsulated in the provided `reidemeister_schreier_normal_closure_eq` lemma) to construct a finite presentation for the subgroup.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 04d8ffbc-8465-4506-9ebe-1fab639e3a4b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e45a48d8-98ce-469c-aa53-7fa8cd2de963

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A group is finitely presented if it is isomorphic to a group presented by a finite set of generators and a finite set of relations.
-/
universe u

def IsFinitelyPresentedGroup (G : Type u) [Group G] : Prop :=
  ∃ (α : Type u) (_ : Finite α) (rels : Set (FreeGroup α)) (_ : rels.Finite),
    Nonempty (G ≃* PresentedGroup rels)

/-
The free group on a finite type is finitely generated.
-/
lemma free_group_finite_type_is_fg {α : Type u} [Finite α] : Group.FG (FreeGroup α) := by
  obtain ⟨ s, hs ⟩ := Finite.exists_equiv_fin α;
  refine' ⟨ _, _ ⟩;
  exact Finset.image ( fun g : Fin s => FreeGroup.of ( hs.some.symm g ) ) Finset.univ;
  simp +decide [ Subgroup.closure, Set.ext_iff ];
  intro a ha; ext x; induction x using FreeGroup.induction_on; aesop;
  · exact iff_of_true ( ha ⟨ hs.some ‹_›, by simp +decide ⟩ ) trivial;
  · aesop;
  · aesop

/-
The free group on a set is isomorphic to the group presented by that set with empty relations.
-/
lemma free_group_equiv_presented_group_empty {α : Type u} :
    Nonempty (FreeGroup α ≃* PresentedGroup (∅ : Set (FreeGroup α))) := by
      refine' ⟨ _ ⟩;
      symm;
      refine' { Equiv.ofBijective _ ⟨ _, _ ⟩ with .. };
      refine' fun x => Quotient.liftOn' x ( fun x => x ) _;
      all_goals simp +decide [ QuotientGroup.leftRel_apply, Subgroup.normalClosure ];
      all_goals norm_num [ Group.conjugatesOfSet ];
      all_goals norm_num [ Function.Injective, Function.Surjective, mul_eq_one_iff_eq_inv ];
      · intro x y hxy
        generalize_proofs at *;
        induction x using Quotient.inductionOn' ; induction y using Quotient.inductionOn' ; aesop;
      · exact fun b => ⟨ Quotient.mk'' b, rfl ⟩;
      · rintro ⟨ x ⟩ ⟨ y ⟩ ; rfl

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_of_fg_free_abelian_group {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  -- Since `FreeAbelianGroup α` is finitely generated as a `ℤ`-module, its rank is finite.
  have h_rank_finite : Finite α := by
    have h_rank : Module.rank ℤ (FreeAbelianGroup α) = Cardinal.mk α := by
      convert ( FreeAbelianGroup.basis α ).mk_eq_rank.symm;
      · rw [ Cardinal.lift_id ];
      · rw [ Cardinal.lift_id ]
    exact Cardinal.lt_aleph0_iff_finite.mp ( h_rank ▸ Module.rank_lt_aleph0 _ _ );
  exact h_rank_finite

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  exact?

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_new {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  convert finite_basis_of_fg_free_abelian_group h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v3 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  convert finite_basis_of_fg_free_abelian_group h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v4 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  apply finite_of_fg_free_abelian_group h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v5 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  convert finite_basis_of_fg_free_abelian_group_v4 h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v6 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  convert finite_basis_of_fg_free_abelian_group_v5 h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v7 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  -- Apply the lemma that states if a free abelian group is finitely generated, its basis is finite.
  apply finite_basis_of_fg_free_abelian_group_v6 h

/-
If a free abelian group is finitely generated, its basis is finite.
-/
lemma finite_basis_of_fg_free_abelian_group_v8 {α : Type u} (h : AddGroup.FG (FreeAbelianGroup α)) : Finite α := by
  rw [AddGroup.fg_iff] at h
  obtain ⟨S, h_closure, h_fin⟩ := h
  have : Module.Finite ℤ (FreeAbelianGroup α) := by
    rw [Module.finite_def]
    use h_fin.toFinset
    rw [Set.Finite.coe_toFinset]
    rw [← Submodule.span_int_eq_addSubgroupClosure] at h_closure
    exact Submodule.toAddSubgroup_injective h_closure
  have h_rank : Module.rank ℤ (FreeAbelianGroup α) < Cardinal.aleph0 := Module.rank_lt_aleph0 ℤ (FreeAbelianGroup α)
  let b := FreeAbelianGroup.basis α
  let b' := b.reindex (Equiv.Set.univ α).symm
  have h_fin : Set.Finite (Set.univ : Set α) := Module.Basis.finite_index_of_rank_lt_aleph0 b' h_rank
  exact Set.finite_univ_iff.mp h_fin

/-
If a free group is finitely generated, its set of generators is finite.
-/
lemma finite_generators_of_fg_free_group {G : Type u} [Group G] [IsFreeGroup G] [Group.FG G] :
    Finite (IsFreeGroup.Generators G) := by
      obtain ⟨ S, hS ⟩ := ‹Group.FG G›;
      -- Since $G$ is free, its abelianization is the free abelian group on the set of generators.
      have h_abelianization : (Additive (Abelianization G)) ≃+ FreeAbelianGroup (IsFreeGroup.Generators G) := by
        have h_abelianization : (Abelianization G) ≃* Multiplicative (FreeAbelianGroup (IsFreeGroup.Generators G)) := by
          have h_iso : G ≃* (FreeGroup (IsFreeGroup.Generators G)) := by
            exact?
          have h_abelianization : (Abelianization G) ≃* (Abelianization (FreeGroup (IsFreeGroup.Generators G))) := by
            exact?;
          exact?;
        exact h_abelianization.toAdditive;
      -- Since $G$ is finitely generated, its abelianization is also finitely generated.
      have h_abelianization_fg : AddGroup.FG (Additive (Abelianization G)) := by
        have h_abelianization_fg : Group.FG (Abelianization G) := by
          have h_surjective : Function.Surjective (Abelianization.of : G → Abelianization G) := by
            exact QuotientGroup.mk_surjective
          refine' ⟨ S.image ( Abelianization.of ), _ ⟩;
          simp_all +decide [ Subgroup.eq_top_iff', Subgroup.mem_closure ];
          intro x K hK; obtain ⟨ y, rfl ⟩ := h_surjective x; specialize hS y ( K.comap ( Abelianization.of ) ) ; aesop;
        obtain ⟨ S, hS ⟩ := h_abelianization_fg;
        refine' ⟨ S, _ ⟩;
        simp_all +decide [ SetLike.ext_iff, Subgroup.mem_closure, AddSubgroup.mem_closure ];
        intro x K hK; specialize hS x ( K.toSubgroup ) ; aesop;
      convert finite_basis_of_fg_free_abelian_group_v8 _;
      obtain ⟨ S, hS ⟩ := h_abelianization_fg;
      refine' ⟨ S.image h_abelianization.toFun, _ ⟩;
      simp_all +decide [ SetLike.ext_iff, AddSubgroup.mem_closure ];
      intro x K hK; specialize hS ( h_abelianization.symm x |> Additive.toMul ) ( K.comap h_abelianization.toAddMonoidHom ) ; aesop;

/-
The abelianization of a free group is isomorphic to the free abelian group.
-/
noncomputable def abelianizationToFreeAbelianGroup (α : Type u) :
    Additive (Abelianization (FreeGroup α)) →+ FreeAbelianGroup α :=
  let to_fun : FreeGroup α →* Multiplicative (FreeAbelianGroup α) :=
    FreeGroup.lift (fun x => Multiplicative.ofAdd (FreeAbelianGroup.of x))
  let f : Abelianization (FreeGroup α) →* Multiplicative (FreeAbelianGroup α) :=
    Abelianization.lift to_fun
  { toFun := fun x => Multiplicative.toAdd (f (Additive.toMul x))
    map_zero' := by simp [f]
    map_add' := by
      intro x y
      simp [f] }

noncomputable def freeAbelianGroupToAbelianization (α : Type u) :
    FreeAbelianGroup α →+ Additive (Abelianization (FreeGroup α)) :=
  FreeAbelianGroup.lift (fun x => Additive.ofMul (Abelianization.of (FreeGroup.of x)))

lemma abelianizationToFreeAbelianGroup_comp_freeAbelianGroupToAbelianization (α : Type u) :
    (abelianizationToFreeAbelianGroup α).comp (freeAbelianGroupToAbelianization α) = AddMonoidHom.id _ := by
      refine' AddMonoidHom.ext fun x => _;
      induction x using FreeAbelianGroup.induction_on <;> aesop

lemma freeAbelianGroupToAbelianization_comp_abelianizationToFreeAbelianGroup (α : Type u) :
    (freeAbelianGroupToAbelianization α).comp (abelianizationToFreeAbelianGroup α) = AddMonoidHom.id _ := by
      ext x;
      simp +decide [ freeAbelianGroupToAbelianization, abelianizationToFreeAbelianGroup ]

noncomputable def abelianizationFreeGroupEquiv (α : Type u) :
    Additive (Abelianization (FreeGroup α)) ≃+ FreeAbelianGroup α :=
  AddMonoidHom.toAddEquiv (abelianizationToFreeAbelianGroup α) (freeAbelianGroupToAbelianization α)
    (freeAbelianGroupToAbelianization_comp_abelianizationToFreeAbelianGroup α)
    (abelianizationToFreeAbelianGroup_comp_freeAbelianGroupToAbelianization α)

/-
If a free group is finitely generated, its set of generators is finite.
-/
lemma finite_generators_of_fg_free_group_v2 {G : Type u} [Group G] [IsFreeGroup G] [Group.FG G] :
    Finite (IsFreeGroup.Generators G) := by
      -- Apply the lemma that states if a free group is finitely generated, its set of generators is finite.
      apply finite_generators_of_fg_free_group

/-
A finitely generated free group is finitely presented.
-/
lemma finitely_presented_of_is_free_group_of_fg {G : Type u} [Group G] [IsFreeGroup G] [Group.FG G] :
    IsFinitelyPresentedGroup G := by
  have : Finite (IsFreeGroup.Generators G) := finite_generators_of_fg_free_group_v2
  let β := IsFreeGroup.Generators G
  let e : G ≃* FreeGroup β := IsFreeGroup.toFreeGroup G
  obtain ⟨e'⟩ := free_group_equiv_presented_group_empty (α := β)
  use β, this, ∅, Set.finite_empty
  exact ⟨e.trans e'⟩

/-
A finite index subgroup of a finitely generated free group is finitely presented.
-/
lemma finitely_presented_of_finite_index_free_group {α : Type u} [Finite α] (K : Subgroup (FreeGroup α)) [K.FiniteIndex] :
    IsFinitelyPresentedGroup K := by
  have : Group.FG (FreeGroup α) := free_group_finite_type_is_fg
  have : Group.FG K := Subgroup.fg_of_index_ne_zero K
  have : IsFreeGroup K := subgroupIsFreeOfIsFree K
  exact finitely_presented_of_is_free_group_of_fg

/-
The quotient of a presented group by the normal closure of a finite set is isomorphic to a presented group with finitely many additional relations.
-/
lemma presented_group_quotient_iso_presented_group_add_rels {α : Type u} (rels : Set (FreeGroup α)) (S : Set (PresentedGroup rels)) (hS : S.Finite) :
    ∃ (S' : Set (FreeGroup α)), S'.Finite ∧ Nonempty (PresentedGroup rels ⧸ Subgroup.normalClosure S ≃* PresentedGroup (rels ∪ S')) := by
  let proj : FreeGroup α →* PresentedGroup rels := QuotientGroup.mk' _
  have h_surj : Function.Surjective proj := QuotientGroup.mk'_surjective _
  -- Choose a lift for each element in S
  let lift : PresentedGroup rels → FreeGroup α := Function.surjInv h_surj
  let S' := lift '' S
  have hS' : S'.Finite := hS.image lift
  use S'
  constructor
  · exact hS'
  · -- Now construct the isomorphism
    -- G = F / N, where N = normalClosure rels
    -- G / normalClosure S = (F / N) / normalClosure S
    -- This is isomorphic to F / (N * proj⁻¹(normalClosure S))
    -- But proj⁻¹(normalClosure S) = normalClosure (proj⁻¹(S))
    -- Actually, we want F / normalClosure (rels ∪ S')
    -- We know proj(S') = S.
    -- Let N' = normalClosure (rels ∪ S').
    -- We need to show that the kernel of the composition F → G → G / normalClosure S is N'.
    -- The map is φ : F → G / normalClosure S.
    -- ker φ = { w | proj(w) ∈ normalClosure S } = proj⁻¹(normalClosure S).
    -- We need to show proj⁻¹(normalClosure S) = normalClosure (rels ∪ S').
    -- We know ker proj = normalClosure rels.
    -- By the correspondence theorem, proj⁻¹(normalClosure S) = normalClosure (proj⁻¹(S) ∪ ker proj) = normalClosure (proj⁻¹(S) ∪ rels).
    -- We need to show normalClosure (proj⁻¹(S) ∪ rels) = normalClosure (S' ∪ rels).
    -- Since S' ⊆ proj⁻¹(S), normalClosure (S' ∪ rels) ⊆ normalClosure (proj⁻¹(S) ∪ rels).
    -- Conversely, let w ∈ proj⁻¹(S). Then proj(w) ∈ S.
    -- Since proj(S') = S, there exists w' ∈ S' such that proj(w') = proj(w).
    -- Then proj(w * w'⁻¹) = 1, so w * w'⁻¹ ∈ ker proj = normalClosure rels.
    -- So w = (w * w'⁻¹) * w' ∈ normalClosure rels * normalClosure S' ⊆ normalClosure (rels ∪ S').
    -- Thus proj⁻¹(S) ⊆ normalClosure (rels ∪ S').
    -- So normalClosure (proj⁻¹(S) ∪ rels) ⊆ normalClosure (rels ∪ S').
    -- Thus ker φ = normalClosure (rels ∪ S').
    -- So G / normalClosure S ≃ F / normalClosure (rels ∪ S') = PresentedGroup (rels ∪ S').
    have h_iso : Nonempty ((FreeGroup α ⧸ (Subgroup.normalClosure (rels ∪ S'))) ≃* (PresentedGroup rels ⧸ Subgroup.normalClosure S)) := by
      refine' ⟨ _ ⟩;
      -- By definition of normal closure, we know that $\langle\langle S \rangle\rangle = \pi(\langle\langle S' \rangle\rangle)$.
      have h_normal_closure : Subgroup.normalClosure S = Subgroup.map proj (Subgroup.normalClosure (rels ∪ S')) := by
        refine' le_antisymm _ _;
        · refine' sInf_le _;
          simp +decide [ Set.subset_def, Group.conjugatesOfSet ];
          rintro x y hy ⟨ g, hg ⟩;
          refine' ⟨ lift g * lift y * ( lift g ) ⁻¹, _, _ ⟩ <;> simp_all +decide [ SemiconjBy ];
          · refine' Subgroup.Normal.mem_comm inferInstance _;
            simp +decide [ ← mul_assoc, Subgroup.normalClosure ];
            exact Subgroup.subset_closure ( Group.subset_conjugatesOfSet <| Set.mem_union_right _ <| Set.mem_image_of_mem _ hy );
          · have := Function.surjInv_eq h_surj ( g : PresentedGroup rels ) ; have := Function.surjInv_eq h_surj y; aesop;
        · simp +decide [ Subgroup.map_le_iff_le_comap, Subgroup.normalClosure ];
          simp +decide [ Set.subset_def, Group.conjugatesOfSet ];
          simp +decide [ conjugatesOf ];
          rintro x y ( hy | ⟨ z, hz, rfl ⟩ ) w hw <;> simp_all +decide [ Subgroup.mem_closure ];
          · intro K hK; specialize hK; simp_all +decide [ ← hw, Set.subset_def ] ;
            convert K.one_mem using 1;
            erw [ QuotientGroup.eq_one_iff ];
            exact Subgroup.normalClosure_normal.conj_mem _ ( Subgroup.subset_normalClosure hy ) _;
          · intro K hK; specialize hK z hz; simp_all +decide [ Set.subset_def ] ;
            convert hK ( proj w ) using 1 ; simp +decide [ ← hw ];
            exact Function.surjInv_eq h_surj z;
      refine' MulEquiv.ofBijective ( QuotientGroup.lift _ _ _ ) ⟨ fun x y hxy => _, fun x => _ ⟩;
      exact QuotientGroup.mk' ( Subgroup.normalClosure S ) |> MonoidHom.comp <| proj;
      intro x hx;
      simp [h_normal_closure];
      exact ⟨ x, hx, rfl ⟩;
      · obtain ⟨ x, rfl ⟩ := QuotientGroup.mk_surjective x; obtain ⟨ y, rfl ⟩ := QuotientGroup.mk_surjective y; simp_all +decide [ QuotientGroup.eq ] ;
        obtain ⟨ z, hz, h ⟩ := hxy;
        have h_eq : x⁻¹ * y * z⁻¹ ∈ Subgroup.normalClosure rels := by
          have h_eq : proj (x⁻¹ * y * z⁻¹) = 1 := by
            simp +decide [ h, mul_assoc ];
          exact?;
        have h_eq : x⁻¹ * y * z⁻¹ ∈ Subgroup.normalClosure (rels ∪ S') := by
          exact Subgroup.normalClosure_mono ( Set.subset_union_left ) h_eq;
        simpa using Subgroup.mul_mem _ h_eq hz;
      · obtain ⟨ y, rfl ⟩ := QuotientGroup.mk_surjective x;
        obtain ⟨ x, rfl ⟩ := h_surj y;
        exact ⟨ QuotientGroup.mk x, rfl ⟩;
    exact ⟨ h_iso.some.symm ⟩

/-
The quotient of a finitely presented group by the normal closure of a finite set is finitely presented.
-/
lemma quotient_is_finitely_presented {G : Type u} [Group G] (hG : IsFinitelyPresentedGroup G) (S : Set G) (hS : S.Finite) :
    IsFinitelyPresentedGroup (G ⧸ Subgroup.normalClosure S) := by
      obtain ⟨ α, hα, rels, hrels, ⟨ f ⟩ ⟩ := hG;
      obtain ⟨ S', hS', ⟨ g ⟩ ⟩ := presented_group_quotient_iso_presented_group_add_rels rels ( f '' S ) ( hS.image f );
      -- Since $G$ is isomorphic to $G'$, the quotient $G / \langle\langle S \rangle\rangle$ is isomorphic to $G' / \langle\langle S' \rangle\rangle$.
      have h_iso : (G ⧸ Subgroup.normalClosure S) ≃* (PresentedGroup rels ⧸ Subgroup.normalClosure (f '' S)) := by
        refine' QuotientGroup.congr _ _ _ _;
        exact f;
        refine' le_antisymm _ _;
        · simp +decide [ Subgroup.map_le_iff_le_comap ];
          rw [ Subgroup.normalClosure ];
          simp +decide [ Subgroup.closure_le, Group.conjugatesOfSet ];
          simp +decide [ conjugatesOf, Set.subset_def ];
          exact fun i hi a => Subgroup.normalClosure_normal.conj_mem _ ( Subgroup.subset_normalClosure ( Set.mem_image_of_mem _ hi ) ) _;
        · simp +decide [ Subgroup.normalClosure ];
          simp +decide [ Set.subset_def, Group.conjugatesOfSet ];
          simp +decide [ conjugatesOf ];
          rintro x y hy z rfl;
          refine' ⟨ f.symm z * y * ( f.symm z ) ⁻¹, _, _ ⟩ <;> simp +decide [ Subgroup.mem_closure ];
          exact fun K hK => hK y hy ⟨ f.symm z, rfl ⟩;
      exact ⟨ α, hα, rels ∪ S', hrels.union hS', ⟨ h_iso.trans g ⟩ ⟩

/-
The normal closure of $R$ in $G$ is equal to the normal closure of the set of conjugates of $R$ by a transversal.
-/
lemma normal_closure_eq_normal_closure_schreier {G : Type u} [Group G] (K : Subgroup G)
    (R : Set G) (h : Subgroup.normalClosure R ≤ K) (T : Set G) (hT : T = Set.range (Quotient.out : G ⧸ K → G)) :
    let S_set := ⋃ t ∈ T, (fun r => t * r * t⁻¹) '' R
    Subgroup.normalClosure R = Subgroup.normalClosure S_set := by
  let S_set := ⋃ t ∈ T, (fun r => t * r * t⁻¹) '' R
  apply le_antisymm
  · -- normalClosure R ≤ normalClosure S_set
    -- R ⊆ S_set? No.
    -- But R ⊆ normalClosure S_set?
    -- 1 ∈ T (usually, but not guaranteed by Quotient.out).
    -- However, normalClosure S_set is normal in G.
    -- If we show R ⊆ normalClosure S_set, then normalClosure R ≤ normalClosure S_set.
    -- Let r ∈ R. We need r ∈ normalClosure S_set.
    -- We know 1 = k * t for some k ∈ K, t ∈ T.
    -- So t⁻¹ = k⁻¹.
    -- t * r * t⁻¹ ∈ S_set.
    -- r = t⁻¹ * (t * r * t⁻¹) * t = k⁻¹ * s * k.
    -- Since normalClosure S_set is normal, k⁻¹ * s * k ∈ normalClosure S_set.
    simp +decide [ Subgroup.normalClosure ];
    simp +decide [ Group.conjugatesOfSet ];
    intro r hr g hg; simp_all +decide [ conjugatesOf ] ;
    obtain ⟨ c, rfl ⟩ := hg;
    refine' Subgroup.subset_closure _;
    simp +decide [ ← mul_assoc ];
    refine' ⟨ QuotientGroup.mk c, r, hr, c * ( Quotient.out ( QuotientGroup.mk c ) ) ⁻¹, _ ⟩;
    exact K;
    group
  · -- normalClosure S_set ≤ normalClosure R
    -- S_set ⊆ normalClosure R?
    -- t * r * t⁻¹ is a conjugate of r.
    -- r ∈ R ⊆ normalClosure R.
    -- normalClosure R is normal, so it contains all conjugates.
    -- So S_set ⊆ normalClosure R.
    apply Subgroup.normalClosure_le_normal
    intro x hx
    simp [S_set] at hx
    obtain ⟨t, ht, r, hr, rfl⟩ := hx
    apply Subgroup.normalClosure_normal.conj_mem
    apply Subgroup.subset_normalClosure
    exact hr

/-
If every conjugate of an element of $R$ by an element of $G$ is a conjugate of an element of $S$ by an element of $K$, then the normal closure of $R$ in $G$ is contained in the normal closure of $S$ in $K$.
-/
lemma normal_closure_le_map_normal_closure_of_conjugates {G : Type u} [Group G] {K : Subgroup G}
    {R : Set G} {S : Set K}
    (h : ∀ (g : G) (r : R), ∃ (k : K) (s : S), g * r * g⁻¹ = k * s * k⁻¹) :
    Subgroup.normalClosure R ≤ (Subgroup.normalClosure S).map K.subtype := by
      rw [ Subgroup.normalClosure ];
      simp +decide [ Group.conjugatesOfSet ];
      intro r hr;
      simp +decide [ conjugatesOf, Set.subset_def ];
      intro g
      obtain ⟨k, s, hks⟩ := h g ⟨r, hr⟩;
      refine' ⟨ _, _ ⟩;
      convert K.mul_mem ( K.mul_mem k.2 s.1.2 ) ( K.inv_mem k.2 ) using 1;
      convert Subgroup.normalClosure_normal.conj_mem _ ( Subgroup.subset_normalClosure s.2 ) k using 1;
      exact Subtype.ext hks

/-
If elements of $S$ are in the normal closure of $R$, then the normal closure of $S$ in a subgroup is contained in the normal closure of $R$.
-/
lemma map_normal_closure_le_normal_closure {G : Type u} [Group G] {K : Subgroup G}
    {R : Set G} {S : Set K} (h : ∀ s ∈ S, (s : G) ∈ Subgroup.normalClosure R) :
    (Subgroup.normalClosure S).map K.subtype ≤ Subgroup.normalClosure R := by
  rw [Subgroup.map_le_iff_le_comap]
  apply Subgroup.normalClosure_le_normal
  intro s hs
  exact h s hs

/-
Isomorphic groups share the property of being finitely presented.
-/
lemma isFinitelyPresentedGroup_of_iso {G H : Type u} [Group G] [Group H] (h : G ≃* H) (hH : IsFinitelyPresentedGroup H) : IsFinitelyPresentedGroup G := by
  rcases hH with ⟨α, hα, rels, hrels, ⟨iso⟩⟩
  use α, hα, rels, hrels
  exact ⟨h.trans iso⟩

/-
The normal closure of relations in the free group is equal to the normal closure of the Reidemeister-Schreier relations in the subgroup.
-/
lemma reidemeister_schreier_normal_closure_eq
  {α : Type u}
  (rels : Set (FreeGroup α))
  (L : Subgroup (FreeGroup α))
  (hR_le_L : Subgroup.normalClosure rels ≤ L)
  (T : Set (FreeGroup α))
  (hT : T = Set.range (Quotient.out : FreeGroup α ⧸ L → FreeGroup α))
  (S_set : Set (FreeGroup α))
  (hS_set : S_set = ⋃ t ∈ T, ⋃ r ∈ rels, {t⁻¹ * r * t}) :
  Subgroup.normalClosure rels = (Subgroup.normalClosure (L.subtype ⁻¹' S_set)).map L.subtype := by
    refine' le_antisymm _ _ <;> simp_all +decide [ Subgroup.map_commutator, Subgroup.normalClosure ];
    · intro x hx
      obtain ⟨g, r, hr⟩ : ∃ g : FreeGroup α, ∃ r ∈ rels, x = g * r * g⁻¹ := by
        simp_all +decide [ Group.conjugatesOfSet ];
        rcases hx with ⟨ r, hr, hx ⟩ ; rw [ conjugatesOf ] at hx; aesop;
      generalize_proofs at *; (
      obtain ⟨l, t, hl, ht, rfl⟩ : ∃ l ∈ L, ∃ t ∈ T, g = l * t⁻¹ := by
        obtain ⟨t, ht⟩ : ∃ t ∈ T, g * t ∈ L := by
          simp_all +decide [ Set.range, QuotientGroup.eq ];
          have h_exists_a : ∀ g : FreeGroup α, ∃ a : FreeGroup α ⧸ L, g * a.out ∈ L := by
            intro g
            set a : FreeGroup α ⧸ L := QuotientGroup.mk g⁻¹
            use a
            generalize_proofs at *; (
            have := QuotientGroup.eq.1 ( Quotient.out_eq' a ) ; simp_all +decide [ mul_assoc, Subgroup.mul_mem_cancel_left, Subgroup.mul_mem_cancel_right ] ;
            simpa [ mul_assoc ] using L.inv_mem this |> L.mul_mem <| L.one_mem;)
          generalize_proofs at *; (
          exact Exists.elim ( h_exists_a g ) fun a ha => ⟨ a, ha ⟩)
        generalize_proofs at *; (
        exact ⟨ g * t, ht.2, t, ht.1, by group ⟩)
      generalize_proofs at *; (
      simp_all +decide [ Group.conjugatesOfSet, Set.subset_def ];
      refine' ⟨ _, Subgroup.subset_closure _ ⟩
      generalize_proofs at *; (
      grind);
      obtain ⟨ y, rfl ⟩ := ht; simp +decide [ conjugatesOf ] ;
      refine' ⟨ _, _, r, ⟨ y, rfl ⟩, hr.1, l, t, _ ⟩ ; simp +decide [ mul_assoc ];
      convert hR_le_L _ _ hr.1 _ using 1
      generalize_proofs at *; (
      simp +decide [ conjugatesOf ];
      exact ⟨ y.out⁻¹, by group ⟩);
      exact Subtype.ext ( by simp +decide [ mul_assoc ] )));
    · simp_all +decide [ Set.subset_def, Group.conjugatesOfSet ];
      simp +decide [ Subgroup.map_le_iff_le_comap, Subgroup.closure_le, Set.subset_def ];
      simp +decide [ conjugatesOf, Subgroup.mem_subgroupOf ];
      rintro a ha x hx y z rfl hy u hu h; simp_all +decide [ Subtype.ext_iff ] ;
      exact h.symm ▸ Subgroup.subset_closure ( Set.mem_iUnion₂.mpr ⟨ y, hy, u * z.out⁻¹, by group ⟩ )

/-
A finite index subgroup of a finitely presented group is finitely presented.
-/
theorem finitely_presented_of_finite_index {G : Type u} [Group G] (hG : IsFinitelyPresentedGroup G) (H : Subgroup G) [H.FiniteIndex] :
    IsFinitelyPresentedGroup H := by
      obtain ⟨ α, hα, rels, hrels, ⟨ ϕ ⟩ ⟩ := hG;
      -- Let $H'$ be the image of $H$ under $\phi$. Since $G \cong \text{PresentedGroup } rels$, $H \cong H'$, so it suffices to show $H'$ is finitely presented.
      set H' := Subgroup.map ϕ.toMonoidHom H with hH'
      have hH'_iso : H ≃* H' := by
        refine' { Equiv.ofBijective ( fun x => ⟨ ϕ x, Subgroup.mem_map_of_mem _ x.2 ⟩ ) ⟨ fun x y hxy => _, fun x => _ ⟩ with .. } <;> aesop;
      -- Let $K = \pi^{-1}(H')$. Then $K$ is a subgroup of $FreeGroup \alpha$ containing $N$.
      set K := Subgroup.comap (QuotientGroup.mk' (Subgroup.normalClosure rels)) H' with hK
      have hK_cont_N : Subgroup.normalClosure rels ≤ K := by
        intro x hx;
        refine' ⟨ 1, H.one_mem, _ ⟩ ; simp +decide [ hx ];
        exact QuotientGroup.eq.mpr ( by simpa using Subgroup.subset_normalClosure hx );
      -- Since $K$ is a finite index subgroup of $FreeGroup \alpha$, it is finitely presented.
      have hK_fg : IsFinitelyPresentedGroup K := by
        have hK_finite_index : K.FiniteIndex := by
          have hK_finite_index : H'.FiniteIndex := by
            constructor <;> intro h <;> rw [ Subgroup.finiteIndex_iff ] at * <;> aesop;
          convert hK_finite_index using 1;
          constructor <;> intro h <;> have := hK_finite_index <;> simp_all +decide [ Subgroup.finiteIndex_iff ];
          rw [ Subgroup.index_comap ] ; aesop;
        exact?;
      -- Since $H' \cong K / N$, we need to show $N$ is the normal closure of a finite set in $K$.
      have hN_finite : ∃ S : Set K, S.Finite ∧ Subgroup.normalClosure S = Subgroup.comap (Subgroup.subtype K) (Subgroup.normalClosure rels) := by
        -- By the Reidemeister-Schreier rewriting process, $N$ (as a normal subgroup of $FreeGroup \alpha$ generated by $rels$) is generated as a normal subgroup of $K$ by a set $S'$.
        obtain ⟨S', hS'_finite, hS'_gen⟩ : ∃ S' : Set (FreeGroup α), S'.Finite ∧ Subgroup.normalClosure rels = (Subgroup.normalClosure (K.subtype ⁻¹' S')).map K.subtype := by
          have := reidemeister_schreier_normal_closure_eq rels K hK_cont_N;
          refine' ⟨ _, _, this _ rfl _ rfl ⟩;
          refine' Set.Finite.biUnion _ _;
          · have h_quotient_finite : Finite (FreeGroup α ⧸ K) := by
              have h_quotient_finite : Finite (PresentedGroup rels ⧸ H') := by
                have h_quotient_finite : Finite (PresentedGroup rels ⧸ H') := by
                  have h_iso : (G ⧸ H) ≃ (PresentedGroup rels ⧸ H') := by
                    refine' Equiv.ofBijective ( fun x => Quotient.map' ( fun y => ϕ y ) ( fun y z h => _ ) x ) ⟨ fun x y h => _, fun x => _ ⟩;
                    all_goals simp_all +decide [ QuotientGroup.leftRel_apply, Subgroup.mem_map ];
                    exact ⟨ y⁻¹ * z, h, by simp +decide [ ϕ.map_mul, ϕ.map_inv ] ⟩;
                    · obtain ⟨ x, rfl ⟩ := QuotientGroup.mk_surjective x; obtain ⟨ y, rfl ⟩ := QuotientGroup.mk_surjective y; simp +decide [ QuotientGroup.eq ] at h ⊢;
                      obtain ⟨ z, hz, hz' ⟩ := Subgroup.mem_map.mp h; simp_all +decide [ ← map_mul, ← map_inv ] ;
                    · obtain ⟨ y, rfl ⟩ := Quotient.exists_rep x; exact ⟨ Quotient.mk'' ( ϕ.symm y ), by simp +decide ⟩ ;
                  exact Finite.of_equiv _ h_iso;
                exact h_quotient_finite;
              have h_quotient_finite : Nonempty (FreeGroup α ⧸ K ≃ (PresentedGroup rels ⧸ H')) := by
                refine' ⟨ _ ⟩;
                refine' Equiv.ofBijective ( fun x => Quotient.map' ( fun y => Quotient.mk'' y ) ( fun y z h => _ ) x ) ⟨ fun x y h => _, fun x => _ ⟩;
                all_goals norm_num [ QuotientGroup.leftRel_apply ] at *;
                exact?;
                · obtain ⟨ x, rfl ⟩ := QuotientGroup.mk_surjective x; obtain ⟨ y, rfl ⟩ := QuotientGroup.mk_surjective y; simp +decide [ QuotientGroup.eq ] at h ⊢;
                  exact?;
                · obtain ⟨ y, rfl ⟩ := Quotient.exists_rep x;
                  obtain ⟨ x, rfl ⟩ := QuotientGroup.mk_surjective y;
                  exact ⟨ ⟦x⟧, rfl ⟩;
              exact Finite.of_equiv _ h_quotient_finite.some.symm;
            exact Set.toFinite _;
          · exact fun x hx => Set.Finite.biUnion hrels fun y hy => Set.finite_singleton _;
        refine' ⟨ _, _, _ ⟩;
        exact K.subtype ⁻¹' S';
        · exact Set.Finite.subset ( hS'_finite.preimage fun x => by aesop ) fun x hx => hx;
        · simp +decide [ hS'_gen, Subgroup.comap_map_eq_self ];
      -- Since $H' \cong K / N$, we need to show $N$ is the normal closure of a finite set in $K$. Use the fact that $N$ is the normal closure of a finite set in $K$.
      obtain ⟨ S, hS_finite, hS_normal_closure ⟩ := hN_finite;
      have hH'_iso_K_N : H' ≃* K ⧸ Subgroup.normalClosure S := by
        have hH'_iso_K_N : H' ≃* K ⧸ (Subgroup.comap (Subgroup.subtype K) (Subgroup.normalClosure rels)) := by
          have h_iso : K ⧸ (Subgroup.comap (Subgroup.subtype K) (Subgroup.normalClosure rels)) ≃* H' := by
            refine' MulEquiv.ofBijective ( QuotientGroup.lift _ _ _ ) ⟨ _, _ ⟩;
            refine' MonoidHom.codRestrict _ _ _;
            exact QuotientGroup.mk' ( Subgroup.normalClosure rels ) |> MonoidHom.comp <| Subgroup.subtype K;
            exact fun x => x.2;
            all_goals simp +decide [ Function.Injective, Function.Surjective ];
            all_goals norm_num [ SetLike.le_def, Subgroup.mem_subgroupOf ];
            exact fun a ha ha' => QuotientGroup.eq.mpr <| by simpa using ha';
            · intro a₁ a₂ h; obtain ⟨ x₁, rfl ⟩ := QuotientGroup.mk_surjective a₁; obtain ⟨ x₂, rfl ⟩ := QuotientGroup.mk_surjective a₂; simp_all +decide [ QuotientGroup.eq ] ;
              erw [ QuotientGroup.eq ] at h ; aesop;
            · intro a ha;
              obtain ⟨ x, hx ⟩ := QuotientGroup.mk_surjective a;
              refine' ⟨ QuotientGroup.mk ⟨ x, _ ⟩, _ ⟩ <;> aesop
          exact h_iso.symm;
        convert hH'_iso_K_N using 1;
        grind;
      have hH'_fg : IsFinitelyPresentedGroup (K ⧸ Subgroup.normalClosure S) := by
        exact?;
      obtain ⟨ α, hα, rels, hrels, ⟨ ϕ ⟩ ⟩ := hH'_fg;
      exact ⟨ α, hα, rels, hrels, ⟨ hH'_iso.trans ( hH'_iso_K_N.trans ϕ ) ⟩ ⟩
