/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ee184b13-3f8c-4a75-ba34-330eb5e05406

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove the existence of a continuous surjection from the real line to the plane (a space-filling curve).
The construction involves:
1.  Defining a surjective map `peano_map_surj` from `[0, 1]` to `[0, 1] × [0, 1]` using the Cantor function and a retraction.
2.  Scaling and translating this map to cover larger squares `[-n-1, n+1] × [-n-1, n+1]`.
3.  Stitching these maps together to form a global map `global_peano_surj` from `ℝ` to `ℝ × ℝ`.
4.  Proving that `global_peano_surj` is continuous and surjective.
The main theorem is `exists_continuous_surjection_R_R2`.
-/

/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 8d9d884b-9f37-458d-a7e4-a1051c669df3

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The Cantor space (functions from N to Bool) is homeomorphic to its square.
-/
def cantor_square_homeomorph : (ℕ → Bool) ≃ₜ (ℕ → Bool) × (ℕ → Bool) :=
  (Homeomorph.piCongrLeft Equiv.natSumNatEquivNat).symm.trans Homeomorph.sumArrowHomeomorphProdArrow

/-
The Cantor function is continuous.
-/
lemma continuous_cantorFunction {c : ℝ} (hc : 0 ≤ c) (hc' : c < 1) : Continuous (Cardinal.cantorFunction c) := by
  refine' continuous_iff_continuousAt.mpr _;
  intro x
  unfold Cardinal.cantorFunction
  simp [ContinuousAt];
  -- Since $c < 1$, the series $\sum_{n=0}^{\infty} c^n$ converges.
  have h_series_conv : Summable (fun n => c^n) := by
    exact summable_geometric_of_lt_one hc hc';
  refine' ( tendsto_tsum_of_dominated_convergence _ _ _ );
  use fun n => c ^ n;
  · exact h_series_conv;
  · intro k; induction' k with k ih <;> simp_all +decide [ Cardinal.cantorFunctionAux ];
    · exact tendsto_const_nhds.congr' ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_iff.mpr <| isClosed_eq ( continuous_apply 0 ) continuous_const ) <| show x 0 ≠ Bool.not ( x 0 ) from by cases x 0 <;> simp +decide ] with y hy ; aesop );
    · by_cases h : x ( k + 1 ) <;> simp +decide [ h ];
      · exact tendsto_const_nhds.congr' ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_ne.preimage ( continuous_apply ( k + 1 ) ) ) ( show x ( k + 1 ) ≠ Bool.false by aesop ) ] with y hy; aesop );
      · exact tendsto_const_nhds.congr' ( by filter_upwards [ IsOpen.mem_nhds ( isOpen_compl_iff.mpr <| isClosed_eq ( continuous_apply ( k + 1 ) ) continuous_const ) h ] with y hy; aesop );
  · simp +decide [ Cardinal.cantorFunctionAux ];
    exact Filter.Eventually.of_forall fun n k => by cases n k <;> simp +decide [ *, abs_of_nonneg ] ;

/-
The Cantor function with parameter 1/2 maps the Cantor space surjectively onto [0, 2].
-/
lemma surjOn_cantorFunction_two : Set.SurjOn (Cardinal.cantorFunction (1/2)) Set.univ (Set.Icc 0 2) := by
  unfold Cardinal.cantorFunction;
  -- We'll use the fact that every number in [0, 2] can be represented as a binary fraction.
  intro x hx
  obtain ⟨f, hf⟩ : ∃ f : ℕ → Bool, ∑' n, (if f n then (1 / 2 : ℝ) ^ (n + 1) else 0) = x / 2 := by
    -- By definition of binary representation, we can find such a function $f$.
    have h_binary : ∃ f : ℕ → ℕ, (∀ n, f n < 2) ∧ (∑' n, (f n : ℝ) / 2 ^ (n + 1)) = x / 2 := by
      have h_binary : ∀ y : ℝ, 0 ≤ y → y < 1 → ∃ f : ℕ → ℕ, (∀ n, f n < 2) ∧ (∑' n, (f n : ℝ) / 2 ^ (n + 1)) = y := by
        intro y hy₁ hy₂
        set f : ℕ → ℕ := fun n => Nat.floor (2^(n+1) * y) - 2 * Nat.floor (2^n * y) with hf_def
        have hf_bounds : ∀ n, f n < 2 := by
          intro n; rw [ tsub_lt_iff_left ] <;> norm_num [ pow_succ', mul_assoc ];
          · rw [ Nat.floor_lt ] <;> norm_num <;> nlinarith [ Nat.lt_floor_add_one ( 2 ^ n * y ), pow_pos ( zero_lt_two' ℝ ) n ];
          · exact Nat.le_floor <| by push_cast; linarith [ Nat.floor_le <| show 0 ≤ 2 ^ n * y by positivity ] ;
        have hf_sum : ∑' n, (f n : ℝ) / 2^(n+1) = y := by
          have hf_sum : ∀ N, ∑ n ∈ Finset.range N, (f n : ℝ) / 2^(n+1) = (Nat.floor (2^N * y) : ℝ) / 2^N := by
            intro N; induction N <;> simp_all +decide [ Finset.sum_range_succ, pow_succ' ] ; ring;
            · exact_mod_cast Eq.symm ( Nat.floor_eq_zero.mpr hy₂ );
            · rw [ Nat.cast_sub ] <;> push_cast <;> ring;
              exact Nat.le_floor <| by push_cast; linarith [ Nat.floor_le ( show 0 ≤ y * 2 ^ ‹_› by positivity ) ] ;
          -- By definition of $f$, we know that $\frac{\lfloor 2^N y \rfloor}{2^N}$ converges to $y$ as $N$ tends to infinity.
          have hf_conv : Filter.Tendsto (fun N => (Nat.floor (2^N * y) : ℝ) / 2^N) Filter.atTop (nhds y) := by
            refine' ( tendsto_iff_norm_sub_tendsto_zero.mpr _ );
            norm_num [ div_sub' ];
            exact squeeze_zero ( fun _ => div_nonneg ( abs_nonneg _ ) ( pow_nonneg zero_le_two _ ) ) ( fun e => div_le_div_of_nonneg_right ( show |↑⌊2 ^ e * y⌋₊ - 2 ^ e * y| ≤ 1 by erw [ abs_le ] ; constructor <;> linarith [ Nat.floor_le ( show 0 ≤ 2 ^ e * y by positivity ), Nat.lt_floor_add_one ( 2 ^ e * y ) ] ) ( pow_nonneg zero_le_two _ ) ) ( tendsto_const_nhds.div_atTop ( tendsto_pow_atTop_atTop_of_one_lt one_lt_two ) );
          refine' HasSum.tsum_eq _;
          rw [ hasSum_iff_tendsto_nat_of_nonneg fun n => div_nonneg ( Nat.cast_nonneg _ ) ( pow_nonneg ( by norm_num ) _ ) ] ; aesop
        use f, hf_bounds, hf_sum;
      by_cases hx' : x = 2;
      · use fun n => 1; norm_num [ hx' ];
        ring_nf; rw [ tsum_mul_right, tsum_geometric_of_lt_one ] <;> norm_num;
      · exact h_binary _ ( div_nonneg hx.1 zero_le_two ) ( by contrapose! hx'; linarith [ hx.2 ] );
    obtain ⟨ f, hf₁, hf₂ ⟩ := h_binary; use fun n => f n = 1; simp_all +decide [ div_eq_mul_inv ] ;
    exact Eq.trans ( tsum_congr fun n => by specialize hf₁ n; interval_cases f n <;> norm_num ) hf₂;
  convert Set.mem_image_of_mem _ ( Set.mem_univ f ) using 1;
  convert congr_arg ( · * 2 ) hf.symm using 1 ; ring;
  rw [ ← tsum_mul_right ] ; congr ; ext n ; norm_num [ Cardinal.cantorFunctionAux ] ; ring

/-
The Cantor surjection maps a sequence of booleans to a point in the unit square.
-/
def cantor_surjection (x : ℕ → Bool) : ℝ × ℝ :=
  let (y, z) := cantor_square_homeomorph x
  (Cardinal.cantorFunction (1/2) y / 2, Cardinal.cantorFunction (1/2) z / 2)

/-
The Cantor surjection is a continuous function.
-/
lemma continuous_cantor_surjection : Continuous cantor_surjection := by
  apply_rules [ Continuous.prodMk, Continuous.div_const, continuous_const ];
  · exact continuous_cantorFunction ( by norm_num ) ( by norm_num ) |> Continuous.comp <| by continuity;
  · exact Continuous.comp ( continuous_cantorFunction ( by norm_num ) ( by norm_num ) ) ( by continuity )

/-
The scaled Cantor function maps surjectively to the unit interval.
-/
lemma surjOn_cantorFunction_half_scaled : Set.SurjOn (fun x => Cardinal.cantorFunction (1/2) x / 2) Set.univ (Set.Icc 0 1) := by
  intro x hx;
  obtain ⟨y, hy⟩ : ∃ y : ℕ → Bool, Cardinal.cantorFunction (1/2) y = 2 * x := by
    have := surjOn_cantorFunction_two;
    exact this ( Set.mem_Icc.mpr ⟨ by linarith [ hx.1 ], by linarith [ hx.2 ] ⟩ ) |> fun ⟨ y, hy ⟩ => ⟨ y, hy.2 ⟩;
  exact ⟨ y, by aesop ⟩

/-
The Cantor surjection maps the Cantor space surjectively onto the unit square.
-/
lemma surjOn_cantor_surjection : Set.SurjOn cantor_surjection Set.univ (Set.prod (Set.Icc 0 1) (Set.Icc 0 1)) := by
  intro p hp;
  obtain ⟨y, hy⟩ : ∃ y : ℕ → Bool, Cardinal.cantorFunction (1/2) y / 2 = p.1 := by
    exact surjOn_cantorFunction_half_scaled ( Set.mem_Icc.mpr ⟨ hp.1.1, hp.1.2 ⟩ ) |> fun ⟨ y, hy ⟩ => ⟨ y, hy.2 ⟩
  obtain ⟨z, hz⟩ : ∃ z : ℕ → Bool, Cardinal.cantorFunction (1/2) z / 2 = p.2 := by
    have := surjOn_cantorFunction_half_scaled;
    exact this ( Set.mem_Icc.mpr hp.2 ) |> fun ⟨ z, hz ⟩ => ⟨ z, hz.2 ⟩;
  obtain ⟨x, hx⟩ : ∃ x : ℕ → Bool, cantor_square_homeomorph x = (y, z) := by
    exact Homeomorph.surjective _ _;
  exact ⟨ x, Set.mem_univ _, by unfold cantor_surjection; aesop ⟩

/-
The Cantor function with parameter 1/3 is a closed embedding.
-/
lemma closedEmbedding_cantorFunction_third : Topology.IsClosedEmbedding (Cardinal.cantorFunction (1/3)) := by
  apply_rules [ Continuous.isClosedEmbedding ];
  · apply continuous_cantorFunction; norm_num; norm_num;
  · -- The Cantor function with parameter $c = \frac{1}{3}$ is injective.
    apply Cardinal.cantorFunction_injective; norm_num;
    norm_num [ ENNReal.div_lt_iff ]

/-
There exists a continuous function from the reals to the plane that extends the Cantor surjection.
-/
lemma exists_extension_cantor_surjection : ∃ F : ℝ → ℝ × ℝ, Continuous F ∧ ∀ x : ℕ → Bool, F (Cardinal.cantorFunction (1/3) x) = cantor_surjection x := by
  have := @ContinuousMap.exists_extension;
  specialize this ( show Topology.IsClosedEmbedding ( Cardinal.cantorFunction ( 1 / 3 ) ) from by
                      exact? ) ( ContinuousMap.mk ( cantor_surjection ) <| by
                      exact? );
  exact ⟨ _, this.choose.continuous, fun x => congr_arg ( fun f => f x ) this.choose_spec ⟩

/-
The retraction function maps any real number to the unit interval [0, 1].
-/
def retraction_Icc (x : ℝ) : Set.Icc (0 : ℝ) 1 := ⟨min (max x 0) 1, by
  constructor
  · apply le_min;
    · apply le_max_right
    · norm_num
  · apply min_le_right
⟩

/-
The retraction function is continuous.
-/
lemma continuous_retraction_Icc : Continuous retraction_Icc := by
  apply Continuous.subtype_mk;
  fun_prop

/-
The Cantor extension is a continuous function that agrees with the Cantor surjection on the Cantor set.
-/
noncomputable def cantor_extension : ℝ → ℝ × ℝ := Classical.choose exists_extension_cantor_surjection

lemma continuous_cantor_extension : Continuous cantor_extension := (Classical.choose_spec exists_extension_cantor_surjection).1

lemma cantor_extension_extends (x : ℕ → Bool) : cantor_extension (Cardinal.cantorFunction (1/3) x) = cantor_surjection x := (Classical.choose_spec exists_extension_cantor_surjection).2 x

/-
The Peano map is a function from the unit interval to the unit square.
-/
def peano_map (x : Set.Icc (0 : ℝ) 1) : Set.Icc (0 : ℝ) 1 × Set.Icc (0 : ℝ) 1 :=
  let (u, v) := cantor_extension x
  (retraction_Icc u, retraction_Icc v)

/-
The scaled Peano map transforms the unit interval to a larger square.
-/
def peano_on_square (n : ℕ) (t : ℝ) : ℝ × ℝ :=
  let (u, v) := peano_map (retraction_Icc t)
  let s := (2 * n + 2 : ℝ)
  (s * u - (n + 1), s * v - (n + 1))

/-
The scaled Peano map is continuous.
-/
lemma continuous_peano_on_square (n : ℕ) : Continuous (peano_on_square n) := by
  apply_rules [ Continuous.prodMk, Continuous.mul, Continuous.sub, continuous_const ];
  · apply_rules [ Continuous.min, Continuous.max, continuous_const, continuous_id ];
    apply_rules [ Continuous.fst, continuous_const ];
    apply_rules [ Continuous.comp, continuous_retraction_Icc ];
    any_goals continuity;
    · exact Classical.choose_spec exists_extension_cantor_surjection |>.1;
    · exact Continuous.subtype_val continuous_retraction_Icc;
  · refine' continuous_subtype_val.comp _;
    refine' continuous_retraction_Icc.comp _;
    exact Continuous.snd ( Classical.choose_spec exists_extension_cantor_surjection |>.1.comp ( continuous_subtype_val.comp continuous_retraction_Icc ) )

/-
The Peano map is continuous.
-/
lemma continuous_peano_map : Continuous peano_map := by
  exact Continuous.prodMk ( continuous_retraction_Icc.comp <| continuous_fst.comp <| continuous_cantor_extension.comp <| continuous_subtype_val ) ( continuous_retraction_Icc.comp <| continuous_snd.comp <| continuous_cantor_extension.comp <| continuous_subtype_val )

/-
If x is in [0, 1], then the retraction of x is x.
-/
lemma retraction_Icc_val_eq_self {x : ℝ} (h : x ∈ Set.Icc 0 1) : (retraction_Icc x).val = x := by
  unfold retraction_Icc; aesop

#print Cardinal.cantorFunction

/-
A line segment between two points in the plane.
-/
def segment_R2 (a b : ℝ × ℝ) (t : ℝ) : ℝ × ℝ :=
  ((1 - t) * a.1 + t * b.1, (1 - t) * a.2 + t * b.2)

/-
An extended Peano map defined on the whole real line.
-/
def peano_extended (t : ℝ) : ℝ × ℝ :=
  let (u, v) := cantor_extension t
  (retraction_Icc u, retraction_Icc v)

lemma continuous_peano_extended : Continuous peano_extended := by
  apply_rules [ Continuous.prodMk, continuous_retraction_Icc ];
  · apply_rules [ Continuous.min, Continuous.max, continuous_id, continuous_const ];
    exact continuous_fst.comp ( Classical.choose_spec exists_extension_cantor_surjection |>.1 );
  · convert continuous_subtype_val.comp ( continuous_retraction_Icc.comp ( continuous_snd.comp ( Classical.choose_spec exists_extension_cantor_surjection |>.1 ) ) ) using 1

/-
The extended Peano map is surjective onto the unit square when restricted to [0, 1.5].
-/
lemma surjective_peano_extended_on_Icc : Set.SurjOn peano_extended (Set.Icc 0 1.5) (Set.prod (Set.Icc 0 1) (Set.Icc 0 1)) := by
  intro y hy;
  -- By definition of $cantor\_surjection$, there exists $x \in C$ such that $cantor\_surjection(x) = y$.
  obtain ⟨x, hx⟩ : ∃ x : ℕ → Bool, cantor_surjection x = y := by
    have := surjOn_cantor_surjection;
    exact this ( Set.mem_prod.mpr hy ) |> Exists.imp fun x hx => hx.2;
  -- By definition of $cantor\_extension$, we know that $cantor\_extension (cantorFunction (1/3) x) = cantor\_surjection x$.
  have h_cantor_extension : cantor_extension (Cardinal.cantorFunction (1/3) x) = y := by
    rw [ ← hx, cantor_extension_extends ];
  -- By definition of $cantor\_function$, we know that $cantorFunction (1/3) x \in [0, 1.5]$.
  have h_cantorFunction_range : Cardinal.cantorFunction (1 / 3) x ∈ Set.Icc 0 1.5 := by
    norm_num [ Cardinal.cantorFunction ];
    unfold Cardinal.cantorFunctionAux ; ring ; norm_num;
    refine' ⟨ tsum_nonneg fun n => _, _ ⟩;
    · cases x n <;> norm_num;
    · refine' le_trans ( Summable.tsum_le_tsum _ _ _ ) _;
      use fun n => ( 1 / 3 ) ^ n;
      · intro i; cases x i <;> norm_num;
      · exact Summable.of_nonneg_of_le ( fun n => by cases x n <;> norm_num ) ( fun n => by cases x n <;> norm_num ) ( summable_geometric_of_lt_one ( by norm_num ) ( by norm_num : ( 1 : ℝ ) / 3 < 1 ) );
      · exact summable_geometric_of_lt_one ( by norm_num ) ( by norm_num );
      · rw [ tsum_geometric_of_lt_one ] <;> norm_num;
  refine' ⟨ _, h_cantorFunction_range, _ ⟩;
  unfold peano_extended;
  rw [ h_cantor_extension ];
  exact Prod.ext ( retraction_Icc_val_eq_self hy.1 ) ( retraction_Icc_val_eq_self hy.2 )

/-
Check if peano_on_square is defined.
-/
#check peano_on_square

/-
A piece of the global Peano curve, defined for t in [0, 2]. It traverses the n-th square for t in [0, 1] and connects to the (n+1)-th square for t in [1, 2].
-/
def piece (n : ℕ) (t : ℝ) : ℝ × ℝ :=
  if t ≤ 1 then peano_on_square n t
  else segment_R2 (peano_on_square n 1) (peano_on_square (n + 1) 0) (t - 1)

/-
A global Peano curve mapping the real line to the plane. It is constructed by stitching together scaled Peano curves on expanding squares.
-/
def global_peano (t : ℝ) : ℝ × ℝ :=
  if t ≤ 0 then peano_on_square 0 0
  else
    let n := Nat.floor (t / 2)
    let rem := t - 2 * n
    piece n rem

/-
Check if continuous_peano_on_square is available.
-/
#check continuous_peano_on_square

/-
The segment function is continuous in its parameter t.
-/
lemma continuous_segment_R2 (a b : ℝ × ℝ) : Continuous (segment_R2 a b) := by
  exact Continuous.prodMk ( by continuity ) ( by continuity )

/-
The piece function is continuous.
-/
lemma continuous_piece (n : ℕ) : Continuous (piece n) := by
  refine' Continuous.if _ _ _;
  · erw [ frontier_Iic ] ; norm_num [ segment_R2 ];
  · exact?;
  · exact continuous_segment_R2 _ _ |> Continuous.comp <| continuous_sub_right _

/-
The global Peano map is continuous.
-/
lemma continuous_global_peano : Continuous global_peano := by
  -- We'll use the fact that if the function is continuous on each interval and the limits match at the endpoints, then the function is continuous.
  have h_cont : ∀ n : ℕ, ContinuousOn global_peano (Set.Icc (2 * n : ℝ) (2 * n + 2)) := by
    intro n;
    -- By definition of `global_peano`, it is equal to `piece n` on the interval `[2 * n, 2 * n + 2]`.
    have h_eq_piece : ∀ t ∈ Set.Icc (2 * n : ℝ) (2 * n + 2), global_peano t = piece n (t - 2 * n) := by
      intro t ht
      simp [global_peano, piece];
      have h_floor : ⌊t / 2⌋₊ = n ∨ ⌊t / 2⌋₊ = n + 1 := by
        exact Classical.or_iff_not_imp_left.2 fun h => le_antisymm ( Nat.le_of_lt_succ <| by rw [ Nat.floor_lt' ] <;> norm_num ; linarith [ ht.1, ht.2 ] ) ( Nat.succ_le_of_lt <| Nat.lt_of_le_of_ne ( Nat.le_floor <| by linarith [ ht.1, ht.2 ] ) <| Ne.symm h );
      cases h_floor <;> simp_all +decide [ Nat.floor_eq_iff ];
      · intro h; norm_num [ show t = 0 by linarith ] at *;
        norm_num [ ← ‹0 = n› ];
      · rw [ Nat.floor_eq_iff ] at * <;> norm_num at * <;> try linarith;
        split_ifs <;> try linarith;
        norm_num [ show t = 2 * n + 2 by linarith ] at *;
        unfold peano_on_square segment_R2; ring;
    exact ContinuousOn.congr ( by exact Continuous.continuousOn ( by exact continuous_piece n |> Continuous.comp <| by continuity ) ) h_eq_piece;
  refine' continuous_iff_continuousAt.mpr _;
  intro x
  by_cases hx : x ≤ 0;
  · by_cases hx' : x = 0;
    · rw [ Metric.continuousAt_iff ];
      intro ε hε;
      obtain ⟨ δ, hδ, H ⟩ := Metric.continuousOn_iff.mp ( h_cont 0 ) 0 ( by norm_num ) ε hε;
      use Min.min δ 1;
      simp +zetaDelta at *;
      refine' ⟨ hδ, fun y hy₁ hy₂ => _ ⟩;
      by_cases hy₃ : y ≤ 0;
      · unfold global_peano; aesop;
      · simpa [ hx' ] using H y ( by linarith ) ( by linarith [ abs_lt.mp hy₂ ] ) ( by simpa [ hx' ] using hy₁ );
    · exact ContinuousAt.congr ( show ContinuousAt ( fun t => peano_on_square 0 0 ) x from continuousAt_const ) ( Filter.EventuallyEq.symm <| Filter.eventuallyEq_of_mem ( Iio_mem_nhds <| lt_of_le_of_ne hx hx' ) fun t ht => if_pos ht.out.le );
  · obtain ⟨n, hn⟩ : ∃ n : ℕ, x ∈ Set.Ioo (2 * n : ℝ) (2 * n + 2) ∨ x = 2 * n + 2 := by
      field_simp;
      by_cases hx' : ∃ n : ℕ, x = 2 * (n + 1);
      · aesop;
      · exact ⟨ ⌊x / 2⌋₊, Or.inl ⟨ lt_of_le_of_ne ( by linarith [ Nat.floor_le ( show 0 ≤ x / 2 by linarith ) ] ) fun h => hx' ⟨ ⌊x / 2⌋₊ - 1, by cases n : ⌊x / 2⌋₊ <;> aesop ⟩, by linarith [ Nat.lt_floor_add_one ( x / 2 ) ] ⟩ ⟩;
    cases hn;
    · exact h_cont n |> ContinuousOn.continuousAt <| Icc_mem_nhds ( by linarith [ Set.mem_Ioo.mp ‹_› ] ) ( by linarith [ Set.mem_Ioo.mp ‹_› ] );
    · have h_cont_at : ContinuousAt global_peano (2 * n + 2) := by
        have h_left : ContinuousWithinAt global_peano (Set.Iio (2 * n + 2)) (2 * n + 2) := by
          have := h_cont n;
          have := this.continuousWithinAt ( show ( 2 * n + 2 : ℝ ) ∈ Set.Icc ( 2 * n : ℝ ) ( 2 * n + 2 ) by constructor <;> linarith );
          simp_all +decide [ ContinuousWithinAt ];
          exact this.mono_left <| nhdsWithin_mono _ <| Set.Iio_subset_Iic_self
        have h_right : ContinuousWithinAt global_peano (Set.Ioi (2 * n + 2)) (2 * n + 2) := by
          have h_right : ContinuousOn global_peano (Set.Icc (2 * n + 2 : ℝ) (2 * n + 4)) := by
            convert h_cont ( n + 1 ) using 1 ; push_cast ; ring;
          have := h_right ( 2 * n + 2 ) ⟨ by linarith, by linarith ⟩;
          rw [ Metric.continuousWithinAt_iff ] at *;
          exact fun ε hε => by obtain ⟨ δ, hδ, H ⟩ := this ε hε; exact ⟨ Min.min δ 2, lt_min hδ zero_lt_two, fun x hx₁ hx₂ => H ⟨ by linarith [ hx₁.out ], by linarith [ hx₁.out, abs_lt.mp hx₂, min_le_left δ 2, min_le_right δ 2 ] ⟩ ( by exact lt_of_lt_of_le hx₂ ( min_le_left _ _ ) ) ⟩ ;
        exact continuousAt_iff_continuous_left'_right'.mpr ⟨ h_left, h_right ⟩;
      grind

/-
The range of the Cantor function with parameter 1/3 is contained in [0, 1.5].
-/
lemma range_cantorFunction_third_subset_Icc_three_halves : Set.range (Cardinal.cantorFunction (1/3)) ⊆ Set.Icc 0 (3/2) := by
  intro x hx
  obtain ⟨y, rfl⟩ := hx
  have h_bound : ∀ (x : ℕ → Bool), (Cardinal.cantorFunction (1/3) x) ≤ 3/2 := by
    intro x
    have h_sum : ∑' (n : ℕ), (1/3 : ℝ) ^ n * (if x n = Bool.true then 1 else 0) ≤ ∑' (n : ℕ), (1/3 : ℝ) ^ n := by
      exact Summable.tsum_le_tsum ( fun n => mul_le_of_le_one_right ( by positivity ) ( by split_ifs <;> norm_num ) ) ( by exact Summable.of_nonneg_of_le ( fun n => by positivity ) ( fun n => mul_le_of_le_one_right ( by positivity ) ( by split_ifs <;> norm_num ) ) ( summable_geometric_of_lt_one ( by norm_num ) ( by norm_num ) ) ) ( by exact summable_geometric_of_lt_one ( by norm_num ) ( by norm_num ) );
    convert h_sum using 1 ; norm_num [ Cardinal.cantorFunction ];
    · exact tsum_congr fun n => by unfold Cardinal.cantorFunctionAux; aesop;
    · rw [ tsum_geometric_of_lt_one ] <;> norm_num
  have h_nonneg : ∀ (x : ℕ → Bool), 0 ≤ (Cardinal.cantorFunction (1/3) x) := by
    intro x
    simp [Cardinal.cantorFunction];
    apply_rules [ tsum_nonneg ] ; norm_num [ Cardinal.cantorFunctionAux ];
    exact fun i => by cases x i <;> norm_num;
  exact ⟨h_nonneg y, h_bound y⟩

/-
A surjective Peano map from the unit interval to the unit square.
-/
def peano_map_surj (t : Set.Icc (0 : ℝ) 1) : Set.Icc (0 : ℝ) 1 × Set.Icc (0 : ℝ) 1 :=
  let (u, v) := cantor_extension (t.val * 1.5)
  (retraction_Icc u, retraction_Icc v)

lemma continuous_peano_map_surj : Continuous peano_map_surj := by
  -- The peano_map_surj is a composition of continuous functions, hence it is continuous.
  have h_cont : Continuous (fun x : Set.Icc (0 : ℝ) 1 => cantor_extension x.val) := by
    exact continuous_cantor_extension.comp continuous_subtype_val;
  convert h_cont using 1;
  constructor;
  · exact?;
  · intro h_cont
    have h_cont_retraction : Continuous (fun x : ℝ => retraction_Icc x) := by
      exact continuous_retraction_Icc
    have h_cont_peano : Continuous (fun x : ℝ => (retraction_Icc (cantor_extension x).1, retraction_Icc (cantor_extension x).2)) := by
      exact Continuous.prodMk ( h_cont_retraction.comp ( continuous_fst.comp ( continuous_cantor_extension ) ) ) ( h_cont_retraction.comp ( continuous_snd.comp ( continuous_cantor_extension ) ) )
    exact (by
    convert h_cont_peano.comp ( show Continuous fun t : Set.Icc ( 0 : ℝ ) 1 => ( t : ℝ ) * 1.5 by continuity ) using 1)

/-
The map peano_map_surj is surjective onto the unit square.
-/
lemma surjective_peano_map_surj : Function.Surjective peano_map_surj := by
  intro y;
  -- By surjectivity of `peano_extended`, there exists `x ∈ [0, 1.5]` such that `peano_extended x = y`.
  obtain ⟨x, hx⟩ : ∃ x : ℝ, x ∈ Set.Icc (0 : ℝ) 1.5 ∧ peano_extended x = (y.1.val, y.2.val) := by
    have := surjective_peano_extended_on_Icc;
    exact this ⟨ y.1.2, y.2.2 ⟩;
  use ⟨x / 1.5, by
    exact ⟨ div_nonneg hx.1.1 ( by norm_num ), div_le_one_of_le₀ hx.1.2 ( by norm_num ) ⟩⟩
  generalize_proofs at *;
  unfold peano_map_surj;
  norm_num +zetaDelta at *;
  unfold peano_extended at hx; aesop;

/-
A scaled Peano map that maps the real line (via retraction) to the square [-n-1, n+1] x [-n-1, n+1].
-/
def peano_on_square_surj (n : ℕ) (t : ℝ) : ℝ × ℝ :=
  let (u, v) := peano_map_surj (retraction_Icc t)
  let s := (2 * n + 2 : ℝ)
  (s * u - (n + 1), s * v - (n + 1))

/-
The scaled surjective Peano map is continuous.
-/
lemma continuous_peano_on_square_surj (n : ℕ) : Continuous (peano_on_square_surj n) := by
  apply_rules [ Continuous.prodMk, Continuous.mul, Continuous.sub, continuous_const ];
  · apply_rules [ Continuous.min, Continuous.max, continuous_const, continuous_id ];
    exact Continuous.fst ( Classical.choose_spec exists_extension_cantor_surjection |>.1.comp <| Continuous.mul ( continuous_subtype_val.comp continuous_retraction_Icc ) continuous_const );
  · apply_rules [ Continuous.min, Continuous.max, continuous_const, continuous_id ];
    apply_rules [ Continuous.snd, Continuous.mul, continuous_const, continuous_id ];
    apply_rules [ Continuous.comp, continuous_const, continuous_id ];
    any_goals continuity;
    · exact Classical.choose_spec exists_extension_cantor_surjection |>.1;
    · apply_rules [ Continuous.mul, continuous_const, continuous_subtype_val.comp continuous_retraction_Icc ]

/-
The scaled Peano map is surjective onto the square [-n-1, n+1] x [-n-1, n+1].
-/
lemma surjective_peano_on_square_surj (n : ℕ) : Set.SurjOn (peano_on_square_surj n) Set.univ (Set.prod (Set.Icc (-(n + 1 : ℝ)) (n + 1)) (Set.Icc (-(n + 1 : ℝ)) (n + 1))) := by
  intro x hx;
  -- Let's choose any $t \in [0, 1]$ such that $peano_map_surj t = (u, v)$ where $u = \frac{x.1 + n + 1}{2n + 2}$ and $v = \frac{x.2 + n + 1}{2n + 2}$.
  obtain ⟨t, ht⟩ : ∃ t : Set.Icc (0 : ℝ) 1, peano_map_surj t = (⟨(x.1 + n + 1) / (2 * n + 2), by
    exact ⟨ div_nonneg ( by linarith [ hx.1.1 ] ) ( by linarith ), div_le_one_of_le₀ ( by linarith [ hx.1.2 ] ) ( by linarith ) ⟩⟩, ⟨(x.2 + n + 1) / (2 * n + 2), by
    exact ⟨ div_nonneg ( by linarith [ hx.2.1 ] ) ( by linarith ), div_le_one_of_le₀ ( by linarith [ hx.2.2 ] ) ( by linarith ) ⟩⟩) := by
    exact surjective_peano_map_surj _
  generalize_proofs at *;
  unfold peano_on_square_surj;
  use t.val;
  field_simp;
  rw [ show retraction_Icc ( t : ℝ ) = t from ?_ ];
  · simp +zetaDelta at *;
    exact Prod.mk_inj.mpr ⟨ by rw [ ht ] ; norm_num; nlinarith [ mul_div_cancel₀ ( x.1 + n + 1 ) ( by linarith : ( 2 * n + 2 : ℝ ) ≠ 0 ) ], by rw [ ht ] ; norm_num; nlinarith [ mul_div_cancel₀ ( x.2 + n + 1 ) ( by linarith : ( 2 * n + 2 : ℝ ) ≠ 0 ) ] ⟩;
  · exact Subtype.ext <| retraction_Icc_val_eq_self t.2

/-
A piece of the surjective global Peano curve.
-/
def piece_surj (n : ℕ) (t : ℝ) : ℝ × ℝ :=
  if t ≤ 1 then peano_on_square_surj n t
  else segment_R2 (peano_on_square_surj n 1) (peano_on_square_surj (n + 1) 0) (t - 1)

lemma continuous_piece_surj (n : ℕ) : Continuous (piece_surj n) := by
  refine' Continuous.if _ _ _;
  · erw [ frontier_Iic ] ; norm_num [ segment_R2 ];
  · exact?;
  · exact continuous_segment_R2 _ _ |> Continuous.comp <| continuous_sub_right _

/-
A global surjective Peano map from the reals to the plane.
-/
def global_peano_surj (t : ℝ) : ℝ × ℝ :=
  if t ≤ 0 then peano_on_square_surj 0 0
  else
    let n := Nat.floor (t / 2)
    let rem := t - 2 * n
    piece_surj n rem

/-
The global surjective Peano map is continuous.
-/
lemma continuous_global_peano_surj : Continuous global_peano_surj := by
  refine' continuous_iff_continuousAt.mpr _;
  intro x
  by_cases hx : x ≤ 0;
  · by_cases hx' : x = 0;
    · -- For t approaching 0 from the left, the function is constant, so it's continuous.
      have h_left : Filter.Tendsto (fun t => global_peano_surj t) (nhdsWithin 0 (Set.Iio 0)) (nhds (global_peano_surj 0)) := by
        have h_left : ∀ᶠ t in nhdsWithin 0 (Set.Iio 0), global_peano_surj t = peano_on_square_surj 0 0 := by
          exact Filter.eventually_of_mem self_mem_nhdsWithin fun t ht => if_pos ht.out.le;
        rw [ Filter.tendsto_congr' h_left ] ; norm_num [ hx' ];
        unfold global_peano_surj; norm_num [ hx' ] ;
      have h_right : Filter.Tendsto (fun t => global_peano_surj t) (nhdsWithin 0 (Set.Ioi 0)) (nhds (global_peano_surj 0)) := by
        have h_piece : ∀ᶠ t in nhdsWithin 0 (Set.Ioi 0), global_peano_surj t = piece_surj 0 t := by
          filter_upwards [ Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, zero_lt_one ⟩ ] with t ht using by rw [ global_peano_surj ] ; rw [ show Nat.floor ( t / 2 ) = 0 from Nat.floor_eq_zero.mpr <| by linarith [ ht.1, ht.2 ] ] ; aesop;
        rw [ Filter.tendsto_congr' h_piece ];
        convert Filter.Tendsto.mono_left ( continuous_piece_surj 0 |> Continuous.continuousAt ) inf_le_left using 1 ; norm_num [ piece_surj ];
        unfold global_peano_surj; norm_num;
      exact hx'.symm ▸ continuousAt_iff_continuous_left'_right'.mpr ⟨ h_left, h_right ⟩;
    · rw [ continuousAt_congr ];
      exacts [ show ContinuousAt ( fun t => peano_on_square_surj 0 0 ) x from continuousAt_const, Filter.eventuallyEq_of_mem ( Iio_mem_nhds ( lt_of_le_of_ne hx hx' ) ) fun t ht => if_pos ht.out.le ];
  · by_cases hx' : ∃ n : ℕ, x = 2 * n;
    · obtain ⟨n, hn⟩ : ∃ n : ℕ, x = 2 * n := hx'
      have h_lhs : Filter.Tendsto (fun t => global_peano_surj t) (nhdsWithin x (Set.Iio x)) (nhds (piece_surj (n - 1) 2)) := by
        have h_lhs : ∀ᶠ t in nhdsWithin x (Set.Iio x), global_peano_surj t = piece_surj (n - 1) (t - 2 * (n - 1)) := by
          rw [ eventually_nhdsWithin_iff ];
          rw [ Metric.eventually_nhds_iff ];
          use 1; norm_num [ hn ];
          intro y hy₁ hy₂; rcases n with ( _ | n ) <;> norm_num [ global_peano_surj ] at *;
          · linarith;
          · rw [ if_neg ( by linarith [ abs_lt.mp hy₁ ] ) ];
            norm_num [ show ⌊y / 2⌋₊ = n by exact Nat.floor_eq_iff ( by linarith [ abs_lt.mp hy₁ ] ) |>.2 ⟨ by linarith [ abs_lt.mp hy₁ ], by linarith [ abs_lt.mp hy₁ ] ⟩ ];
        rw [ Filter.tendsto_congr' h_lhs ] ; convert Filter.Tendsto.comp ( continuous_piece_surj ( n - 1 ) |> Continuous.continuousAt ) ( continuousWithinAt_id.sub continuousWithinAt_const ) using 2 ; norm_num [ hn ] ; ring;
      have h_rhs : Filter.Tendsto (fun t => global_peano_surj t) (nhdsWithin x (Set.Ioi x)) (nhds (piece_surj n 0)) := by
        have h_rhs : ∀ᶠ t in nhdsWithin x (Set.Ioi x), global_peano_surj t = piece_surj n (t - 2 * n) := by
          filter_upwards [ Ioo_mem_nhdsGT_of_mem ⟨ le_rfl, show x < 2 * ( n + 1 ) by linarith ⟩ ] with t ht;
          unfold global_peano_surj;
          norm_num [ show ⌊t / 2⌋₊ = n by exact Nat.floor_eq_iff ( by linarith [ ht.1 ] ) |>.2 ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩ ];
          exact fun h => False.elim <| h.not_lt <| by linarith [ ht.1 ] ;
        rw [ Filter.tendsto_congr' h_rhs ] ; exact Continuous.continuousWithinAt ( by exact continuous_piece_surj n |> Continuous.comp <| continuous_sub_right _ ) |> fun h => h.trans <| by norm_num [ hn ] ;
      have h_eq : piece_surj (n - 1) 2 = piece_surj n 0 := by
        rcases n with ( _ | n ) <;> norm_num [ piece_surj ] at *;
        · linarith;
        · unfold segment_R2; norm_num;
      have h_cont : ContinuousAt global_peano_surj x := by
        refine' continuousAt_iff_continuous_left'_right'.mpr _;
        simp_all +decide [ ContinuousWithinAt ];
        convert And.intro h_lhs h_rhs using 2 <;> norm_num [ hn, global_peano_surj ];
        · exact fun h => False.elim <| h.not_lt <| by positivity;
        · exact fun h => False.elim <| h.not_lt <| by positivity;
      exact h_cont;
    · -- Since $x$ is not of the form $2n$, there exists an $n$ such that $2n < x < 2(n+1)$.
      obtain ⟨n, hn⟩ : ∃ n : ℕ, 2 * n < x ∧ x < 2 * (n + 1) := by
        exact ⟨ ⌊x / 2⌋₊, lt_of_le_of_ne ( by linarith [ Nat.floor_le ( show 0 ≤ x / 2 by linarith ) ] ) fun h => hx' ⟨ _, h.symm ⟩, by linarith [ Nat.lt_floor_add_one ( x / 2 ) ] ⟩;
      -- Since $2n < x < 2(n+1)$, we have $global_peano_surj(x) = piece_surj(n, x - 2n)$.
      have h_eq : ∀ᶠ t in nhds x, global_peano_surj t = piece_surj n (t - 2 * n) := by
        filter_upwards [ Ioo_mem_nhds hn.1 hn.2 ] with t ht;
        unfold global_peano_surj;
        rw [ if_neg ( by linarith [ ht.1 ] ) ];
        norm_num [ show ⌊t / 2⌋₊ = n by exact Nat.floor_eq_iff ( by linarith [ ht.1 ] ) |>.2 ⟨ by linarith [ ht.1 ], by linarith [ ht.2 ] ⟩ ];
      exact ContinuousAt.congr ( show ContinuousAt ( fun t => piece_surj n ( t - 2 * n ) ) x from ContinuousAt.comp ( continuous_piece_surj n |> Continuous.continuousAt ) ( continuousAt_id.sub continuousAt_const ) ) ( Filter.eventuallyEq_of_mem h_eq fun t ht => ht.symm )

/-
The global surjective Peano map is surjective.
-/
lemma surjective_global_peano_surj : Function.Surjective global_peano_surj := by
  intro y
  obtain ⟨n, hn⟩ : ∃ n : ℕ, y ∈ Set.prod (Set.Icc (-(n + 1 : ℝ)) (n + 1)) (Set.Icc (-(n + 1 : ℝ)) (n + 1)) := by
    exact ⟨ Nat.ceil ( |y.1| + |y.2| ), ⟨ ⟨ by cases abs_cases y.1 <;> cases abs_cases y.2 <;> linarith [ Nat.le_ceil ( |y.1| + |y.2| ) ], by cases abs_cases y.1 <;> cases abs_cases y.2 <;> linarith [ Nat.le_ceil ( |y.1| + |y.2| ) ] ⟩, ⟨ by cases abs_cases y.1 <;> cases abs_cases y.2 <;> linarith [ Nat.le_ceil ( |y.1| + |y.2| ) ], by cases abs_cases y.1 <;> cases abs_cases y.2 <;> linarith [ Nat.le_ceil ( |y.1| + |y.2| ) ] ⟩ ⟩ ⟩;
  -- By `surjective_peano_on_square_surj n`, there exists `t' \in R` such that `peano_on_square_surj n t' = y`.
  obtain ⟨t', ht'⟩ : ∃ t' : ℝ, peano_on_square_surj n t' = y := by
    have := surjective_peano_on_square_surj n;
    exact this hn |> fun ⟨ t', ht', ht'' ⟩ => ⟨ t', ht'' ⟩;
  -- By `surjective_peano_on_square_surj n`, there exists `t' \in [0, 1]` such that `peano_on_square_surj n t' = y`.
  obtain ⟨t', ht'⟩ : ∃ t' ∈ Set.Icc 0 1, peano_on_square_surj n t' = y := by
    -- By definition of `peano_on_square_surj`, if `t'` is not in `[0, 1]`, then `peano_on_square_surj n t'` is equal to `peano_on_square_surj n (retraction_Icc t')`.
    have h_retraction : peano_on_square_surj n t' = peano_on_square_surj n (retraction_Icc t') := by
      unfold peano_on_square_surj;
      unfold retraction_Icc; aesop;
    exact ⟨ _, ⟨ by exact ( retraction_Icc t' ) |>.2.1, by exact ( retraction_Icc t' ) |>.2.2 ⟩, h_retraction.symm.trans ht' ⟩;
  use 2 * n + t';
  unfold global_peano_surj;
  split_ifs <;> norm_num at *;
  · norm_num [ show t' = 0 by linarith ] at *;
    norm_cast at * ; aesop;
  · norm_num [ show ⌊ ( 2 * n + t' : ℝ ) / 2⌋₊ = n by exact Nat.floor_eq_iff ( by linarith ) |>.2 ⟨ by linarith, by linarith ⟩ ];
    unfold piece_surj; aesop;

/-
There exists a continuous surjection from the real line to the plane.
-/
theorem exists_continuous_surjection_R_R2 : ∃ f : ℝ → ℝ × ℝ, Continuous f ∧ Function.Surjective f := by
  exact ⟨ _, continuous_global_peano_surj, surjective_global_peano_surj ⟩
